const exams={
2019:{title:'TDPI Libre 2019',source:'Basado en el examen oficial ICS del 27/10/2019',questions:[
['En una radiografía PA de tórax, ¿qué criterio NO es apropiado como criterio de calidad?',['Que se incluyan los vértices y los ángulos costofrénicos','Que todas las vértebras dorsales sean claramente visibles a través de la silueta cardiaca','Que las escápulas queden fuera de los campos pulmonares','Que las bases pulmonares queden correctamente incluidas'],1],
['La proyección West Point se utiliza para estudiar principalmente:',['El calcáneo','La rótula','La cadera','La articulación glenohumeral'],3],
['La proyección axial de Dunn permite valorar especialmente:',['La esfericidad de la cabeza humeral','La esfericidad de la cabeza femoral','El platillo tibial','La angulación rotuliana'],1],
['La radiación que puede salir del tubo de rayos X y no forma parte del haz útil se denomina:',['Radiación directa','Radiación indirecta','Radiación dispersa','Radiación de fuga'],3],
['Una medida eficaz para disminuir la radiación dispersa es:',['Aumentar el volumen irradiado','Reducir el campo irradiado mediante colimación','Aumentar siempre el kV','Eliminar las rejillas antidifusoras'],1],
['La proyección inlet de pelvis permite valorar principalmente:',['La parte inferior y anterior del anillo pélvico','La parte superior y posterior del anillo pélvico','Únicamente las luxaciones de cadera','El acetábulo sin valorar el anillo pélvico'],1],
['En protección radiológica, un efecto estocástico se caracteriza porque:',['Tiene un umbral y la gravedad aumenta con la dosis','La probabilidad aumenta con la dosis y la gravedad no depende de ella','Solo aparece por encima de una dosis umbral','Su gravedad siempre es proporcional a la dosis'],1],
['En la fila distal del carpo, de radial a cubital, el orden correcto es:',['Escafoides, semilunar, grande y ganchoso','Trapecio, trapezoide, grande y ganchoso','Ganchoso, grande, trapezoide y trapecio','Escafoides, trapezoide, semilunar y ganchoso'],1],
['Una imagen radiológica digital está formada esencialmente por:',['Vóxeles exclusivamente','Píxeles que pueden codificarse digitalmente','Solo señales analógicas','Imágenes que no pueden procesarse después de adquirirlas'],1],
['La unidad del Sistema Internacional utilizada para expresar la dosis absorbida es:',['Sievert','Gray','Becquerel','Roentgen'],1],
['Los estudios dinámicos de la columna cervical suelen realizarse mediante:',['Flexión y extensión','Bending exclusivamente','Proyecciones oblicuas','Método de Judd'],0],
['El seno paranasal situado por debajo de la silla turca es el:',['Frontal','Etmoidal','Esfenoidal','Maxilar'],2],
['Una radiografía PA de tórax en espiración puede ser especialmente útil para detectar:',['Pequeños neumotórax','Mejor la silueta cardiaca','Fracturas costales únicamente','Derrames pleurales mínimos exclusivamente'],0],
['En densitometría de columna lumbar, para obtener un estudio interpretable se necesita valorar como mínimo:',['Una vértebra','Dos vértebras','Cinco vértebras','Toda la columna dorsal'],1],
['En el espectro electromagnético, los rayos X se encuentran entre:',['Ultravioleta y rayos gamma','Microondas y ultravioleta','Infrarrojos y microondas','Rayos gamma y ondas de radio'],0],
['Los rayos X y gamma se caracterizan por presentar:',['Longitud de onda corta y frecuencia alta','Longitud de onda corta y frecuencia baja','Longitud de onda larga y frecuencia alta','Longitud de onda larga y frecuencia baja'],0],
['El efecto Compton produce principalmente:',['Radiación dispersa','Producción de pares','Una imagen necesariamente más clara','Ausencia de ionización'],0],
['Para una ortopantomografía, el posicionamiento habitual de la arcada dental requiere:',['Morder correctamente el bloque de mordida con los incisivos','Morder solo con los molares','Mantener siempre la boca abierta','Elevar al máximo la cabeza'],0],
['Para confirmar la presencia de un derrame pleural libre, una proyección especialmente útil es:',['Lordótica','Espiratoria','Decúbito lateral con rayo horizontal','Supina'],2],
['Cuando se sospecha una lesión mamográfica que no se identifica mediante ecografía, una opción de biopsia adecuada es:',['Biopsia guiada por RM en todos los casos','Repetir indefinidamente la mamografía','Biopsia ecográfica de una lesión no visible','Biopsia estereotáxica'],3]
]},
2022:{title:'TDPI Estabilización 2022',source:'Basado en el primer ejercicio oficial de estabilización ICS 2022',questions:[
['El programa de garantía de calidad de una unidad asistencial de radiodiagnóstico debe estar disponible:',['Solo después de seis meses de actividad','Cuando lo solicite el paciente','Antes de la puesta en funcionamiento de la unidad','A partir del segundo trimestre de actividad'],2],
['Para personas en formación o estudiantes de 16 a 18 años, el límite anual de dosis efectiva indicado en la normativa de protección radiológica es:',['50 mSv','15 mSv','6 mSv','1 mSv'],2],
['¿Cuál es la combinación correcta de magnitudes y unidades radiológicas?',['Dosis absorbida–Sv; dosis equivalente–Gy','Dosis absorbida–Gy; dosis equivalente–Sv','Dosis absorbida–Bq; dosis equivalente–Gy','Dosis absorbida–Gy; dosis equivalente–Bq'],1],
['En una trabajadora embarazada expuesta profesionalmente, la declaración del embarazo:',['Impide continuar trabajando con radiaciones','Obliga siempre a cambiar de puesto','No implica automáticamente dejar de trabajar, pero exige aplicar las medidas de protección correspondientes','Permite trabajar sin ninguna medida adicional'],2],
['En intervencionismo, una opción adecuada de protección frente a la radiación dispersa es utilizar:',['Un delantal exclusivamente posterior','Protección integral adecuada al procedimiento','Ninguna protección si se usa fluoroscopia','Solo protección tiroidea'],1],
['Una proyección radiológica se define atendiendo fundamentalmente a:',['La dirección del haz central respecto al cuerpo','El color del detector','La dosis recibida por el paciente','El tamaño del chasis'],0],
['Para demostrar determinadas estructuras del primer dedo de la mano puede utilizarse una proyección:',['Lateral de rodilla','AP de pie','PA con la mano en la posición indicada','Oblicua de hombro'],2],
['En la proyección AP de cóccix, la angulación del rayo central se dirige habitualmente:',['15° caudal hacia la línea media próxima a la sínfisis','45° craneal','90° lateral','Sin angulación en todos los pacientes'],0],
['En la nomenclatura dental de la FDI, la pieza 15 corresponde al:',['Cuadrante superior izquierdo','Cuadrante inferior derecho','Cuadrante inferior izquierdo','Cuadrante superior derecho'],3],
['En una proyección lateral de húmero, un criterio de calidad es:',['Ver los epicóndilos sin rotación significativa','Superponer siempre el troquíter sobre el cuello','Mostrar únicamente el húmero proximal','No incluir la articulación del codo'],0],
['La posición de Sims corresponde a:',['Decúbito lateral con una pierna flexionada y el brazo superior adelantado','Decúbito supino con ambas piernas extendidas','Bipedestación con brazos elevados','Decúbito prono con piernas extendidas'],0],
['En la fila distal del tarso, el orden de los huesos desde medial hacia lateral incluye:',['Cuneiformes y cuboides','Escafoides y cuboides únicamente','Astrágalo y calcáneo','Talus y navicular exclusivamente'],0],
['La emisión de electrones desde el filamento del cátodo por efecto del calentamiento se denomina:',['Emisión fotoeléctrica','Emisión termoiónica','Emisión Compton','Emisión secundaria'],1],
['La espectroscopia por resonancia magnética permite principalmente:',['Caracterizar y cuantificar metabolitos tisulares','Medir exclusivamente la densidad ósea','Obtener únicamente imágenes de difusión','Sustituir siempre a la TC'],0],
['En RM fetal se utilizan secuencias ultrarrápidas principalmente para:',['Evitar en gran medida los artefactos derivados del movimiento fetal','Aumentar la dosis de radiación','Administrar siempre gadolinio','Sedarlo obligatoriamente'],0],
['Para reducir el artefacto de movimiento en una RM fetal es especialmente útil:',['Utilizar secuencias de adquisición rápida','Aumentar mucho el tiempo de adquisición','Reducir la velocidad de adquisición','Administrar contraste en todos los casos'],0],
['Una fractura vertebral lumbar puede alterar la medición densitométrica porque:',['Puede modificar artificialmente la DMO y debe valorarse su exclusión','Siempre aumenta la DMO de forma fiable','Nunca afecta a la interpretación','Obliga siempre a estudiar L5'],0],
['Una exploración con contraste o material radiopaco realizada poco antes de una densitometría lumbar puede:',['No tener ninguna influencia','Interferir con la medición de la DMO','Mejorar la precisión de la prueba','Convertir la DMO en una medida de dosis'],1],
['En ecografía fetal por RM, una característica importante es:',['La principal indicación incluye anomalías del sistema nervioso central','La sedación fetal es siempre obligatoria','El gadolinio se administra de rutina','Es siempre la primera prueba de cribado fetal'],0],
['La persona atendida es titular de la información relativa a su proceso asistencial y estado de salud, respetándose también:',['El derecho a no ser informada si así lo manifiesta','El derecho del personal a decidir unilateralmente','La obligación de informar a cualquier tercero','La prohibición absoluta de acceso a la historia clínica'],0]
]}};
let current=null,index=0,score=0;
const exam=document.getElementById('exam');
function render(){const q=exams[current].questions[index];exam.hidden=false;exam.innerHTML=`<div class="study-material"><p class="eyebrow">${exams[current].title.toUpperCase()}</p><h2>Pregunta ${index+1} de ${exams[current].questions.length}</h2><p>${q[0]}</p><div class="answer-grid">${q[1].map((a,i)=>`<button class="answer-option" data-i="${i}">${String.fromCharCode(65+i)}) ${a}</button>`).join('')}</div><p class="exam-progress">Aciertos: ${score} · ${exams[current].source}</p></div>`;window.scrollTo({top:exam.offsetTop-20,behavior:'smooth'});document.querySelectorAll('.answer-option').forEach(b=>b.onclick=()=>answer(+b.dataset.i));}
function answer(i){const q=exams[current].questions[index];document.querySelectorAll('.answer-option').forEach((b,n)=>{b.disabled=true;if(n===q[2])b.classList.add('correct');if(n===i&&i!==q[2])b.classList.add('wrong')});if(i===q[2])score++;setTimeout(()=>{index++;if(index<exams[current].questions.length)render();else finish()},650)}
function finish(){exam.innerHTML=`<div class="study-material"><p class="eyebrow">SIMULACRO TERMINADO</p><h2>🏆 ${exams[current].title}</h2><p class="final-score">${score} / ${exams[current].questions.length}</p><p>Has terminado este simulacro. La puntuación se ha calculado sobre las preguntas disponibles en esta versión.</p><button class="secondary-button" id="again">Repetir</button><a class="module-action exam-home" href="examenes-ics.html">Volver a exámenes ICS</a></div>`;document.getElementById('again').onclick=()=>{index=0;score=0;render()}}
document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>{current=b.dataset.exam;index=0;score=0;render()});
