const official=[...exams[2019].questions,...exams[2022].questions];
const extra=[
['En un tubo de rayos X, la emisión termoiónica tiene lugar principalmente en:',['El filamento del cátodo','El blanco del ánodo','El colimador','El detector'],0,'Tubo de RX','fácil'],
['La copa de enfoque del cátodo sirve principalmente para:',['Concentrar y dirigir los electrones hacia el blanco','Refrigerar el detector','Filtrar el haz útil','Medir la dosis'],0,'Tubo de RX','fácil'],
['En un tubo de rayos X, aumentar el mA manteniendo el resto constante aumenta principalmente:',['El número de electrones disponibles y la cantidad de radiación','La energía máxima de los fotones','La distancia foco-receptor','El tamaño del detector'],0,'Técnica radiográfica','fácil'],
['La función principal del colimador es:',['Limitar el campo de radiación al área de interés','Aumentar la radiación dispersa','Cambiar la frecuencia de los rayos X','Eliminar la necesidad de posicionamiento'],0,'Técnica radiográfica','fácil'],
['Una consecuencia habitual de aumentar la distancia foco-receptor manteniendo la técnica ajustada es:',['Disminuir la intensidad en el receptor si no se compensa','Aumentar siempre la dosis al paciente','Aumentar la magnificación','Eliminar la radiación dispersa'],0,'Técnica radiográfica','medio'],
['El principio de justificación en protección radiológica implica que:',['Una exposición debe aportar un beneficio que la justifique','Toda exposición debe utilizar la máxima dosis','La colimación es opcional','Solo se aplica al personal sanitario'],0,'Protección radiológica','medio'],
['La dosis absorbida se expresa en:',['Gray','Sievert','Becquerel','Tesla'],0,'Protección radiológica','fácil'],
['La actividad de una sustancia radiactiva se expresa en:',['Becquerel','Gray','Sievert','Culombio'],0,'Medicina nuclear','fácil'],
['En una imagen digital, aumentar la matriz manteniendo el campo de visión puede producir:',['Píxeles de menor tamaño','Píxeles de mayor tamaño','Menor número de píxeles','Desaparición de la resolución'],0,'Radiología digital','medio'],
['El PACS está relacionado principalmente con:',['Gestión, almacenamiento y distribución de imágenes','Generación de rayos X','Administración de contraste','Medición de actividad radiactiva'],0,'Radiología digital','fácil'],
['En ecografía, la impedancia acústica depende principalmente de:',['La densidad del medio y la velocidad del sonido en él','La dosis absorbida','El número atómico exclusivamente','La tensión del tubo'],0,'Ecografía','medio'],
['Cuando existe una gran diferencia de impedancia acústica entre dos medios, la reflexión en la interfaz tiende a ser:',['Mayor','Menor','Nula siempre','Independiente de la interfaz'],0,'Ecografía','medio'],
['En TC, aumentar el número de detectores por fila permite principalmente:',['Adquirir más información por rotación y favorecer adquisiciones más rápidas','Eliminar completamente el ruido','Sustituir el contraste','Evitar toda reconstrucción'],0,'Tomografía computarizada','medio'],
['En TC, el pitch relaciona principalmente:',['El avance de la mesa por rotación con la colimación total','El kV con el mA','La dosis con el contraste','El FOV con la matriz'],0,'Tomografía computarizada','difícil'],
['En RM, el gadolinio se utiliza como:',['Agente de contraste paramagnético en determinadas exploraciones','Medio de contraste yodado','Material radiactivo','Agente ecográfico de microburbujas'],0,'Resonancia magnética','fácil'],
['Una secuencia de difusión en RM es especialmente sensible a:',['El movimiento microscópico de las moléculas de agua','La radiación dispersa','La actividad radiactiva','La densidad mineral ósea'],0,'Resonancia magnética','medio'],
['En radiografía, una rejilla antidifusora puede mejorar el contraste porque:',['Reduce parte de la radiación dispersa que alcanza el receptor','Aumenta la radiación dispersa','Elimina la radiación primaria','Reduce el tamaño del foco'],0,'Técnica radiográfica','medio'],
['La borrosidad por movimiento se reduce principalmente mediante:',['Inmovilización y un tiempo de exposición adecuado','Aumentando siempre el tiempo de exposición','Aumentando la distancia objeto-receptor','Eliminando la colimación'],0,'Técnica radiográfica','fácil'],
['En RM, antes de entrar en la sala del imán es especialmente importante:',['Comprobar objetos y dispositivos que puedan ser incompatibles con el campo magnético','Aumentar el kV','Retirar la rejilla','Preparar un detector de panel plano'],0,'Resonancia magnética','fácil'],
['La principal ventaja del contraste de tejidos blandos de la RM se debe a:',['La sensibilidad a propiedades magnéticas y tiempos de relajación de los tejidos','La utilización de rayos X','La actividad del radionúclido','La absorción fotoeléctrica'],0,'Resonancia magnética','medio']
];
const bank=[...official.map((q,i)=>[q[0],q[1],q[2],i<20?'Técnicas de radiología convencional':'Protección y fundamentos',i%3===0?'medio':'fácil']),...extra];
const key='radtech_tests_v1';const load=()=>JSON.parse(localStorage.getItem(key)||'{}');const save=x=>localStorage.setItem(key,JSON.stringify(x));
const ws=document.getElementById('workspace');
function shuffle(a){return a.slice().sort(()=>Math.random()-0.5)}
function prepare(q){const opts=shuffle(q[1].map((text,i)=>({text,i})));return [q[0],opts.map(x=>x.text),opts.findIndex(x=>x.i===q[2]),q[3],q[4]]}
function session(title,items){let qs=items.map(prepare),pos=0,score=0;ws.hidden=false;const render=()=>{if(pos>=qs.length){const s=load();s.sessions=(s.sessions||0)+1;s.correct=(s.correct||0)+score;s.answered=(s.answered||0)+qs.length;save(s);ws.innerHTML=`<div class="study-material"><p class="eyebrow">${title.toUpperCase()}</p><h2>🏆 Sesión terminada</h2><p class="final-score">${score} / ${qs.length}</p><p>${Math.round(score/qs.length*100)}% de aciertos</p><button class="secondary-button" id="again">Repetir</button></div>`;document.getElementById('again').onclick=()=>session(title,items);return}const q=qs[pos];ws.innerHTML=`<div class="study-material"><p class="eyebrow">${title.toUpperCase()}</p><h2>Pregunta ${pos+1} de ${qs.length}</h2><p>${q[0]}</p><div class="answer-grid">${q[1].map((a,i)=>`<button class="answer-option" data-i="${i}">${String.fromCharCode(65+i)}) ${a}</button>`).join('')}</div><p class="exam-progress">Aciertos: ${score} · ${q[3]} · ${q[4]}</p></div>`;ws.scrollIntoView({behavior:'smooth',block:'start'});ws.querySelectorAll('.answer-option').forEach(b=>b.onclick=()=>{const chosen=+b.dataset.i;ws.querySelectorAll('.answer-option').forEach((x,i)=>{x.disabled=true;if(i===q[2])x.classList.add('correct');if(i===chosen&&chosen!==q[2])x.classList.add('wrong')});const data=load();data.errors=data.errors||{};const id=q[0];if(chosen!==q[2])data.errors[id]=(data.errors[id]||0)+1;else if(data.errors[id])data.errors[id]=Math.max(0,data.errors[id]-1);save(data);if(chosen===q[2])score++;setTimeout(()=>{pos++;render()},550)})};render()}
function menu(title,buttons){ws.hidden=false;ws.innerHTML=`<div class="study-material"><p class="eyebrow">${title.toUpperCase()}</p><h2>${title}</h2><div class="cards">${buttons.map((b,i)=>`<button class="module-card" data-pick="${i}"><h3>${b[0]}</h3><p>${b[1]}</p><span class="module-action">Elegir →</span></button>`).join('')}</div></div>`;ws.querySelectorAll('[data-pick]').forEach((b,i)=>b.onclick=()=>buttons[i][2]())}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='quick')session('⚡ Reto rápido',shuffle(bank).slice(0,10));if(a==='topics')menu('Test por temas',[['Radiología convencional','Fundamentos y técnica',()=>session('Radiología convencional',bank.filter(q=>q[3].includes('convencional')).slice(0,10))],['Protección y fundamentos','Radioprotección, dosis e interacción',()=>session('Protección y fundamentos',bank.filter(q=>q[3].includes('Protección')).slice(0,10))],['Radiología digital','Imagen digital y PACS',()=>session('Radiología digital',bank.filter(q=>q[3]==='Radiología digital'))],['Ecografía','Ultrasonidos',()=>session('Ecografía',bank.filter(q=>q[3]==='Ecografía'))],['TC','Tomografía computarizada',()=>session('TC',bank.filter(q=>q[3]==='Tomografía computarizada'))],['RM','Resonancia magnética',()=>session('RM',bank.filter(q=>q[3]==='Resonancia magnética'))]]);if(a==='difficulty')menu('Por dificultad',[['🌱 Aprende','Preguntas fáciles',()=>session('Aprende',bank.filter(q=>q[4]==='fácil').slice(0,10))],['⚡ Entrena','Dificultad media',()=>session('Entrena',bank.filter(q=>q[4]==='medio').slice(0,10))],['🔥 Reto','Preguntas difíciles',()=>session('Reto',bank.filter(q=>q[4]==='difícil'))]]);if(a==='errors'){const d=load(),errs=d.errors||{};const items=bank.filter(q=>errs[q[0]]>0);if(!items.length)menu('Mis errores',[['✨ Aún no tienes errores','Haz algunos tests y aquí aparecerán las preguntas que falles.',()=>{}]]);else session('🎯 Mis errores',shuffle(items).slice(0,10))}if(a==='smart'){const d=load(),errs=d.errors||{};const weak=bank.filter(q=>errs[q[0]]>0);session('🔄 Repaso inteligente',shuffle([...weak,...bank]).slice(0,10))}if(a==='progress'){const d=load();const answered=d.answered||0,correct=d.correct||0;menu('Mi progreso',[[`📊 ${correct} / ${answered}`,'Aciertos acumulados',()=>{}],[`🎯 ${Object.keys(d.errors||{}).length}`,'Preguntas con errores pendientes',()=>{}],[`🧠 ${answered?Math.round(correct/answered*100):0}%`,'Porcentaje global',()=>{}]])}});