const official=(typeof exams!=='undefined')?[...exams[2019].questions,...exams[2022].questions]:[];
const curated=[
['¿Dónde tiene lugar principalmente la emisión termoiónica en el tubo de rayos X?',['Filamento del cátodo','Blanco del ánodo','Colimador','Detector'],0,'TEMA 3','fácil'],
['¿Cuál es la función principal de la copa de enfoque?',['Concentrar y dirigir los electrones hacia el blanco','Refrigerar el detector','Filtrar el haz útil','Medir la dosis'],0,'TEMA 3','fácil'],
['¿Qué unidad corresponde a la dosis absorbida?',['Gray','Sievert','Becquerel','Tesla'],0,'Protección radiológica','fácil'],
['¿Qué unidad corresponde a la actividad radiactiva?',['Becquerel','Gray','Sievert','Tesla'],0,'Medicina nuclear','fácil'],
['¿Qué sistema se encarga de gestionar, almacenar y distribuir imágenes médicas?',['PACS','Generador','Colimador','Doppler'],0,'Radiología digital','fácil'],
['¿Qué agente se utiliza como contraste paramagnético en RM?',['Gadolinio','Bario','Yodo','Microburbujas'],0,'Resonancia magnética','fácil'],
['¿Qué parámetro de TC relaciona el avance de la mesa por rotación con la colimación total?',['Pitch','FOV','Matriz','Ventana'],0,'Tomografía computarizada','medio'],
['¿Qué permite valorar el Doppler en ecografía?',['El flujo sanguíneo','La dosis absorbida','El número atómico','La actividad radiactiva'],0,'Ecografía','fácil'],
['¿Qué efecto de la radiación implica la absorción del fotón incidente por el átomo?',['Efecto fotoeléctrico','Dispersión Thomson','Dispersión coherente exclusivamente','Efecto Doppler'],0,'TEMA 2','medio'],
['¿Qué principio de protección radiológica exige que una exposición aporte un beneficio que la justifique?',['Justificación','Optimización','Dosimetría','Colimación'],0,'Protección radiológica','medio']
];

// Banco específico y revisado del TEMA 1.
// No utiliza generación automática de preguntas a partir de frases del contenido.
const topic1Curated=[
['¿Quién descubrió los rayos X?',['Wilhelm Conrad Röntgen','Thomas Edison','Godfrey Hounsfield','Allan Cormack'],0,'TEMA 1','fácil'],
['¿En qué año descubrió Wilhelm Conrad Röntgen los rayos X?',['1895','1890','1905','1911'],0,'TEMA 1','fácil'],
['¿Qué fecha corresponde a la primera radiografía de la mano de la esposa de Röntgen?',['22 de diciembre de 1895','8 de noviembre de 1895','22 de diciembre de 1896','1 de enero de 1896'],0,'TEMA 1','medio'],
['¿Qué ocurrió el 8 de noviembre de 1895?',['Röntgen descubrió los rayos X','Röntgen realizó la primera radiografía de la mano de su esposa','Se obtuvo la primera imagen de TAC','Se desarrolló la primera RM clínica'],0,'TEMA 1','fácil'],
['¿Qué científico aparece relacionado con el descubrimiento del radio?',['Marie Curie','Röntgen','Salomon','Hounsfield'],0,'TEMA 1','fácil'],
['¿En qué año recibió Marie Curie el Premio Nobel de Química por sus trabajos relacionados con el radio y el polonio?',['1911','1895','1913','1952'],0,'TEMA 1','medio'],
['¿Quién está relacionado con el desarrollo inicial de la mamografía mediante el estudio radiológico de la mama?',['Albert Salomon','Marie Curie','Wilhelm Röntgen','Raymond Damadian'],0,'TEMA 1','medio'],
['¿En qué año se sitúa el trabajo de Salomon relacionado con la mamografía?',['1913','1911','1952','1972'],0,'TEMA 1','medio'],
['¿Qué científicos recibieron el Premio Nobel de Física de 1952 por sus trabajos fundamentales sobre la resonancia magnética nuclear?',['Félix Bloch y Edward Purcell','Hounsfield y Cormack','Lauterbur y Mansfield','Röntgen y Curie'],0,'TEMA 1','medio'],
['¿Qué acontecimiento relacionado con la tomografía computarizada se sitúa en 1972?',['Primer protocolo de TAC cerebral','Introducción del TAC helicoidal','Primeras imágenes de RM','Primera promoción de técnicos de rayos'],0,'TEMA 1','medio'],
['¿Qué investigadores aparecen relacionados con el desarrollo del PET en la cronología histórica?',['Michael E. Phelps y Edward J. Hoffman','Hounsfield y Cormack','Bloch y Purcell','Lauterbur y Mansfield'],0,'TEMA 1','difícil'],
['¿Qué acontecimiento se sitúa en 1977 en la cronología histórica del tema?',['Primera promoción de técnicos de rayos','Primer protocolo de TAC cerebral','Primeras imágenes de TAC','Introducción del TAC helicoidal'],0,'TEMA 1','medio'],
['¿Qué investigadores están asociados al desarrollo de las imágenes de TAC?',['Godfrey Hounsfield y Allan Cormack','Lauterbur y Mansfield','Bloch y Purcell','Röntgen y Salomon'],0,'TEMA 1','fácil'],
['¿En qué año se sitúa la introducción del TAC helicoidal?',['1990','1972','1979','2003'],0,'TEMA 1','medio'],
['¿En qué año se sitúa la referencia histórica a la titulación de Técnico Superior en Imagen para el Diagnóstico (TSID)?',['1995','1990','2003','2014'],0,'TEMA 1','medio'],
['¿Qué investigadores recibieron el Premio Nobel de Fisiología o Medicina de 2003 por sus descubrimientos relacionados con la resonancia magnética?',['Paul C. Lauterbur y Peter Mansfield','Godfrey Hounsfield y Allan Cormack','Félix Bloch y Edward Purcell','Michael Phelps y Edward Hoffman'],0,'TEMA 1','medio'],
['¿Qué titulación corresponde actualmente a la formación profesional superior del ámbito de la imagen para el diagnóstico y la medicina nuclear?',['Técnico Superior en Imagen para el Diagnóstico y Medicina Nuclear','Técnico Superior en Radiología Médica','Técnico Especialista en Radiodiagnóstico','Técnico Superior en Diagnóstico por Imagen'],0,'TEMA 1','fácil'],
['¿En qué se centraban buena parte de las investigaciones que precedieron al descubrimiento de los rayos X?',['En el estudio de las descargas eléctricas en gases a diferentes presiones','En el desarrollo de equipos de resonancia magnética','En la obtención de imágenes mediante ultrasonidos','En el desarrollo de detectores digitales'],0,'TEMA 1','medio'],
['¿Qué modificación del ánodo permitió mejorar las condiciones de producción de rayos X al reducir la concentración del impacto sobre una zona fija?',['La incorporación del ánodo giratorio','La eliminación del ánodo','La sustitución del ánodo por un detector digital','La incorporación de un colimador automático'],0,'TEMA 1','medio'],
['¿Qué científico está relacionado con las primeras aplicaciones militares del sónar, antecedente de las aplicaciones posteriores de los ultrasonidos?',['Paul Langevin','Wilhelm Röntgen','Godfrey Hounsfield','Allan Cormack'],0,'TEMA 1','difícil']
];

const topicSpecific=(typeof topic37Curated!=='undefined')?topic37Curated:[];
const key='radtech_tests_v2';
const load=()=>JSON.parse(localStorage.getItem(key)||'{}');
const save=x=>localStorage.setItem(key,JSON.stringify(x));
const ws=document.getElementById('workspace');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function shuffle(a){return a.slice().sort(()=>Math.random()-0.5)}
function topicFacts(topic){const lines=topic.content.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean),facts=[];for(const line of lines){if(line.length<18||/^[A-ZÁÉÍÓÚÜÑ0-9 .·→⟶()/-]{3,80}$/.test(line))continue;const m=line.match(/^(.{2,70}?)\s*(?:⟶|→|:)\s*(.{10,220})$/);if(m)facts.push({term:m[1].replace(/[•→⟶]/g,'').trim(),def:m[2].trim(),raw:line})}const seen=new Set();return facts.filter(f=>{const k=f.term+'|'+f.def;if(seen.has(k))return false;seen.add(k);return true})}
function buildTopicBank(){const out=[];if(typeof topics==='undefined')return out;Object.keys(topics).sort((a,b)=>+a-+b).forEach(n=>{if(n==='1'||n==='37')return;const t=topics[n],facts=topicFacts(t);if(!facts.length)return;shuffle(facts).slice(0,24).forEach((f,i)=>{const others=facts.filter(x=>x!==f&&x.def!==f.def&&x.term!==f.term);if(others.length<3)return;const reverse=i%3===1;let question,answers;if(reverse){question=`¿A qué concepto corresponde la siguiente descripción? «${f.def}»`;answers=[f.term,...shuffle(others).slice(0,3).map(x=>x.term)]}else{question=`¿Cuál de las siguientes afirmaciones describe correctamente ${f.term}?`;answers=[f.def,...shuffle(others).slice(0,3).map(x=>x.def)]}const difficulty=/\d|%|mm|cm|kg|kV|mA|MHz|seg|años|min|veces/i.test(f.raw)?'medio':(f.def.length>140?'difícil':'fácil');out.push([question,answers,0,`TEMA ${n}`,difficulty])})});return out}
function prepare(q){const opts=shuffle(q[1].map((text,i)=>({text,i})));return[q[0],opts.map(x=>x.text),opts.findIndex(x=>x.i===q[2]),q[3],q[4]]}
function record(q,correct){const d=load();d.errors=d.errors||{};d.stats=d.stats||{};const id=q[0];if(correct){if(d.errors[id])d.errors[id]=Math.max(0,d.errors[id]-1)}else d.errors[id]=(d.errors[id]||0)+1;d.stats.answered=(d.stats.answered||0)+1;d.stats.correct=(d.stats.correct||0)+(correct?1:0);save(d)}
function session(title,items){let qs=shuffle(items).map(prepare),pos=0,score=0;ws.hidden=false;const render=()=>{if(pos>=qs.length){ws.innerHTML=`<div class="study-material"><p class="eyebrow">${esc(title).toUpperCase()}</p><h2>🏆 Sesión terminada</h2><p class="final-score">${score} / ${qs.length}</p><p>${Math.round(score/qs.length*100)}% de aciertos</p><button class="secondary-button" id="again">Repetir</button></div>`;document.getElementById('again').onclick=()=>session(title,items);return}const q=qs[pos];ws.innerHTML=`<div class="study-material"><p class="eyebrow">${esc(title).toUpperCase()}</p><h2>Pregunta ${pos+1} de ${qs.length}</h2><p>${esc(q[0])}</p><div class="answer-grid">${q[1].map((a,i)=>`<button class="answer-option" data-i="${i}">${String.fromCharCode(65+i)}) ${esc(a)}</button>`).join('')}</div><p class="exam-progress">Aciertos: ${score}</p></div>`;ws.querySelectorAll('.answer-option').forEach(b=>b.onclick=()=>{const chosen=+b.dataset.i;ws.querySelectorAll('.answer-option').forEach((x,i)=>{x.disabled=true;if(i===q[2])x.classList.add('correct');if(i===chosen&&chosen!==q[2])x.classList.add('wrong')});const ok=chosen===q[2];if(ok)score++;record(q,ok);setTimeout(()=>{pos++;render()},450)})};render()}
function topicMenu(){const generated=[...buildTopicBank(),...topic1Curated,...topicSpecific],byTopic={};generated.forEach(q=>(byTopic[q[3]]??=[]).push(q));const entries=Object.keys(byTopic).sort((a,b)=>+a.split(' ')[1]-+b.split(' ')[1]);ws.hidden=false;ws.innerHTML=`<div class="study-material"><p class="eyebrow">TEST POR TEMAS</p><h2>📚 Elige un tema</h2><p>Cada tema tiene un banco propio de preguntas generado a partir del contenido real. El número disponible aparece en cada tarjeta.</p><div class="cards">${entries.map((n,i)=>`<button class="module-card" data-topic="${i}"><span class="module-number">${n}</span><h3>${esc((topics[n.split(' ')[1]]||{}).title||n)}</h3><p>${byTopic[n].length} preguntas disponibles</p><span class="module-action">Entrenar →</span></button>`).join('')}</div></div>`;ws.querySelectorAll('[data-topic]').forEach((b,i)=>b.onclick=()=>session(entries[i],byTopic[entries[i]]))}
function menu(title,buttons){ws.hidden=false;ws.innerHTML=`<div class="study-material"><p class="eyebrow">${esc(title).toUpperCase()}</p><h2>${esc(title)}</h2><div class="cards">${buttons.map((b,i)=>`<button class="module-card" data-pick="${i}"><h3>${esc(b[0])}</h3><p>${esc(b[1])}</p><span class="module-action">Elegir →</span></button>`).join('')}</div></div>`;ws.querySelectorAll('[data-pick]').forEach((b,i)=>b.onclick=()=>buttons[i][2]())}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const generated=buildTopicBank(),bank=[...generated,...topic1Curated,...curated,...topicSpecific,...official.map((q,i)=>[q[0],q[1],q[2],`ICS ${i<60?'2019':'2022'}`,i%4===0?'difícil':'medio'])],a=b.dataset.action;if(a==='quick')session('⚡ Reto rápido',shuffle(bank).slice(0,10));if(a==='topics')topicMenu();if(a==='difficulty')menu('Por dificultad',[['🌱 Aprende','Preguntas fáciles',()=>session('Aprende',bank.filter(q=>q[4]==='fácil').slice(0,15))],['⚡ Entrena','Dificultad media',()=>session('Entrena',bank.filter(q=>q[4]==='medio').slice(0,15))],['🔥 Reto','Preguntas difíciles',()=>session('Reto',bank.filter(q=>q[4]==='difícil').slice(0,15))]]);if(a==='errors'){const d=load(),errs=d.errors||{},items=bank.filter(q=>errs[q[0]]>0);if(!items.length)menu('Mis errores',[['✨ Todavía no hay errores','Haz algunos tests y aquí aparecerán las preguntas que falles.',()=>{}]]);else session('🎯 Mis errores',shuffle(items).slice(0,15))}if(a==='smart'){const d=load(),errs=d.errors||{},weak=bank.filter(q=>errs[q[0]]>0),fresh=shuffle(bank.filter(q=>!errs[q[0]])).slice(0,8);session('🔄 Repaso inteligente',shuffle([...weak,...fresh]).slice(0,15))}if(a==='progress'){const d=load(),s=d.stats||{},answered=s.answered||0,correct=s.correct||0;menu('Mi progreso',[[`📊 ${correct} / ${answered}`,'Aciertos acumulados',()=>{}],[`🎯 ${Object.keys(d.errors||{}).length}`,'Preguntas con errores pendientes',()=>{}],[`🧠 ${answered?Math.round(correct/answered*100):0}%`,'Porcentaje global',()=>{}]])}});