// Banco curado del TEMA 12.
const topic12Curated = [
  ['¿Cuál es la finalidad principal de los medios de contraste radiológicos?',['Sustituir la radiación utilizada en las técnicas de imagen.','Aumentar la capacidad diagnóstica de las técnicas de imagen.','Reducir siempre la dosis de radiación administrada al paciente.','Evitar la necesidad de realizar diferentes proyecciones.'],1,'TEMA 12','fácil','Los medios de contraste permiten diferenciar mejor determinadas estructuras o tejidos y, por tanto, aumentar la capacidad diagnóstica de la prueba.'],
  ['¿Qué combinación de medio de contraste y técnica de imagen es correcta?',['Rayos X — gadolinio.','Resonancia magnética — sulfato de bario.','Rayos X — bario o yodo.','Ecografía — gadolinio.'],2,'TEMA 12','fácil','En radiología con rayos X se emplean principalmente contrastes como el bario y los compuestos yodados. El gadolinio es propio de la RM y las microburbujas de la ecografía.'],
  ['¿Qué medio de contraste se utiliza habitualmente para estudiar el tubo digestivo por vía oral?',['Gadolinio.','Sulfato de bario.','Microburbujas.','Yodo intraarterial.'],1,'TEMA 12','fácil','El sulfato de bario se administra habitualmente por vía oral para opacificar el tubo digestivo y delimitar su luz en los estudios radiológicos.'],
  ['En un paciente con sospecha de perforación del tubo digestivo, ¿qué contraste debe evitarse habitualmente por vía oral?',['Sulfato de bario.','Gadolinio.','Microburbujas.','Aire.'],0,'TEMA 12','medio','Si existe sospecha de perforación, debe evitarse el bario porque su salida fuera del tubo digestivo puede provocar una reacción inflamatoria importante.'],
  ['Ante la sospecha de una perforación del tubo digestivo, ¿qué medio de contraste se utiliza habitualmente como alternativa al sulfato de bario?',['Gadolinio.','Microburbujas.','Gastrografin.','Aire exclusivamente.'],2,'TEMA 12','medio','Gastrografin es un contraste yodado hidrosoluble que puede utilizarse como alternativa al bario cuando existe sospecha de perforación.'],
  ['¿Para qué estructuras se utiliza principalmente la administración de contraste por vía oral?',['Colon y recto exclusivamente.','Esófago, estómago e intestino delgado.','Vejiga y uréteres.','Articulaciones y partes blandas.'],1,'TEMA 12','fácil','La vía oral permite que el contraste recorra el tubo digestivo, especialmente esófago, estómago e intestino delgado.'],
  ['¿En qué situación está especialmente indicada la administración de contraste por vía oral?',['En pacientes conscientes que pueden colaborar.','Exclusivamente en pacientes anestesiados.','Únicamente en pacientes con una sonda arterial.','Solo en pacientes con una ostomía.'],0,'TEMA 12','fácil','La administración oral requiere que el paciente pueda ingerir y deglutir el contraste de forma adecuada, por lo que la colaboración es importante.'],
  ['Para realizar un estudio del intestino grueso mediante un enema opaco convencional, ¿qué contraste se utiliza?',['Gadolinio.','Sulfato de bario.','Gastrografin exclusivamente.','Microburbujas.'],1,'TEMA 12','fácil','En el enema opaco convencional se introduce sulfato de bario por vía rectal para opacificar el colon y valorar su morfología.'],
  ['¿Qué diferencia fundamental existe entre un enema opaco convencional y uno de doble contraste?',['El convencional utiliza gadolinio y el de doble contraste yodo.','El convencional utiliza aire y el de doble contraste únicamente bario.','El convencional utiliza sulfato de bario y el de doble contraste utiliza sulfato de bario y aire.','No existe ninguna diferencia en los medios utilizados.'],2,'TEMA 12','medio','El doble contraste combina bario, que recubre la mucosa, con aire, que distiende el colon y mejora la visualización de sus relieves.'],
  ['¿Qué debe comprobarse antes de administrar contraste a través de una sonda nasogástrica?',['Que la sonda esté conectada a una bomba de contraste.','Que el extremo esté correctamente colocado y alejado de la unión esofagogástrica.','Que la sonda llegue necesariamente al intestino grueso.','Que el paciente esté siempre en decúbito prono.'],1,'TEMA 12','medio','Antes de administrar contraste por una sonda nasogástrica hay que comprobar su correcta posición para reducir el riesgo de una administración incorrecta o de aspiración.'],
  ['¿Qué actuación se recomienda al finalizar la administración de contraste por una sonda nasogástrica?',['Retirar inmediatamente la sonda sin realizar ninguna otra actuación.','Limpiar la sonda con suero para evitar obstrucciones.','Introducir aire a presión para eliminar el contraste.','Mantener la sonda cerrada durante 24 horas.'],1,'TEMA 12','fácil','Lavar la sonda con suero ayuda a eliminar restos de contraste y disminuye el riesgo de que se obstruya.'],
  ['Para administrar contraste a través de un estoma, ¿qué procedimiento se describe?',['Introducir una sonda Foley y administrar el contraste diluido con agua.','Introducir siempre una sonda nasogástrica.','Administrar el contraste exclusivamente por vía intravenosa.','Utilizar únicamente aire sin contraste.'],0,'TEMA 12','medio','En la administración a través de un estoma puede utilizarse una sonda Foley para introducir el contraste, habitualmente diluido con agua según el procedimiento indicado.'],
  ['¿Cómo se administra habitualmente el contraste por vía intravenosa?',['Mediante una arteria femoral.','A través de una vena periférica, habitualmente del antebrazo.','Directamente en una cavidad articular.','Mediante una cánula introducida en el colon.'],1,'TEMA 12','fácil','La vía intravenosa se realiza habitualmente mediante un acceso venoso periférico, con frecuencia en una vena del antebrazo.'],
  ['La administración de contraste por vía intravenosa puede realizarse:',['Únicamente de forma manual.','Únicamente mediante bomba.','De forma manual o mediante una bomba de inyección.','Exclusivamente mediante catéter arterial.'],2,'TEMA 12','fácil','El contraste intravenoso puede administrarse manualmente o mediante un inyector automático, según la técnica y la velocidad de inyección necesaria.'],
  ['¿Cuál es la arteria utilizada con mayor frecuencia para la administración de contraste por vía intraarterial?',['Arteria radial.','Arteria femoral.','Arteria carótida.','Arteria humeral distal.'],1,'TEMA 12','fácil','La arteria femoral es un acceso habitual para procedimientos intraarteriales por su calibre y facilidad de acceso.'],
  ['Si la arteria femoral no es viable para una administración intraarterial, ¿qué alternativa se contempla?',['Arteria braquial proximal (transaxilar).','Vena cefálica.','Vena femoral.','Arteria radial distal exclusivamente.'],0,'TEMA 12','medio','Cuando el acceso femoral no es posible, puede contemplarse un acceso arterial alternativo como la vía braquial proximal o transaxilar.'],
  ['¿En qué consiste una artrografía?',['En administrar contraste dentro de una vena periférica.','En introducir contraste directamente en una cavidad articular para mejorar la visualización de sus estructuras.','En administrar contraste dentro del tubo digestivo.','En introducir contraste en una arteria.'],1,'TEMA 12','fácil','La artrografía consiste en introducir contraste directamente en una articulación para delimitar mejor sus estructuras y detectar alteraciones.'],
  ['Para realizar una artro-TC, ¿qué combinación es la adecuada?',['Gadolinio diluido con agua.','Sulfato de bario y aire.','Yodo no iónico diluido con suero.','Microburbujas de aire.'],2,'TEMA 12','medio','En la artro-TC se introduce contraste yodado, habitualmente no iónico y diluido con suero, dentro de la articulación.'],
  ['¿Qué medio de contraste se utiliza en una artro-RM?',['Sulfato de bario.','Yodo no iónico.','Gadolinio.','Gastrografin.'],2,'TEMA 12','fácil','En la artro-RM se utiliza habitualmente gadolinio diluido para aumentar el contraste dentro de la articulación y valorar mejor sus estructuras.'],
  ['¿Cuál de las siguientes asociaciones entre técnica y vía de administración es correcta?',['Histerosalpingografía — contraste intracavitario.','Dacriografía — contraste intraarticular.','Galactografía — contraste intraarterial.','Fistulografía — contraste intravenoso.'],0,'TEMA 12','medio','La histerosalpingografía utiliza contraste introducido en la cavidad uterina, es decir, por vía intracavitaria, para estudiar la cavidad y las trompas.']
];

window.topic12Curated = topic12Curated;
