// Banco curado del TEMA 11.
const topic11Curated = [
  ['¿En qué se basa el Departamento de Radiología Digital?',['Exclusivamente en las imágenes obtenidas mediante radiología convencional.','En las imágenes digitales generadas por las diferentes modalidades de imagen.','Únicamente en los sistemas de gestión administrativa.','Exclusivamente en los sistemas de archivo de imágenes.'],1,'TEMA 11','fácil','Un Departamento de Radiología Digital trabaja con imágenes digitales procedentes de las distintas modalidades de imagen, no solo de la radiología convencional.'],
  ['¿Qué modalidades pueden generar imágenes digitales gestionadas en un Departamento de Radiología Digital?',['Solo radiología simple y TAC.','Solo TAC y resonancia magnética.','Radiología simple, TAC, resonancia, medicina nuclear y modalidades de fusión.','Exclusivamente modalidades de radiología convencional.'],2,'TEMA 11','fácil','La radiología digital puede integrar imágenes procedentes de múltiples modalidades, como radiología simple, TAC, RM, medicina nuclear y técnicas de fusión.'],
  ['¿Cuál es una de las funciones principales del PACS?',['Gestionar las citas de los pacientes.','Archivar, visualizar, manipular y comunicar imágenes.','Gestionar exclusivamente el material sanitario.','Realizar la administración económica del servicio.'],1,'TEMA 11','fácil','El PACS está orientado a la gestión de las imágenes médicas: permite almacenarlas, visualizarlas, manipularlas y distribuirlas dentro del sistema.'],
  ['¿Cuál de las siguientes actividades corresponde principalmente al RIS?',['Archivar las imágenes a largo plazo.','Manipular las imágenes obtenidas por las modalidades.','Agendar y citar a los pacientes.','Generar directamente las imágenes radiológicas.'],2,'TEMA 11','fácil','El RIS gestiona la información y los procesos del servicio de radiología, incluyendo tareas como la agenda y la citación de pacientes.'],
  ['¿Qué sistema se encarga de gestionar toda la actividad del sistema de radiología, tanto asistencial como administrativa y de gestión?',['PACS.','RIS.','Servidor central de imágenes.','Estación de diagnóstico.'],1,'TEMA 11','fácil','El RIS (Radiology Information System) gestiona la actividad radiológica desde el punto de vista asistencial, administrativo y de gestión.'],
  ['¿Cuál de las siguientes funciones pertenece al RIS?',['Gestionar la actividad administrativa y asistencial del servicio de radiología.','Generar imágenes mediante las distintas modalidades.','Sustituir las estaciones de diagnóstico.','Realizar exclusivamente el almacenamiento físico de imágenes.'],0,'TEMA 11','fácil','El RIS se ocupa de la gestión administrativa y asistencial del servicio; la generación de imágenes corresponde a las modalidades y su gestión visual/archivado al PACS.'],
  ['¿Cuál de las siguientes opciones recoge correctamente algunas funciones de gestión del RIS?',['Agendar, citar, registrar procesos y gestionar materiales.','Adquirir, irradiar, reconstruir y almacenar imágenes.','Diagnosticar, informar, archivar y transmitir imágenes.','Manipular, comprimir, imprimir y eliminar imágenes.'],0,'TEMA 11','medio','Entre las funciones del RIS se encuentran la agenda y citación, el registro de los procesos realizados y la gestión de recursos y materiales del servicio.'],
  ['¿Qué función del RIS está relacionada directamente con el seguimiento de la actividad realizada durante el proceso radiológico?',['Registro de procesos.','Archivo de imágenes a largo plazo.','Manipulación de imágenes.','Generación de imágenes.'],0,'TEMA 11','fácil','El registro de procesos permite dejar constancia y realizar el seguimiento de las actuaciones que se llevan a cabo durante el proceso radiológico.'],
  ['¿Cuál de los siguientes elementos forma parte de los componentes principales de un PACS?',['Servidor central.','Únicamente terminales administrativos.','Exclusivamente sistemas de citación.','Solo estaciones de impresión.'],0,'TEMA 11','fácil','El servidor central es uno de los componentes principales del PACS y participa en la gestión de las imágenes y la información asociada.'],
  ['¿Qué función cumple el sistema de archivo dentro de un PACS?',['Gestionar las citas de los pacientes.','Permitir el almacenamiento de las imágenes durante diferentes periodos de tiempo.','Generar las imágenes radiológicas.','Registrar los procesos administrativos del RIS.'],1,'TEMA 11','fácil','El sistema de archivo del PACS permite conservar las imágenes durante los periodos de tiempo establecidos y hacerlas disponibles cuando sea necesario.'],
  ['¿Qué modalidades forman parte de la estructura de un PACS como fuentes de imágenes?',['Las modalidades que generan imágenes.','Únicamente las estaciones de diagnóstico.','Los sistemas administrativos.','Los sistemas de citación.'],0,'TEMA 11','fácil','Las modalidades de adquisición son las fuentes de las imágenes que posteriormente se incorporan al PACS para su gestión.'],
  ['¿Cuál es la función de las estaciones de diagnóstico y revisión dentro de un PACS?',['Generar las imágenes radiológicas.','Permitir el trabajo con las imágenes para su diagnóstico y revisión.','Gestionar las citas de los pacientes.','Administrar los materiales del servicio.'],1,'TEMA 11','fácil','Las estaciones de diagnóstico y revisión permiten visualizar y trabajar con las imágenes para su interpretación, diagnóstico y revisión.'],
  ['¿Qué componente del PACS permite la transmisión de información entre los diferentes elementos del sistema?',['Sistema de archivo.','Estación de diagnóstico.','Red de transmisión de datos.','Modalidad de adquisición.'],2,'TEMA 11','fácil','La red de transmisión de datos conecta los distintos componentes y permite intercambiar imágenes e información entre ellos.'],
  ['¿Cuál de las siguientes opciones recoge correctamente los principales componentes de un PACS?',['Servidor central, sistema de archivo, modalidades, estaciones de diagnóstico y red de transmisión de datos.','RIS, sistema de citación, almacén de materiales y estaciones administrativas.','Servidor central, únicamente estaciones de diagnóstico y sistema de impresión.','Modalidades, RIS, agenda y gestión de materiales.'],0,'TEMA 11','medio','El PACS integra servidor, almacenamiento, modalidades de adquisición, estaciones de trabajo y red de comunicación para gestionar el flujo de imágenes digitales.'],
  ['¿Qué característica debe presentar un RIS para responder adecuadamente a las necesidades de un servicio de radiología?',['Ser exclusivamente administrativo.','Ser completo, personalizado, robusto, flexible e integrado.','Ser independiente del resto de sistemas.','Ser rígido y específico para una única modalidad.'],1,'TEMA 11','fácil','Un RIS adecuado debe poder cubrir las necesidades del servicio y adaptarse a ellas: por eso se describe como completo, personalizado, robusto, flexible e integrado.'],
  ['¿Cuál de las siguientes NO es una característica indicada para un RIS?',['Flexible.','Robusto.','Personalizado.','Aislado.'],3,'TEMA 11','fácil','Un RIS debe integrarse con el resto de sistemas del entorno radiológico. Por tanto, estar aislado no es una característica deseable.'],
  ['¿Qué significa que un RIS sea flexible?',['Que solo pueda utilizarse con una modalidad concreta.','Que pueda adaptarse a las necesidades y cambios del servicio.','Que no pueda modificarse una vez implantado.','Que gestione únicamente la actividad administrativa.'],1,'TEMA 11','medio','La flexibilidad significa que el RIS puede adaptarse a las necesidades, procedimientos y cambios que surjan en el servicio de radiología.'],
  ['¿Qué relación existe entre el RIS y el PACS dentro de un Departamento de Radiología Digital?',['Ambos realizan exactamente la misma función.','El RIS gestiona la actividad radiológica y el PACS se centra en la gestión de las imágenes digitales.','El PACS gestiona las citas y el RIS almacena las imágenes.','Son sistemas independientes que no intervienen en el proceso radiológico.'],1,'TEMA 11','medio','RIS y PACS tienen funciones complementarias: el RIS gestiona la actividad e información del servicio y el PACS se centra en las imágenes digitales.'],
  ['Un servicio de radiología necesita gestionar citas, registrar procesos y controlar materiales, además de dar soporte al proceso informado. ¿Qué sistema debe realizar principalmente estas funciones?',['PACS.','RIS.','Estación de diagnóstico.','Sistema de archivo.'],1,'TEMA 11','medio','Las funciones descritas pertenecen principalmente al RIS, que gestiona la actividad asistencial y administrativa del servicio, incluido el seguimiento del proceso radiológico.'],
  ['Un Departamento de Radiología Digital necesita almacenar, visualizar, manipular y comunicar las imágenes generadas por sus diferentes modalidades. ¿Qué sistema cumple principalmente estas funciones?',['RIS.','PACS.','Sistema de gestión de materiales.','Agenda radiológica.'],1,'TEMA 11','medio','Almacenar, visualizar, manipular y comunicar imágenes son funciones propias del PACS, que centraliza la gestión de las imágenes digitales.']
];

window.topic11Curated = topic11Curated;
