// Banco curado del TEMA 10.
const topic10Curated = [
  ['¿Qué se entiende por proceso radiológico?',['El conjunto de técnicas utilizadas exclusivamente para obtener imágenes radiográficas.','Una serie de actividades estructuradas que permiten obtener información con valor añadido para mejorar la atención al paciente.','El procedimiento mediante el cual el radiólogo establece un diagnóstico.','El conjunto de sistemas informáticos utilizados en un servicio de radiología.'],1,'TEMA 10','fácil','El proceso radiológico comprende un conjunto organizado de actividades que permite obtener información útil para la atención del paciente; no se limita a adquirir una imagen.'],
  ['En el proceso radiológico, la obtención de una imagen debe entenderse como:',['Una actividad aislada cuyo objetivo final es almacenar la imagen.','El último paso antes de finalizar la atención al paciente.','Una actividad integrada en un proceso que comienza con una petición y cuya información puede contribuir al diagnóstico y tratamiento.','Una actividad independiente de la información clínica del paciente.'],2,'TEMA 10','fácil','La imagen forma parte de un proceso más amplio que comienza con una petición y continúa con las distintas actuaciones necesarias para aportar información diagnóstica y orientar el tratamiento.'],
  ['¿Qué caracteriza a la ingeniería de un proceso radiológico?',['La modificación de un proceso que ya se encuentra implantado.','La puesta en marcha del proceso definiendo acciones y roles del personal.','La sustitución de los sistemas analógicos por sistemas digitales.','La evaluación de los resultados obtenidos tras la implantación.'],1,'TEMA 10','fácil','La ingeniería consiste en definir y poner en marcha el proceso, estableciendo las acciones y los roles que intervienen en él.'],
  ['La reingeniería de un proceso consiste en:',['Diseñar por primera vez las actividades y responsabilidades del proceso.','Actuar y realizar modificaciones sobre un proceso previamente definido.','Instalar exclusivamente nuevos equipos de adquisición.','Sustituir al personal que participa en el proceso.'],1,'TEMA 10','fácil','La reingeniería parte de un proceso que ya existe y plantea modificaciones para adaptarlo o mejorarlo ante nuevas necesidades.'],
  ['Un servicio de radiología incorpora nuevas modalidades, RIS y PACS. ¿Qué circunstancia puede hacer necesaria una reingeniería del proceso?',['Que la tecnología no tenga ninguna repercusión sobre la organización del trabajo.','Que los cambios tecnológicos obliguen a revisar y adaptar el proceso existente.','Que el proceso radiológico deba mantenerse exactamente igual.','Que únicamente sea necesario cambiar los equipos informáticos.'],1,'TEMA 10','medio','La incorporación de nuevas tecnologías puede cambiar los circuitos de trabajo y las responsabilidades, por lo que el proceso existente puede necesitar ser revisado y adaptado.'],
  ['¿Cuál de las siguientes opciones representa mejor la relación entre ingeniería y reingeniería?',['La ingeniería modifica un proceso existente y la reingeniería lo inicia.','Ambas expresiones hacen referencia al mismo procedimiento.','La ingeniería pone en marcha y estructura el proceso; la reingeniería permite modificarlo posteriormente.','La ingeniería corresponde al RIS y la reingeniería al PACS.'],2,'TEMA 10','medio','La ingeniería estructura y pone en marcha el proceso; la reingeniería actúa posteriormente sobre un proceso ya definido para introducir cambios.'],
  ['¿Cuál es la primera actuación dentro de las fases de reingeniería descritas?',['Gestionar el cambio tecnológico.','Diseñar el nuevo proceso.','Analizar el sistema antiguo.','Evaluar las mejoras obtenidas.'],2,'TEMA 10','fácil','Antes de diseñar modificaciones hay que conocer el punto de partida. Por eso la primera fase es analizar el sistema antiguo.'],
  ['Tras analizar el sistema antiguo, ¿qué aspecto debe estudiarse antes de diseñar el nuevo proceso?',['El cambio tecnológico.','Únicamente la formación del personal.','Exclusivamente los datos maestros.','Los resultados de la evaluación final.'],0,'TEMA 10','medio','Una vez conocido el sistema antiguo, se analiza el cambio tecnológico que motiva o condiciona la transformación antes de diseñar el nuevo proceso.'],
  ['¿Cuál de las siguientes secuencias corresponde al desarrollo correcto de la reingeniería?',['Sistema antiguo → cambio tecnológico → nuevo proceso → gestión del cambio → evaluación.','Cambio tecnológico → sistema antiguo → gestión del cambio → nuevo proceso → evaluación.','Sistema antiguo → nuevo proceso → cambio tecnológico → evaluación → gestión del cambio.','Nuevo proceso → sistema antiguo → cambio tecnológico → gestión del cambio → evaluación.'],0,'TEMA 10','medio','La secuencia parte del análisis del sistema antiguo, estudia el cambio tecnológico, diseña el nuevo proceso, gestiona su implantación y finalmente evalúa los resultados para introducir mejoras.'],
  ['Durante el análisis del cambio tecnológico de un servicio de radiología, ¿qué elementos deben considerarse?',['Únicamente las características del PACS.','Los avances en las modalidades y la introducción de sistemas como RIS, PACS y DICOM.','Exclusivamente las necesidades de formación del personal.','Únicamente el hardware de los equipos de radiografía convencional.'],1,'TEMA 10','medio','El cambio tecnológico debe analizarse de forma global, considerando las nuevas modalidades y sistemas que afectan al proceso, como RIS, PACS y DICOM.'],
  ['¿Cuál de las siguientes actuaciones pertenece específicamente a la fase de gestión del cambio?',['Analizar el sistema antiguo.','Diseñar el nuevo proceso.','Instalar y adecuar los sistemas informáticos y el hardware asociado.','Determinar la necesidad de realizar una reingeniería.'],2,'TEMA 10','medio','La gestión del cambio incluye llevar a la práctica el nuevo entorno, adecuando los sistemas informáticos y el hardware para que el proceso pueda funcionar correctamente.'],
  ['La introducción de datos maestros dentro de la reingeniería del proceso radiológico se incluye en:',['El análisis del sistema antiguo.','El análisis del cambio tecnológico.','El diseño del nuevo proceso.','La gestión del cambio.'],3,'TEMA 10','medio','La introducción y adaptación de los datos maestros forma parte de la implantación y gestión del cambio del nuevo sistema.'],
  ['¿Cuál de las siguientes actuaciones contribuye a facilitar la adaptación del personal a un nuevo proceso radiológico?',['Evitar comunicar los cambios hasta que estén completamente implantados.','Establecer un plan de comunicación y formación.','Mantener los procedimientos antiguos sin modificaciones.','Prescindir de la formación si se dispone de sistemas automatizados.'],1,'TEMA 10','fácil','Comunicar los cambios y formar al personal facilita la adaptación al nuevo proceso y ayuda a que los procedimientos se apliquen correctamente.'],
  ['Durante la implantación de un nuevo sistema informático en radiología, ¿cuál de las siguientes actuaciones es adecuada?',['Instalar el sistema y asumir que funcionará correctamente sin comprobaciones.','Adecuar los sistemas informáticos y el hardware asociado y asegurarse de su correcto funcionamiento.','Eliminar inmediatamente todos los sistemas anteriores sin planificación.','Posponer la formación del personal indefinidamente.'],1,'TEMA 10','medio','La implantación requiere adaptar los sistemas y el hardware y comprobar que funcionan correctamente antes de considerar completado el cambio.'],
  ['¿Cuál de las siguientes afirmaciones sobre la evaluación del proceso radiológico es correcta?',['Se realiza únicamente antes de iniciar la reingeniería.','Constituye la fase final y debe permitir introducir mejoras continuas.','Sustituye al análisis del cambio tecnológico.','Tiene como objetivo impedir modificaciones posteriores del proceso.'],1,'TEMA 10','fácil','La evaluación se realiza al final del proceso de reingeniería y sirve para detectar resultados y aspectos susceptibles de mejora continua.'],
  ['Un servicio ha implantado un nuevo sistema RIS/PACS y, después de su puesta en funcionamiento, analiza los resultados y detecta aspectos que deben modificarse. ¿En qué fase se encuentra?',['Análisis del sistema antiguo.','Diseño del nuevo proceso.','Gestión del cambio.','Evaluación y mejoras continuas.'],3,'TEMA 10','medio','Si el nuevo sistema ya está implantado y se analizan sus resultados para detectar modificaciones, se está en la fase de evaluación y mejora continua.'],
  ['¿Cuál de las siguientes situaciones refleja mejor la necesidad de una reingeniería del proceso radiológico?',['Mantener un proceso diseñado para sistemas analógicos pese a la incorporación de tecnologías digitales.','Mantener sin cambios un proceso que funciona correctamente y no ha sufrido ninguna modificación tecnológica.','Realizar una exploración siguiendo un protocolo establecido.','Registrar una petición radiológica antes de realizar una exploración.'],0,'TEMA 10','medio','Un proceso diseñado para un entorno analógico puede quedar desadaptado cuando se incorporan tecnologías digitales. La reingeniería permite revisarlo y adaptarlo a la nueva situación.'],
  ['En un proceso de transformación tecnológica, ¿cuál de las siguientes actuaciones NO corresponde a la gestión del cambio?',['Introducción de datos maestros.','Plan de comunicación y formación.','Adecuación de los sistemas informáticos y hardware asociado.','Análisis del sistema antiguo.'],3,'TEMA 10','medio','El análisis del sistema antiguo pertenece a la fase inicial de análisis, no a la gestión del cambio, que se ocupa de implantar y facilitar la transición al nuevo proceso.'],
  ['Un hospital pretende incorporar una nueva modalidad y modificar la organización del trabajo que ya tiene establecida. ¿Qué actuación resulta más adecuada?',['Mantener necesariamente el proceso existente porque ya está definido.','Realizar una reingeniería que permita adaptar el proceso a la nueva situación tecnológica.','Limitarse a instalar el nuevo equipo sin modificar el proceso.','Sustituir la fase de evaluación por una nueva fase de ingeniería.'],1,'TEMA 10','medio','Como ya existe una organización del trabajo y se va a introducir una nueva tecnología, la reingeniería permite revisar y adaptar el proceso existente.'],
  ['¿Cuál de las siguientes opciones resume mejor el objetivo de la reingeniería del proceso radiológico?',['Sustituir al personal por sistemas informáticos.','Incorporar tecnología sin modificar la organización existente.','Adaptar y mejorar un proceso previamente definido ante los cambios tecnológicos y organizativos.','Limitar el proceso radiológico a la adquisición y almacenamiento de imágenes.'],2,'TEMA 10','medio','La reingeniería busca adaptar y mejorar un proceso existente cuando cambian las condiciones tecnológicas u organizativas, manteniendo el objetivo de ofrecer un proceso adecuado y eficiente.']
];

window.topic10Curated = topic10Curated;
