const topic9Curated = [
  ['¿Cuál es una de las principales ventajas de la radiografía digital respecto a la radiografía convencional?',['Elimina completamente el ruido de la imagen','Permite reducir la dosis manteniendo una adecuada calidad diagnóstica','Evita la necesidad de procesar las imágenes','Impide que las imágenes sean modificadas posteriormente'],1,'TEMA 9','fácil'],
  ['¿Qué característica del detector digital hace referencia a su capacidad para registrar un amplio intervalo de exposiciones?',['Resolución espacial','Eficiencia de detección cuántica','Rango dinámico','Tamaño del píxel'],2,'TEMA 9','fácil'],
  ['En radiografía digital, ¿qué representa la curva característica del detector?',['La relación entre el tamaño del píxel y la resolución espacial','La relación entre la radiación que llega al detector y la señal obtenida','La relación entre el contraste y el ruido','La relación entre la dosis al paciente y el tiempo de exposición'],1,'TEMA 9','medio'],
  ['¿Qué factor resulta fundamental para mejorar la visibilidad de una estructura en una imagen digital y depende de las características del detector?',['El tamaño de la estructura','El contraste propio de la estructura','El ruido de la imagen','La densidad anatómica'],2,'TEMA 9','medio'],
  ['Respecto a la DQE de un detector digital, ¿cuál de las siguientes afirmaciones es correcta?',['Evalúa únicamente la resolución espacial','Relaciona la señal obtenida con la eficiencia del detector para conservar información frente al ruido','Aumenta siempre al disminuir el tamaño del píxel','No depende de la tecnología de construcción del detector'],1,'TEMA 9','difícil'],
  ['¿Qué ocurre, en general, al disminuir el tamaño del píxel de un detector digital?',['Disminuye la resolución espacial','Aumenta la resolución espacial, pero puede disminuir la DQE y aumentar el ruido','Aumenta siempre la DQE','Desaparece el ruido de la imagen'],1,'TEMA 9','medio'],
  ['¿Cuál es el objetivo de separar la adquisición y la presentación de la imagen en radiografía digital?',['Evitar cualquier modificación posterior de la imagen','Permitir optimizar de forma independiente la adquisición y la presentación','Eliminar la necesidad de utilizar detectores digitales','Conseguir que todas las imágenes tengan el mismo contraste'],1,'TEMA 9','fácil'],
  ['¿Cuál es la secuencia correcta del procesamiento básico de una imagen digital?',['DICOM de presentación → imagen adquirida → DICOM bruto','Imagen adquirida → DICOM bruto → DICOM para presentación','DICOM bruto → imagen adquirida → DICOM de presentación','Imagen adquirida → DICOM de presentación → DICOM bruto'],1,'TEMA 9','fácil'],
  ['¿Qué caracteriza a la imagen DICOM para presentación?',['Es la señal sin ningún tipo de corrección','Es la imagen final procesada preparada para su visualización y archivo','Es exclusivamente la información procedente del detector antes de las correcciones','Es una copia de seguridad de la imagen adquirida'],1,'TEMA 9','fácil'],
  ['En el ajuste de ventana, ¿qué parámetro determina principalmente el tipo de tejido que se visualiza?',['El ancho','El nivel','El tamaño del píxel','La DQE'],1,'TEMA 9','fácil'],
  ['¿Qué efecto produce una ventana estrecha?',['Mayor número de tonos de gris y menor contraste','Menor número de tonos de gris y mayor contraste','Mayor ruido y menor contraste','Menor resolución espacial'],1,'TEMA 9','fácil'],
  ['¿Qué efecto produce una ventana amplia?',['Mayor contraste entre estructuras','Menor número de tonos de gris','Mayor número de tonos de gris y menor contraste','Visualización exclusiva de estructuras óseas'],2,'TEMA 9','fácil'],
  ['¿Qué tipo de nivel de ventana se utiliza principalmente para visualizar estructuras de baja densidad, como el aire o la grasa?',['Nivel alto','Nivel intermedio','Nivel bajo','Nivel máximo'],2,'TEMA 9','medio'],
  ['¿Qué consecuencia puede tener la corrección de una imagen obtenida con sobreexposición?',['Eliminación completa del ruido','Aparición de una imagen con mayor ruido del habitual','Disminución automática de la dosis administrada al paciente','Aumento de la resolución espacial del detector'],1,'TEMA 9','medio'],
  ['¿Cuál es el objetivo de la ecualización tisular?',['Aplicar el mismo procesamiento a toda la imagen','Diferenciar tejidos de distintas densidades dentro de una misma imagen mediante procesamientos adaptados a cada zona','Eliminar completamente el ruido','Aumentar exclusivamente la resolución espacial'],1,'TEMA 9','medio'],
  ['¿Cuál es la principal utilidad del realce de bordes?',['Reducir el contraste entre estructuras','Mejorar la visualización de las interfaces entre estructuras con diferente atenuación','Eliminar el ruido de la imagen','Disminuir el rango dinámico del detector'],1,'TEMA 9','fácil'],
  ['¿Qué efecto secundario puede producir el realce de bordes?',['Disminución de la resolución espacial','Aumento del ruido','Eliminación de estructuras de alto contraste','Reducción del rango dinámico'],1,'TEMA 9','fácil'],
  ['¿Por qué el procesamiento específico de mamografía debe ser especialmente cuidadoso?',['Porque la mama presenta exclusivamente estructuras óseas','Porque las diferencias de densidad entre los tejidos mamarios pueden ser muy pequeñas','Porque no puede utilizarse procesamiento digital','Porque la mamografía carece de contraste entre tejidos'],1,'TEMA 9','medio'],
  ['¿En qué principio físico se basa la energía dual?',['La atenuación de los tejidos es independiente de la energía de los fotones','La atenuación de los tejidos varía en función de la energía de los fotones','Los fotones de cualquier energía producen siempre el mismo efecto','La imagen digital no depende de la energía utilizada'],1,'TEMA 9','medio'],
  ['A energías elevadas, ¿qué interacción adquiere mayor importancia y produce menor diferencia de atenuación entre determinados tejidos?',['Efecto fotoeléctrico','Efecto Compton','Fluorescencia','Resonancia'],1,'TEMA 9','medio'],
  ['En un sistema de energía dual de doble disparo, ¿qué función tiene el filtro de cobre situado entre los dos receptores?',['Aumentar la dosis administrada al paciente','Modificar el espectro de radiación que llega al segundo receptor','Eliminar completamente la radiación dispersa','Aumentar el tamaño del píxel'],1,'TEMA 9','difícil'],
  ['En la energía dual de doble disparo, ¿qué permite obtener el procesamiento de las imágenes adquiridas con diferentes energías?',['Únicamente una imagen convencional','Una imagen convencional y diferentes imágenes procesadas para resaltar determinadas estructuras','Una única imagen sin posibilidad de procesamiento','Exclusivamente una imagen ósea'],1,'TEMA 9','medio'],
  ['En mamografía con energía dual y contraste yodado, ¿qué permite identificar principalmente la combinación de las imágenes obtenidas?',['Únicamente el tejido adiposo','Las zonas de captación del contraste yodado','Exclusivamente las calcificaciones','Solo las estructuras musculares'],1,'TEMA 9','medio'],
  ['¿Qué característica define a la tomosíntesis?',['Obtiene una única imagen plana con mayor contraste','Obtiene múltiples proyecciones desde distintos ángulos para reconstruir imágenes en diferentes planos','Utiliza exclusivamente una proyección lateral','Sustituye siempre a la radiografía convencional'],1,'TEMA 9','fácil'],
  ['¿Cuál es una de las principales ventajas de la tomosíntesis?',['Elimina completamente la radiación dispersa','Permite separar estructuras superpuestas y mejorar su visualización','Reduce siempre la dosis respecto a cualquier técnica convencional','Solo permite estudiar estructuras óseas'],1,'TEMA 9','fácil']
];

// El banco automático de tests-bank.js se mantiene intacto para el resto de temas.
// Para el Tema 9 usamos exclusivamente el banco revisado y aprobado.
window.topic9Curated = topic9Curated;

// tests-bank.js se carga antes que este archivo. Sustituimos solo la presentación
// del menú por temas para que TEMA 9 use estas preguntas y el resto conserve su banco.
window.topicMenu = function(){
  const generated=[...buildTopicBank(),...topic1Curated,...topic2Curated,...topic3Curated,...topic4Specific,...topic5Specific,...topicSpecific];
  const withoutTopic9=generated.filter(q=>q[3]!=='TEMA 9');
  const all=[...withoutTopic9,...topic9Curated];
  const byTopic={};
  all.forEach(q=>(byTopic[q[3]]??=[]).push(q));
  const entries=Object.keys(byTopic).sort((a,b)=>+a.split(' ')[1]-+b.split(' ')[1]);
  ws.hidden=false;
  ws.innerHTML=`<div class="study-material"><p class="eyebrow">TEST POR TEMAS</p><h2>📚 Elige un tema</h2><p>Cada tema tiene un banco propio de preguntas generado a partir del contenido real. El número disponible aparece en cada tarjeta.</p><div class="cards">${entries.map((n,i)=>`<button class="module-card" data-topic="${i}"><span class="module-number">${n}</span><h3>${esc((topics[n.split(' ')[1]]||{}).title||n)}</h3><p>${byTopic[n].length} preguntas disponibles</p><span class="module-action">Entrenar →</span></button>`).join('')}</div></div>`;
  ws.querySelectorAll('[data-topic]').forEach((b,i)=>b.onclick=()=>session(entries[i],byTopic[entries[i]]));
};
