// Test curado del TEMA 26: Radiología convencional de abdomen.
const topic26Curated = [
  ["Para una radiografía simple de abdomen, la técnica indicada se caracteriza por:", ["mA bajo y tiempo de exposición largo", "mA alto y tiempo de exposición corto", "kV muy alto y mA bajo", "Tiempo largo para aumentar la definición"], 1, "TEMA 26", "medio", "La técnica indicada es mA alto y tiempo de exposición corto, con un kilovoltaje aproximado de 60–80 kV. Esto permite una buena visualización del gas y de las partes blandas abdominales."],
  ["El rango aproximado de kilovoltaje indicado para la radiografía simple de abdomen es:", ["40–60 kV", "50–70 kV", "60–80 kV", "80–100 kV"], 2, "TEMA 26", "medio", "El tema establece un kilovoltaje aproximado de 60–80 kV para la radiografía simple de abdomen."],
  ["¿Cuál es la proyección básica u obligada en el estudio radiológico simple del abdomen?", ["AP en bipedestación", "AP en decúbito supino", "Lateral en bipedestación", "PA en decúbito prono"], 1, "TEMA 26", "fácil", "La AP de abdomen en decúbito supino es la proyección básica u obligada. Permite valorar la morfología de las vísceras y el aire contenido en las asas intestinales."],
  ["En la AP de abdomen en decúbito supino, el objetivo principal es:", ["Valorar exclusivamente los niveles hidroaéreos", "Detectar únicamente neumoperitoneo", "Visualizar la morfología de las vísceras y el aire contenido en las asas intestinales", "Estudiar exclusivamente la pared abdominal"], 2, "TEMA 26", "medio", "La AP supina es la proyección básica porque permite visualizar la morfología de las vísceras y el aire contenido en las asas intestinales."],
  ["Un paciente con sospecha de oclusión intestinal puede beneficiarse especialmente de una radiografía de abdomen en:", ["Bipedestación", "Decúbito prono", "Decúbito supino exclusivamente", "Lateral derecha"], 0, "TEMA 26", "medio", "La bipedestación es una proyección complementaria útil para valorar niveles hidroaéreos y sospecha de oclusión intestinal."],
  ["La principal utilidad de la proyección AP de abdomen en bipedestación es demostrar:", ["La morfología hepática", "Los niveles hidroaéreos", "La pared abdominal", "Las vértebras lumbares"], 1, "TEMA 26", "fácil", "La bipedestación permite demostrar niveles hidroaéreos, gracias a la disposición de aire y líquido cuando se utiliza la posición vertical."],
  ["Paciente con sospecha de perforación del tubo digestivo. ¿Qué hallazgo se pretende demostrar mediante una proyección de abdomen en bipedestación?", ["Calcificaciones vasculares", "Aire libre abdominal", "Disminución del tamaño hepático", "Aumento de la densidad de las asas"], 1, "TEMA 26", "medio", "Una perforación del tubo digestivo puede producir salida de aire hacia la cavidad peritoneal. La bipedestación ayuda a demostrar ese aire libre, es decir, un posible neumoperitoneo."],
  ["Un paciente presenta un estado general que le impide mantenerse de pie. Se necesita una alternativa a la proyección de abdomen en bipedestación. ¿Cuál corresponde?", ["Decúbito lateral izquierdo con rayo horizontal", "Decúbito lateral derecho con rayo vertical", "Decúbito prono con rayo vertical", "Lateral de abdomen con rayo vertical"], 0, "TEMA 26", "medio", "El decúbito lateral izquierdo con rayo horizontal puede sustituir a la bipedestación cuando el paciente no puede ponerse de pie. Permite valorar niveles hidroaéreos y aire libre."],
  ["En el decúbito lateral izquierdo con rayo horizontal, el aire libre abdominal puede visualizarse entre:", ["El bazo y la pared abdominal", "El borde hepático derecho y la pared abdominal", "El estómago y el diafragma izquierdo", "El riñón izquierdo y la columna"], 1, "TEMA 26", "difícil", "En esta posición, el aire libre puede acumularse entre el borde hepático derecho y la pared abdominal, facilitando la detección de neumoperitoneo."],
  ["La utilización de un rayo horizontal en determinadas proyecciones abdominales tiene como finalidad principal:", ["Aumentar el contraste de las vísceras", "Demostrar niveles líquidos y aire libre", "Reducir la magnificación", "Eliminar la radiación dispersa"], 1, "TEMA 26", "medio", "El rayo horizontal permite demostrar niveles hidroaéreos y aire libre, ya que favorece la separación entre aire y líquido y su representación como una interfase visible."],
  ["¿Cuál de las siguientes asociaciones es CORRECTA?", ["Bipedestación → únicamente estudio de vísceras sólidas", "Decúbito supino → niveles hidroaéreos como objetivo principal", "Decúbito lateral izquierdo → alternativa a la bipedestación en pacientes que no pueden ponerse de pie", "Lateral en supino → proyección obligatoria en todos los pacientes"], 2, "TEMA 26", "difícil", "El decúbito lateral izquierdo con rayo horizontal es la alternativa a la bipedestación cuando el paciente no puede mantenerse de pie. Las demás asociaciones no corresponden al protocolo del tema."],
  ["Un paciente inmovilizado no puede colocarse de pie ni realizar otras proyecciones. ¿Qué proyección puede realizarse según el protocolo estudiado?", ["Lateral de abdomen en decúbito supino con rayo horizontal", "AP de abdomen en bipedestación", "PA de abdomen en decúbito prono", "Oblicua abdominal bilateral"], 0, "TEMA 26", "medio", "La lateral de abdomen en decúbito supino con rayo horizontal se utiliza en pacientes que no pueden movilizarse y en los que resulta imposible realizar otras proyecciones."],
  ["La proyección lateral de abdomen en decúbito supino con rayo horizontal está especialmente indicada:", ["Como proyección estándar en todos los pacientes", "Cuando el paciente no puede movilizarse y no es posible realizar otras proyecciones", "Para estudiar exclusivamente el hígado", "Para sustituir siempre a la AP supina"], 1, "TEMA 26", "medio", "Es una proyección reservada para pacientes que no pueden movilizarse cuando resulta imposible realizar otras proyecciones. No sustituye de forma general a la AP supina."],
  ["Una mujer en edad fértil va a someterse a una radiografía simple de abdomen. Antes de realizar la exploración debe:", ["Administrarse contraste", "Preguntarse por la posibilidad de embarazo", "Realizarse obligatoriamente una proyección PA", "Reducirse siempre el mA a la mitad"], 1, "TEMA 26", "medio", "El protocolo indica que en mujeres en edad fértil hay que preguntar por la posibilidad de embarazo antes de realizar la exploración radiológica."],
  ["En un equipo digital con exposimetría automática para una radiografía de abdomen, el tema indica utilizar:", ["Una cámara centrada exclusivamente sobre la columna", "Dos cámaras, una central y otra lateral", "Tres cámaras para compensar las diferentes densidades", "Todas las cámaras disponibles independientemente de su número"], 2, "TEMA 26", "medio", "El tema indica utilizar las tres cámaras de la exposimetría automática para compensar las diferentes densidades del abdomen."],
  ["Las tres cámaras del sistema de exposimetría automática permiten compensar principalmente las densidades correspondientes a:", ["Hígado, bazo y pelvis", "Centro abdominal/columna y flancos", "Estómago, hígado y vejiga", "Riñones, pelvis y diafragma"], 1, "TEMA 26", "difícil", "Las tres cámaras compensan las diferencias de densidad entre la zona central del abdomen, incluida la columna, y las densidades de los flancos."],
  ["¿Qué combinación describe mejor la técnica básica indicada para la radiografía simple de abdomen?", ["mA bajo + tiempo largo + 100–120 kV", "mA alto + tiempo corto + 60–80 kV", "mA bajo + tiempo corto + 40–50 kV", "mA alto + tiempo largo + 90–110 kV"], 1, "TEMA 26", "medio", "La técnica básica del tema es mA alto, tiempo de exposición corto y aproximadamente 60–80 kV."],
  ["¿Qué situación justificaría realizar una radiografía de abdomen en bipedestación en lugar de limitarse a la proyección supina?", ["Únicamente sospecha de hepatomegalia", "Sospecha de niveles hidroaéreos o neumoperitoneo", "Dolor lumbar inespecífico", "Estudio rutinario de las vísceras sólidas"], 1, "TEMA 26", "medio", "La bipedestación es complementaria y está indicada cuando interesa valorar niveles hidroaéreos, sospecha de oclusión intestinal o perforación del tubo digestivo con posible neumoperitoneo."],
  ["¿Cuál de las siguientes afirmaciones sobre el neumoperitoneo es CORRECTA?", ["Es la presencia de líquido en la cavidad pleural", "Es la presencia de aire libre en la cavidad peritoneal", "Es la acumulación de aire dentro de las asas exclusivamente", "Es la presencia de líquido libre en el abdomen"], 1, "TEMA 26", "fácil", "El neumoperitoneo es la presencia de aire libre en la cavidad peritoneal."],
  ["Una perforación del tubo digestivo puede provocar:", ["Salida de aire hacia la cavidad abdominal", "Únicamente acumulación de líquido pleural", "Disminución del aire intraluminal", "Exclusivamente calcificaciones abdominales"], 0, "TEMA 26", "medio", "Una perforación del tubo digestivo puede permitir la salida de aire o contenido desde una víscera hueca hacia la cavidad abdominal y producir neumoperitoneo."],
  ["Paciente con sospecha de neumoperitoneo que no puede mantenerse en bipedestación. ¿Cuál sería la opción más adecuada según el protocolo estudiado?", ["Decúbito lateral izquierdo con rayo horizontal", "Decúbito prono con rayo vertical", "Lateral derecha con rayo vertical", "AP de abdomen exclusivamente"], 0, "TEMA 26", "difícil", "Cuando el paciente no puede ponerse de pie, el decúbito lateral izquierdo con rayo horizontal sustituye a la bipedestación para buscar aire libre y niveles hidroaéreos."],
  ["En el contexto de un neumoperitoneo, la presencia de aire entre el borde hepático derecho y la pared abdominal debe hacer sospechar:", ["Derrame pleural", "Aire libre intraperitoneal", "Oclusión esofágica", "Distensión vesical"], 1, "TEMA 26", "difícil", "La presencia de aire entre el borde hepático derecho y la pared abdominal es característica de aire libre intraperitoneal, es decir, neumoperitoneo, en el contexto adecuado."],
  ["¿Cuál de las siguientes situaciones se corresponde con un nivel hidroaéreo?", ["Interfase entre hueso y tejido blando", "Interfase entre líquido y aire", "Interfase entre dos estructuras óseas", "Diferencia de densidad entre hígado y bazo"], 1, "TEMA 26", "fácil", "Un nivel hidroaéreo es la interfase entre líquido y aire dentro de una cavidad."],
  ["¿Por qué resulta útil el rayo horizontal para demostrar niveles hidroaéreos?", ["Porque permite que aire y líquido se dispongan formando una interfase visible", "Porque elimina completamente la radiación dispersa", "Porque evita la magnificación geométrica", "Porque aumenta automáticamente el contraste de la imagen"], 0, "TEMA 26", "difícil", "El rayo horizontal permite que el aire y el líquido se dispongan formando una interfase que puede visualizarse como nivel hidroaéreo."],
  ["¿Cuál de las siguientes afirmaciones es INCORRECTA?", ["La proyección supina es la básica del abdomen", "La bipedestación permite valorar niveles hidroaéreos", "El decúbito lateral izquierdo puede sustituir a la bipedestación si el paciente no puede ponerse de pie", "La proyección lateral en supino es obligatoria en todos los estudios abdominales"], 3, "TEMA 26", "medio", "La incorrecta es que la lateral en supino sea obligatoria en todos los estudios. Se reserva para pacientes que no pueden movilizarse y en los que no es posible realizar otras proyecciones."],
  ["Un paciente encamado presenta distensión abdominal y sospecha de oclusión intestinal. No puede ponerse de pie. ¿Qué combinación sería la más coherente con el protocolo estudiado?", ["Decúbito lateral izquierdo + rayo horizontal", "Decúbito prono + rayo vertical", "Bipedestación + rayo horizontal", "Lateral derecha + rayo vertical"], 0, "TEMA 26", "difícil", "Si el paciente no puede ponerse de pie, el decúbito lateral izquierdo con rayo horizontal es la alternativa indicada para valorar niveles hidroaéreos."],
  ["¿Qué diferencia fundamental existe entre la AP de abdomen en decúbito supino y la AP en bipedestación?", ["La primera utiliza siempre rayo horizontal y la segunda vertical", "La primera es la proyección básica; la segunda es complementaria para niveles hidroaéreos y aire libre", "La primera solo sirve para estudiar huesos; la segunda, vísceras", "No existe ninguna diferencia diagnóstica relevante"], 1, "TEMA 26", "medio", "La AP supina es la proyección básica y la bipedestación es complementaria, especialmente útil para demostrar niveles hidroaéreos y aire libre abdominal."],
  ["Un técnico realiza una radiografía abdominal en una mujer en edad fértil sin preguntar por la posibilidad de embarazo. ¿Qué actuación del protocolo ha omitido?", ["Colocar tres cámaras AEC", "Comprobar la posibilidad de embarazo", "Utilizar siempre 120 kV", "Realizar una proyección lateral obligatoria"], 1, "TEMA 26", "medio", "El protocolo establece que en mujeres en edad fértil debe preguntarse por la posibilidad de embarazo antes de realizar la exploración."],
  ["¿Cuál de las siguientes NO corresponde a una indicación característica de la bipedestación abdominal según el tema?", ["Valoración de niveles hidroaéreos", "Sospecha de oclusión intestinal", "Sospecha de perforación del tubo digestivo", "Visualización rutinaria de la morfología de las vísceras abdominales como única finalidad"], 3, "TEMA 26", "difícil", "La visualización rutinaria de la morfología de las vísceras corresponde a la AP supina, que es la proyección básica. La bipedestación se utiliza como complemento para niveles hidroaéreos, oclusión o perforación."],
  ["Si el paciente no puede ponerse de pie, el decúbito lateral izquierdo con rayo horizontal:", ["No permite valorar niveles hidroaéreos", "Sustituye a la bipedestación en determinadas circunstancias", "Solo sirve para estudiar la columna lumbar", "Se realiza siempre con rayo vertical"], 1, "TEMA 26", "medio", "El decúbito lateral izquierdo con rayo horizontal puede sustituir a la bipedestación cuando el paciente no puede ponerse de pie y permite valorar niveles hidroaéreos y aire libre."],
  ["¿Cuál de las siguientes parejas está correctamente relacionada?", ["Neumoperitoneo → aire libre en cavidad peritoneal", "Oclusión intestinal → aire libre intrapleural", "Nivel hidroaéreo → tejido óseo y aire", "Perforación digestiva → líquido exclusivamente intravascular"], 0, "TEMA 26", "fácil", "Neumoperitoneo significa precisamente presencia de aire libre en la cavidad peritoneal."],
  ["Un paciente no puede ser movilizado y resulta imposible realizar las proyecciones habituales. Se decide hacer una lateral abdominal con rayo horizontal en decúbito supino. Esta decisión:", ["Es coherente con la situación descrita", "Es incorrecta porque la lateral abdominal nunca utiliza rayo horizontal", "Solo sería válida en bipedestación", "Solo se utiliza para estudiar el tórax"], 0, "TEMA 26", "medio", "Esta proyección está contemplada para pacientes que no pueden movilizarse cuando resulta imposible realizar otras proyecciones."],
  ["¿Cuál de estas afirmaciones sobre la exposición automática en abdomen es correcta?", ["Se utiliza una única cámara porque las densidades abdominales son homogéneas", "Se utilizan tres cámaras para compensar las diferencias de densidad entre el centro y los flancos", "Las cámaras sustituyen completamente la selección de kV", "Las cámaras se utilizan únicamente en radiografía convencional analógica"], 1, "TEMA 26", "difícil", "El tema indica utilizar tres cámaras del sistema de exposimetría automática para compensar las diferencias de densidad entre la zona central del abdomen, incluida la columna, y los flancos."],
  ["Caso práctico: paciente con sospecha de perforación digestiva, incapaz de mantenerse en pie. En la radiografía se observa una colección de aire entre el borde hepático derecho y la pared abdominal. ¿Cuál es la interpretación más adecuada?", ["Nivel hidroaéreo intestinal", "Neumoperitoneo", "Derrame abdominal", "Distensión gástrica aislada"], 1, "TEMA 26", "difícil", "En un paciente con sospecha de perforación, aire entre el borde hepático derecho y la pared abdominal indica aire libre intraperitoneal, compatible con neumoperitoneo."],
  ["Un paciente con sospecha de oclusión intestinal no puede ponerse de pie. ¿Cuál es la secuencia más correcta?", ["AP supina obligatoria → si se necesita valorar niveles, decúbito lateral izquierdo con rayo horizontal", "Bipedestación obligatoria → si no puede, suspender el estudio", "Lateral supina → posteriormente PA en bipedestación", "Decúbito prono → posteriormente lateral derecha con rayo vertical"], 0, "TEMA 26", "difícil", "La AP supina es la proyección básica. Si además se necesitan valorar niveles hidroaéreos y el paciente no puede ponerse de pie, se utiliza el decúbito lateral izquierdo con rayo horizontal."]
];
window.topic26Curated = topic26Curated;

const previousTopicMenu26 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu26();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b=>(b.textContent||'').includes('TEMA 26'));
  const setCard = b => {
    b.disabled = false;
    b.innerHTML = `<span class="module-number">TEMA 26</span><h3>${esc((topics[26]||{}).title||'TEMA 26')}</h3><p>${topic26Curated.length} preguntas disponibles</p><span class="module-action">Entrenar →</span>`;
    b.onclick = () => session('TEMA 26', topic26Curated);
  };
  if(existing){ setCard(existing); return; }
  const button = document.createElement('button');
  button.className='module-card';
  button.type='button';
  setCard(button);
  const before=[...cards.querySelectorAll('button.module-card')].find(b=>{const m=(b.textContent||'').match(/TEMA\s+(\d+)/);return m&&Number(m[1])>26;});
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
