// Test curado del TEMA 30: Radiología convencional dental.
const topic30Curated = [
  ["¿Cuántas piezas componen la dentición decidua?", ["16", "20", "24", "32"], 1, "TEMA 30", "fácil", "La dentición decidua o temporal está formada por 20 piezas: 10 en la arcada superior y 10 en la inferior."],
  ["¿Cuántas piezas forman la dentición permanente?", ["20", "28", "30", "32"], 3, "TEMA 30", "fácil", "La dentición permanente completa consta de 32 piezas, incluidos los cuatro terceros molares o cordales."],
  ["¿Cuál de las siguientes piezas NO forma parte de la dentición decidua?", ["Incisivos", "Caninos", "Premolares", "Molares temporales"], 2, "TEMA 30", "medio", "La dentición decidua incluye incisivos, caninos y molares temporales, pero no premolares. Los premolares pertenecen a la dentición permanente."],
  ["La dentición permanente comienza aproximadamente:", ["Al nacimiento", "A los 2 años", "A los 6 años", "A los 12 años"], 2, "TEMA 30", "fácil", "La erupción de la dentición permanente comienza aproximadamente a los 6 años, con la aparición de los primeros molares permanentes y el recambio de los incisivos."],
  ["Los terceros molares reciben también el nombre de:", ["Premolares", "Cordales", "Incisivos", "Caninos"], 1, "TEMA 30", "fácil", "Los terceros molares son conocidos como cordales o muelas del juicio."],
  ["En odontología, el término mesial indica una estructura:", ["Alejada del plano sagital medio", "Situada hacia la superficie oclusal", "Próxima al plano sagital medio", "Dirigida hacia la cara vestibular"], 2, "TEMA 30", "fácil", "Mesial indica proximidad al plano sagital medio. Es el contrario de distal, que indica alejamiento de ese plano."],
  ["¿Qué término indica que una estructura se aleja del plano sagital medio?", ["Mesial", "Distal", "Lingual", "Palatino"], 1, "TEMA 30", "fácil", "Distal significa alejado del plano sagital medio. Mesial significa próximo a él."],
  ["La cara del diente orientada hacia el exterior, hacia el vestíbulo de la boca, se denomina:", ["Lingual", "Palatina", "Vestibular", "Mesial"], 2, "TEMA 30", "fácil", "La superficie vestibular es la cara del diente orientada hacia el vestíbulo de la boca, es decir, hacia labios o mejillas."],
  ["El término lingual se utiliza específicamente para referirse a la cara interna de los dientes de:", ["La arcada superior", "La arcada inferior", "Ambas arcadas indistintamente", "Los incisivos exclusivamente"], 1, "TEMA 30", "medio", "En los dientes inferiores se utiliza el término lingual para la cara interna, orientada hacia la lengua. En los superiores se utiliza específicamente palatino."],
  ["El término palatino hace referencia a la cara interna de los dientes de:", ["La arcada superior", "La arcada inferior", "Ambas arcadas", "Los molares exclusivamente"], 0, "TEMA 30", "fácil", "Palatino describe la superficie interna de los dientes superiores, orientada hacia el paladar. En los inferiores se denomina lingual."],
  ["Una lesión situada en la superficie masticatoria de un diente afecta a su superficie:", ["Vestibular", "Lingual", "Distal", "Oclusal"], 3, "TEMA 30", "fácil", "La superficie oclusal es la superficie masticatoria de premolares y molares, donde contactan con los dientes de la arcada opuesta."],
  ["¿Cuál de las siguientes NO es una de las tres funciones principales atribuidas a los dientes?", ["Digestiva", "Fonética", "Estética", "Respiratoria"], 3, "TEMA 30", "fácil", "Las funciones principales de los dientes incluyen la función digestiva, fonética y estética. La función respiratoria no es una función dental principal."],
  ["En la función digestiva de los dientes, los incisivos se encargan principalmente de:", ["Triturar", "Desgarrar", "Cortar", "Deglutir"], 2, "TEMA 30", "fácil", "Los incisivos están adaptados principalmente para cortar los alimentos. Los caninos desgarran y los premolares y molares trituran."],
  ["¿Qué técnica intraoral permite visualizar las coronas y las crestas alveolares de dientes superiores e inferiores?", ["Periapical", "Bite-wing o aleta de mordida", "Oclusal", "Teleradiografía"], 1, "TEMA 30", "medio", "La bite-wing o aleta de mordida permite visualizar simultáneamente las coronas de dientes superiores e inferiores y las crestas alveolares, siendo especialmente útil para detectar caries interproximales."],
  ["La aleta de mordida resulta especialmente útil para el estudio de:", ["La articulación temporomandibular", "La base del cráneo", "Caries y alteraciones de las coronas/crestas alveolares", "Las estructuras neurovasculares profundas"], 2, "TEMA 30", "medio", "La bite-wing es especialmente útil para detectar caries interproximales y valorar las coronas dentales y el nivel de las crestas alveolares."],
  ["En una radiografía periapical se estudian:", ["Exclusivamente las coronas dentales", "Diente, membrana periodontal y hueso circundante", "Únicamente las estructuras óseas maxilares", "Ambas arcadas completas"], 1, "TEMA 30", "medio", "La radiografía periapical muestra el diente completo o gran parte de él, incluida la región apical, junto con el espacio periodontal y el hueso alveolar circundante."],
  ["En las radiografías periapicales, para incisivos y caninos la placa se coloca habitualmente:", ["Horizontal", "Oblicua", "Vertical", "En el plano sagital"], 2, "TEMA 30", "medio", "Para incisivos y caninos, la colocación habitual del receptor es vertical para incluir adecuadamente la longitud de estos dientes."],
  ["Para premolares y molares, la placa periapical se coloca habitualmente:", ["Vertical", "Horizontal", "Paralela al plano sagital medio", "Perpendicular al plano oclusal"], 1, "TEMA 30", "medio", "Para premolares y molares, el receptor se coloca habitualmente en posición horizontal, porque estos dientes tienen una disposición más ancha en la arcada."],
  ["¿Qué dos técnicas pueden utilizarse para realizar una radiografía periapical?", ["Bisectriz y paralelismo", "Waters y Caldwell", "Schüller y Hirtz", "Towne y Caldwell"], 0, "TEMA 30", "fácil", "Las dos técnicas clásicas para obtener radiografías periapicales son la técnica de la bisectriz y la técnica del paralelismo."],
  ["La técnica de la bisectriz y la técnica del paralelismo son técnicas propias de:", ["Radiografía panorámica", "Radiografía periapical", "Teleradiografía lateral", "TAC dental"], 1, "TEMA 30", "fácil", "Tanto la técnica de la bisectriz como la del paralelismo se emplean para realizar radiografías intraorales periapicales."],
  ["En una radiografía oclusal maxilar, la placa se sitúa:", ["En el plano oclusal superior", "En el plano oclusal inferior", "Fuera de la boca", "En posición vertical junto a la mejilla"], 0, "TEMA 30", "medio", "En la radiografía oclusal maxilar, el receptor se coloca dentro de la boca sobre el plano oclusal de la arcada superior para obtener una visión amplia del maxilar."],
  ["Respecto a las radiografías oclusales, según el material de estudio:", ["Son actualmente la técnica intraoral más utilizada", "Se utilizan exclusivamente en niños", "Están prácticamente en desuso", "Han sustituido a las radiografías periapicales"], 2, "TEMA 30", "fácil", "Según el material de estudio, las radiografías oclusales están prácticamente en desuso frente a otras técnicas intraorales y extraorales más habituales."],
  ["En las técnicas intraorales actuales, el detector puede ser:", ["Exclusivamente una película convencional", "Exclusivamente una pantalla intensificadora", "Un detector digital intraoral", "Únicamente una placa panorámica"], 2, "TEMA 30", "medio", "En radiología dental actual pueden utilizarse receptores digitales intraorales, que sustituyen a la película convencional en muchos sistemas."],
  ["Debido a la escasa DFP en radiología dental intraoral, resulta especialmente importante:", ["Utilizar siempre una parrilla antidifusora", "Aumentar al máximo el campo irradiado", "Una adecuada colimación y protección radiológica", "Utilizar siempre proyecciones oblicuas"], 2, "TEMA 30", "medio", "La pequeña distancia foco-paciente en radiología intraoral hace especialmente importante limitar el campo mediante una buena colimación y aplicar correctamente las medidas de protección radiológica."],
  ["El diámetro externo aproximado del cono delimitador del haz mencionado para estas técnicas es de:", ["2 cm", "4 cm", "6 cm", "10 cm"], 2, "TEMA 30", "medio", "Según el material de estudio, el diámetro externo aproximado del cono delimitador del haz es de 6 cm, ayudando a limitar el campo irradiado."],
  ["¿Cuál de las siguientes técnicas es extraoral?", ["Bite-wing", "Periapical", "Oclusal", "Ortopantomografía"], 3, "TEMA 30", "fácil", "La ortopantomografía es una técnica extraoral: el receptor permanece fuera de la boca y permite obtener una imagen panorámica de las arcadas y estructuras relacionadas."],
  ["La radiografía oblicua lateral dental:", ["Es actualmente la técnica extraoral de elección", "Está prácticamente en desuso gracias a la ortopantomografía", "Se utiliza exclusivamente para cefalometría", "Es una técnica intraoral"], 1, "TEMA 30", "medio", "La radiografía oblicua lateral dental ha quedado prácticamente en desuso como técnica extraoral debido a la disponibilidad de la ortopantomografía."],
  ["La teleradiografía lateral de cara y cráneo se utiliza fundamentalmente para:", ["Estudiar exclusivamente caries", "Cefalometría y estudio ortodóncico", "Valorar únicamente el hueso alveolar", "Detectar alteraciones de la pulpa dental"], 1, "TEMA 30", "fácil", "La teleradiografía lateral permite realizar estudios cefalométricos y es fundamental en la valoración y planificación ortodóncica."],
  ["En la teleradiografía lateral, además de las estructuras óseas del macizo facial, pueden visualizarse:", ["Exclusivamente los dientes", "Las partes blandas de la cara", "Únicamente las estructuras intracraneales", "Solo las raíces dentales"], 1, "TEMA 30", "medio", "La teleradiografía lateral puede mostrar tanto estructuras óseas como las partes blandas del perfil facial, información útil para el estudio cefalométrico."],
  ["¿Qué exploración permite visualizar en una sola imagen las dos arcadas dentarias completas y sus tejidos de soporte?", ["Radiografía periapical", "Bite-wing", "Ortopantomografía", "Teleradiografía lateral"], 2, "TEMA 30", "fácil", "La ortopantomografía proporciona en una sola imagen una visión global de ambas arcadas dentarias y de los tejidos de soporte y estructuras maxilomandibulares relacionadas."],
  ["Una de las principales ventajas de la ortopantomografía es:", ["Permitir estudiar un único diente con máximo detalle", "Obtener una visión global de ambas arcadas", "Evitar completamente cualquier distorsión geométrica", "Sustituir siempre al TAC dental"], 1, "TEMA 30", "medio", "La principal ventaja de la ortopantomografía es ofrecer una visión global de ambas arcadas y estructuras maxilomandibulares en una única exploración."],
  ["Para la planificación de implantes dentales y la valoración de la calidad ósea, una técnica especialmente indicada es:", ["Bite-wing", "Radiografía oclusal", "TAC dental", "Teleradiografía lateral"], 2, "TEMA 30", "difícil", "El TAC dental proporciona información tridimensional y permite valorar la anatomía ósea y estructuras de interés para planificar implantes con mayor precisión."],
  ["Una ventaja importante del TAC dental respecto a una radiografía convencional es que:", ["No utiliza radiación ionizante", "Elimina las superposiciones y permite reconstrucciones multiplanares", "Solo proporciona imágenes bidimensionales", "No permite valorar estructuras óseas"], 1, "TEMA 30", "difícil", "El TAC dental utiliza radiación ionizante, pero permite obtener información tridimensional, reducir el problema de las superposiciones y realizar reconstrucciones en distintos planos."],
  ["¿Cuál de las siguientes asociaciones es INCORRECTA?", ["Bite-wing → estudio de caries", "Periapical → diente y estructuras de soporte", "Teleradiografía lateral → ortodoncia", "Ortopantomografía → estudio exclusivo de un único diente"], 3, "TEMA 30", "medio", "La ortopantomografía no estudia exclusivamente un único diente; precisamente una de sus ventajas es ofrecer una visión global de ambas arcadas y estructuras maxilomandibulares."],
  ["Caso integrado: un paciente acude para planificación de un implante dental. Se necesita conocer la calidad del hueso, la situación de estructuras neurovasculares y disponer de reconstrucciones en diferentes planos. ¿Cuál sería la opción más adecuada?", ["Radiografía bite-wing", "Radiografía periapical", "Ortopantomografía exclusivamente", "TAC dental"], 3, "TEMA 30", "difícil", "El TAC dental es la opción más adecuada cuando se necesita información tridimensional, valorar el hueso y localizar estructuras anatómicas importantes para planificar un implante." ]
];
window.topic30Curated = topic30Curated;

const previousTopicMenu30 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu30();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b=>(b.textContent||'').includes('TEMA 30'));
  const setCard = b => {
    b.disabled = false;
    b.innerHTML = `<span class="module-number">TEMA 30</span><h3>${esc((topics[30]||{}).title||'TEMA 30')}</h3><p>${topic30Curated.length} preguntas disponibles</p><span class="module-action">Entrenar →</span>`;
    b.onclick = () => session('TEMA 30', topic30Curated);
  };
  if(existing){ setCard(existing); return; }
  const button = document.createElement('button');
  button.className='module-card';
  button.type='button';
  setCard(button);
  const before=[...cards.querySelectorAll('button.module-card')].find(b=>{const m=(b.textContent||'').match(/TEMA\s+(\d+)/);return m&&Number(m[1])>30;});
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
