// Test curado del TEMA 42 · EXPLORACIÓN ECOGRÁFICA DEL TIROIDES Y TEJIDOS BLANDOS
const topic42Curated = [
  ["¿En qué compartimento del cuello se localiza el tiroides?", ["En el compartimento suprahiodeo, detrás de la tráquea.", "En el compartimento infrahoideo, en la zona anteroinferior del cuello.", "En la región posterior del cuello, detrás de la columna.", "En la cavidad torácica, por debajo del esternón."], 1, "TEMA 42", "fácil", "El tiroides está localizado en el compartimento infrahoideo, en la zona anteroinferior del cuello y delante y a los lados de los primeros anillos traquelaes."],
  ["¿Qué hormonas sintetiza principalmente el tiroides?", ["T3 y T4.", "T1 y T2.", "TSH y T3.", "T4 y calcitonina exclusivamente."], 0, "TEMA 42", "fácil", "El tema indica que el tiroides produce dos hormonas: triyodotironina (T3) y tiroxina (T4)."],
  ["En ecografía, el tiroides presenta habitualmente una ecogenicidad:", ["Un patrón homogéneo y ligeramente hiperecogénico respecto al músculo.", "Un patrón anecogénico y heterogéneo.", "Un patrón exclusivamente hipoecogénico.", "Un patrón calcificado con sombra acústica posterior."], 0, "TEMA 42", "fácil", "En ECO, el tiroides presenta un patrón homogéneo, ligeramente hiperecogénico respecto al músculo."],
  ["En un corte transversal del tiroides, los lóbulos se encuentran:", ["Dentro de la tráquea y por fuera de la carótida.", "Por fuera de la tráquea y por dentro de la arteria carótida común y la vena yugular interna.", "Por detrás de la columna cervical.", "Por delante de la piel y del tejido subcutáneo."], 1, "TEMA 42", "medio", "En los cortes transversales, los lóbulos tienen forma triangular, están por fuera de la tráquea y por dentro de la arteria carótida común y la vena yugular interna."],
  ["¿Qué estructura aparece como una banda fina de tejido ecogénico por delante de la tráquea?", ["El lóbulo piramidal.", "El istmo.", "La vena yugular interna.", "El esófao."], 1, "TEMA 42", "fácil", "El istmo aparece como una banda fina de tejido ecogénico situada por delante de la tráquea."],
  ["¿Cuál es aproximadamente el diámetro longitudinal de un lóbulo tiroideo?", ["4-6 mm.", "13-18 mm.", "20-30 mm.", "40-60 mm."], 3, "TEMA 42", "fácil", "El diámetro longitudinal indicado es de 40-60 mm. El anteroposterior es de 13-18 mm, el transversal de 20-30 mm y el istmo de 4-6 mm."],
  ["Para la exploración ecográfica del tiroides, el paciente debe colocarse:", ["En decúbito prono con el cuello flexionado.", "En decúbito supino con ligera hiperextensión del cuello.", "Sentado con el cuello en flexión máxima.", "En decúbito lateral con rotación completa de la cabeza."], 1, "TEMA 42", "fácil", "La preparación indicada es decúbito supino, con el cuello descubierto y libre de objetos metálicos y con una ligera hiperextensión del cuello."],
  ["¿Qué tipo de transductor se recomienda para la exploración del tiroides?", ["Sonda de baja frecuencia convexa.", "Sonda de alta frecuencia lineal de 7,5 a 13 MHz.", "Sonda sectorial de 1 a 3 MHz.", "Sonda lineal exclusivamente de 2 a 5 MHz."], 1, "TEMA 42", "fácil", "Se utilizan sondas de alta frecuencia, de 7,5 a 13 MHz, que deben ser lineales por su campo de visión."],
  ["¿Qué modo se utiliza inicialmente en la exploración del tiroides?", ["Modo B.", "Solo Doppler espectral.", "Modo M.", "Solo elastografía."], 0, "TEMA 42", "fácil", "El programa inicial es en modo B. Si se detecta un nódulo, se utiliza Doppler color para valorar, entre otros aspectos, su vascularización."],
  ["¿Qué información aporta principalmente la elastografía?", ["La elastografía por eco.", "La fluoroscopia.", "La radiografía convencional.", "La gammagrafía."], 0, "TEMA 42", "fácil", "La elastografía por eco valora la elasticidad de los tejidos. El tema indica que los nódulos malignos son más rigidos que los tejidos normales o los nódulos benignos."],
  ["Durante el protocolo de estudio del tiroides, el barrido inicial debe realizarse:", ["Solo en transversal.", "Solo en longitudinal.", "En longitudinal y transversal de toda la glándula.", "Exclusivamente sobre el istmo."], 2, "TEMA 42", "fácil", "El barrido inicial será de toda la glándula en longitudinal y transversal."],
  ["En el estudio transversal de toda la glándula a la altura del istmo debe incluirse:", ["Solo el diámetro longitudinal.", "La medida del istmo y un pictograma indicando lugar y posición del transductor.", "Únicamente una imagen Doppler.", "Solo el lóbulo izquierdo."], 1, "TEMA 42", "medio", "La imagen transversal debe incluir toda la glándula a la altura del istmo, con su medida, indicando en el pictograma el lugar y la posición del transductor."],
  ["Cuando se identifica un nódulo tiroideo, la documentación debe incluir:", ["Solo el diámetro longitudinal.", "Los 3 diámtros e indicando la localización.", "Solo una imagen en Doppler.", "Únicamente una medida del istmo."], 1, "TEMA 42", "fácil", "En los hallazgos de nódulos se debe hacer una foto incluyendo los 3 diámtros e indicando la localización."],
  ["En caso de bocio multinodular, ¿qué debe hacerse?", ["Medir todos los nódulos sin excepción y nunca usar Doppler.", "Medir los nódulos dominantes y obtener imágenes en Doppler para valorar el patrón de vascularización.", "Estudiar únicamente el istmo.", "Realizar exclusivamente elastografía."], 1, "TEMA 42", "medio", "En el bocio multinodular se miden los nódulos dominantes y se obtienen imágenes en Doppler para valorar el patrón de vascularización."],
  ["En todo estudio tiroideo hay que estudiar las regiones laterocervicales para:", ["Descartar adenopatías e intentar caracterizarlas.", "Medir exclusivamente la tráquea.", "Valorar únicamente la glándula parótida.", "Descartar únicamente quistes del conducto tirogloso."], 0, "TEMA 42", "medio", "El tema indica que hay que estudiar ambas regiones laterocervicales para descartar adenopatías e intentar caracterizarlas."],
  ["¿Cuál de las siguientes características corresponde a la tiroiditis subaguda en ecografía?", ["Tiroides aumentado de tamaño con áreas hipoecogénicas mal definidas.", "Tiroides homogéneo e hiperecogénico.", "Calcificaciones en cáscara de huevo.", "Lesión quística con sombra acústica posterior."], 0, "TEMA 42", "medio", "En la tiroiditis subaguda, de origen vírico, la ecografía muestra un tiroides aumentado de tamaño con áreas hipoecogénicas mal definidas."],
  ["En la tiroiditis crónica linfocitaria de HASHIMOTO, la ecografía puede mostrar:", ["Una afectación difusa heterogénea con disminución global de la ecogenicidad y patrón reticular con imágenes seudonodulares.", "Una glándula siempre pequeña y homogénea.", "Exclusivamente un nódulo sólido único.", "Una vascularización periférica aislada sin alteración glandular."], 0, "TEMA 42", "difícil", "En HASHIMOTO se aprecia una afectación difusa de toda la glándula, heterogénea, con disminución global de la ecogenicidad, patrón reticular e imágenes seudonodulares. El tamaño puede variar según la fase."],
  ["¿Qué hallazgo Doppler es característico de la enfermedad de Graves-Basedow?", ["Aumento difuso de la vascularización en Doppler.", "Ausencia completa de vascularización.", "Calcificaciones en cáscara de huevo.", "Lesiones exclusivamente quísticas."], 0, "TEMA 42", "medio", "La enfermedad de Graves-Basedow cursa con bocio e hipertiroidismo y en ecografía presenta alteración difusa de la ecogenicidad y aumento difuso de la vascularización con Doppler."],
  ["¿Qué porcentaje aproximado de los nódulos tiroideos son malignos?", ["Menos del 7% son malignos.", "Más del 50% son malignos.", "Todos los nódulos sólidos son malignos.", "Los nódulos múltiples siempre son malignos."], 0, "TEMA 42", "fácil", "El tema indica que los nódulos tiroideos son muy frecuentes y que menos del 7% son malignos."],
  ["¿Qué característica de los márgenes de un nódulo se describe como signo de benignidad?", ["Bordes espiculados.", "Halo hipoecogénico.", "Infiltración extratiroidea.", "Afectación ganglionar."], 1, "TEMA 42", "medio", "El halo hipoecogénico se describe en el tema como signo de benignidad, mientras que los bordes espiculados se consideran un hallazgo malo."],
  ["¿Qué tipo de calcificaciones se relacionan en el tema con benignidad y cuáles con malignidad?", ["Toscas o en cáscara de huevo → benignas; micros → malas.", "Micros → benignas; cáscara de huevo → malas.", "Todas las calcificaciones → benignas.", "Todas las calcificaciones → malignas."], 0, "TEMA 42", "medio", "El tema diferencia las calcificaciones toscas o en cáscara de huevo, relacionadas con benignidad, de las microcalcificaciones, relacionadas con malignidad."],
  ["La presencia de afectación ganglionar ante un nódulo tiroideo es:", ["Altamente sugestiva de malignidad.", "Siempre indicativa de benignidad.", "Irrelevante para la valoración.", "Indicativa únicamente de tiroiditis aguda."], 0, "TEMA 42", "medio", "La presencia de afectación ganglionar se considera en el tema altamente sugestiva de malignidad."],
  ["En el tiroides post-quirúrgico, el lecho quirúrgico se ve inicialmente como:", ["Un área ecogénica.", "Una lesión anecogénica obligatoria.", "Una calcificación difusa.", "Una estructura hiperecogénica con sombra siempre presente."], 0, "TEMA 42", "fácil", "El lecho quirúrgico se ve como un área ecogénica. En el postoperatorio inmediato puede utilizarse la ecografía para valorar la aparición de colecciones líquidas."],
  ["¿Cuál es una utilidad del intervencionismo guiado por ecografía?", ["Permitir controlar el avance y la situación de la aguja.", "Impedir seleccionar los nódulos.", "Aumentar el error de muestreo.", "Evitar puncionar áreas sólidas."], 0, "TEMA 42", "fácil", "El intervencionismo guiado por eco permite seleccionar los nódulos y controlar el avance y la situación de la aguja, reduciendo la posibilidad de error de muestreo."],
  ["¿Qué calibre de agujas se utiliza en la PAAF según el tema?", ["18G.", "20G.", "23/25G.", "30G."], 2, "TEMA 42", "fácil", "Para la PAAF se utilizan agujas de 23/25G. El transductor se cubre con una funda estéril y la zona se desinfecta."],
  ["¿Qué calibre de agujas se utiliza en la BAG?", ["23/25G.", "18G.", "10G.", "5G."], 1, "TEMA 42", "fácil", "La BAG se realiza con pistolas de biopsia con agujas de 18G."],
  ["¿Cuántas glándulas paratiroides existen normalmente según el tema?", ["2.", "3.", "4.", "6."], 2, "TEMA 42", "fácil", "El tema indica que existen 4 glándulas paratiroides, situadas en la cara posterior de los lóbulos laterales del tiroides."],
  ["¿Cómo se describe ecográficamente el adenoma paratiroideo?", ["Lesión sólida, homogénea e hipoecogénica ovoidea situada en la cara posterior del tiroides.", "Lesión anecogénica multilobulada situada dentro de la tráquea.", "Lesión hiperecogénica con sombra posterior en la piel.", "Lesión exclusivamente quística en el istmo."], 0, "TEMA 42", "medio", "El adenoma paratiroideo es una lesión sólida, homogénea e hipoecogénica, ovoidea, situada en la cara posterior del tiroides. Puede presentar degeneración quística o calcificaciones."],
  ["¿Cuál de las siguientes afirmaciones sobre la parótida es CORRECTA?", ["Es la glándula salival más pequeña y está debajo del milohioideo.", "Es la glándula salival más grande y se localiza en la fosa retromandibular.", "Solo tiene un lóbulo.", "Su conducto es el de Wharton."], 1, "TEMA 42", "medio", "La parótida es la glándula salival más grande y está en la fosa retromandibular, por delante y por debajo del oído y por fuera y detrás de la rama mandibular."],
  ["¿Qué conducto atraviesa el masetero, bucinador y la mucosa oral y excreta saliva a la altura del 2do molar superior?", ["Conducto de Wharton.", "Conducto de Stenon.", "Conducto tirogloso.", "Conducto paratiroideo."], 1, "TEMA 42", "medio", "El conducto de Stenon atraviesa los músculos masetero, bucinador y la mucosa oral, y excreta saliva a la altura del 2do molar superior."],
  ["¿Dónde se localizan las glándulas submandibulares?", ["En el triángulo submandibular, entre el músculo digástrico y el ángulo de la mandíbula.", "En la fosa retromandibular.", "En el suelo de la boca sobre el músculo milohioideo.", "Dentro del tiroides."], 0, "TEMA 42", "medio", "Las glándulas submandibulares están en el triángulo submandibular, entre el músculo digástrico y el ángulo de la mandíbula."],
  ["¿Qué conducto corresponde a las glándulas submandibulares?", ["Conducto de Stenon.", "Conducto de Wharton.", "Conducto tirogloso.", "Conducto de Riedel."], 1, "TEMA 42", "fácil", "Las glándulas submandibulares desaguan en la boca por el conducto de Wharton."],
  ["En condiciones normales, los conductos excretores de las glándulas salivales:", ["Siempre se ven dilatados.", "No se ven; pueden hacerse visibles cuando están dilatados por una obstrucción.", "Solo se ven mediante radiografía.", "Son siempre hiperecogénicos con sombra acústica."], 1, "TEMA 42", "medio", "En condiciones normales los conductos excretores no se ven. Pueden verse cuando están dilatados por una obstrucción."],
  ["¿Qué glándula salival no puede estudiarse completamente en su porción profunda debido a la interposición del hueso de la mandíbula?", ["Submandibular.", "Sublingual.", "Parótida.", "Ninguna."], 2, "TEMA 42", "fácil", "La porción profunda de la parótida no se puede estudiar porque el hueso de la mandíbula se interpone."],
  ["¿Dónde son más frecuentes los cálculos salivales (sialolitiasis)?", ["En las parótidas.", "En las submaxilares.", "En las sublinguales.", "En los ganglios laterocervicales."], 1, "TEMA 42", "fácil", "La sialolitiasis es más frecuente en las submaxilares, según el tema, por el tipo de saliva, que es más espesa."],
  ["¿Qué aspecto ecográfico presentan los cálculos salivales?", ["Focos hiperecogénicos con sombra acústica posterior.", "Lesiones anecogénicas sin sombra.", "Áreas hipoecogénicas sin relación con los conductos.", "Solo engrosamiento cutáneo."], 0, "TEMA 42", "fácil", "En ecografía, la sialolitiasis se ve como focos hiperecogénicos con sombra acústica posterior, en el conducto o dentro de la glándula. También pueden verse dilatación del conducto e inflamación."],
  ["En una sialodenitis aguda, la ecografía puede mostrar:", ["Aumento de tamaño de la glándula con disminución de la ecogenicidad y, en ocasiones, abscesos.", "Disminución de tamaño con desestructuración difusa exclusivamente.", "Una glándula siempre homogénea e hiperecogénica.", "Únicamente microcalcificaciones."], 0, "TEMA 42", "medio", "En las inflamaciones agudas se observa aumento de tamaño de la glándula con disminución de la ecogenicidad y pueden aparecer abscesos en ocasiones."],
  ["¿Cuál es el tumor salival benigno más frecuente?", ["Tumor de Whorthin.", "Adenoma pleoformo.", "Carcinoma anaplásico.", "Adenoma paratiroideo."], 1, "TEMA 42", "fácil", "Del 70-80% de los tumores de las glándulas salivales se ubican en la parótida y el 80% son benignos. El más frecuente es el adenoma pleoformo y el segundo el tumor de Worthin."],
  ["¿Cómo se describe ecográficamente el adenoma pleoformo?", ["Lesión hipoecogénica de bordes definidos y lobulados.", "Lesión anecogénica con sombra posterior.", "Lesión hiperecogénica de bordes espiculados.", "Lesión exclusivamente calcificada."], 0, "TEMA 42", "medio", "El adenoma pleoformo es benigno y de lento crecimiento. En ecografía son lesiones hipoecogénicas de bordes definidos y lobulados."],
  ["¿Cuál de las siguientes características corresponde al tumor de Whorthin?", ["Lesiones redondeadas o lobuladas, bien circunscritas, hipoecogénicas o con áreas quísticas y finos septos ecogénicos.", "Lesiones siempre calcificadas con sombra acústica.", "Lesiones anecogénicas exclusivamente en la línea media.", "Lesiones difusas sin límites."], 0, "TEMA 42", "difícil", "El tumor de Whorthin asienta en el lóbulo superficial. En ecografía se describe como una lesión redondeada o lobulada, bien circunscrita, hipoecogénica o con áreas quísticas y finos septos ecogénicos."],
  ["¿Qué característica describe al quiste del conducto tirogloso?", ["Es una masa frecuente en la cara anterior del cuello y se localiza habitualmente en la línea media.", "Se localiza siempre dentro de la parótida.", "Aparece exclusivamente detrás de la tráquea.", "Solo se presenta después de los 50 años."], 0, "TEMA 42", "medio", "El quiste del conducto tirogloso es una de las masas más frecuentes en la cara anterior del cuello. En ecografía aparece como un nódulo bien delimitado en la línea media de la cara anterior del cuello."],
  ["Una característica del quiste del conducto tirogloso es que:", ["La lesión se mueve durante la deglución.", "Nunca cambia con la deglución.", "Siempre produce sombra acústica.", "Solo puede estudiarse mediante Doppler."], 0, "TEMA 42", "fácil", "Dada su relación con la lengua, el tema indica que la lesión se mueve durante la deglución."],
  ["¿Cuál es la complicación más frecuente del quiste del conducto tirogloso?", ["Infección recurrente.", "Calcificación inmediata.", "Hemorragia obligatoria.", "Adenopatía supraclavicular obligatoria."], 0, "TEMA 42", "fácil", "La complicación más frecuente indicada es la infección recurrente. Cuando se infecta, puede aparecer componente ecogénico en su interior y septos irregulares."],
  ["En los quistes de la hendidura branquial, la ecografía permite valorar:", ["Tamaño, extensión, relación con estructuras adyacentes y confirmar su naturaleza quística.", "Solo el diámetro longitudinal.", "Únicamente la vascularización.", "Solo la presencia de calcificaciones."], 0, "TEMA 42", "medio", "La ecografía se utiliza para definir el tamaño, la extensión, la relación con estructuras adyacentes, confirmar la naturaleza quística y servir como guía intervencionista."],

  ["¿Qué utilidad tiene la ecografía en el postoperatorio inmediato de una cirugía tiroidea?",["Valorar posibles colecciones líquidas","Medir exclusivamente la yugular","Determinar la función hormonal","Descartar siempre un adenoma paratiroideo"],0,"TEMA 42","medio","En el postoperatorio inmediato, la ecografía permite valorar la aparición de colecciones líquidas en el lecho quirúrgico."],
  ["¿Qué característica aumenta la sospecha de malignidad de un nódulo tiroideo?",["Mayor tamaño","Menor tamaño","Ser siempre hiperecoico","No tener vascularización"],0,"TEMA 42","medio","El tema indica que los nódulos de mayor tamaño son más sospechosos."],
  ["¿Qué aspecto del nódulo tiroideo debe valorarse además de su tamaño y ecogenicidad?",["Su forma","Solo el grosor del istmo","Solo la piel","Únicamente la tráquea"],0,"TEMA 42","fácil","La forma es uno de los criterios que se valoran en el estudio ecográfico de los nódulos."],
  ["¿Qué relación se establece entre el número de nódulos y la probabilidad de malignidad?",["La presencia de muchos nódulos hace menos probable la malignidad","Muchos nódulos implican siempre malignidad","Un único nódulo es siempre maligno","El número nunca se valora"],0,"TEMA 42","medio","La presencia de múltiples nódulos hace menos probable que uno de ellos sea maligno, aunque deben valorarse individualmente."],
  ["¿Qué lesión paratiroidea puede presentar degeneración quística o calcificaciones?",["Adenoma paratiroideo","Quiste del conducto tirogloso","Tumor de Warthin","Sialolitiasis"],0,"TEMA 42","medio","El adenoma paratiroideo puede presentar ocasionalmente degeneración quística o calcificaciones."],
  ["¿Qué estructura dificulta el estudio ecográfico completo de la porción profunda de la parótida?",["La mandíbula","La tráquea","El hioides","El esófago"],0,"TEMA 42","fácil","La mandíbula se interpone y dificulta el estudio completo de la porción profunda de la parótida."],
  ["¿Qué manifestación es característica de la sialolitiasis?",["Dolor e inflamación, a menudo después de las comidas","Disnea nocturna","Pérdida de audición","Hipertiroidismo"],0,"TEMA 42","medio","La sialolitiasis puede producir episodios dolorosos e inflamatorios que aparecen con frecuencia después de las comidas."],
  ["¿Cómo suele verse una lesión quística salival simple en ecografía?",["Anecoica y de pared fina","Sólida y espiculada","Hiperecoica con sombra","Siempre calcificada"],0,"TEMA 42","fácil","Las lesiones quísticas salivales se describen como anecoicas, de pared fina y uni o multiloculares."],
  ["Además de la propia glándula, ¿qué estructuras pueden observarse dentro de la parótida?",["Ganglios","Solo cálculos","Solo quistes tiroideos","Únicamente músculos"],0,"TEMA 42","medio","En la ecografía pueden verse ganglios dentro de la parótida."],
  ["¿De qué trayecto embrionario es remanente el conducto tirogloso?",["Del trayecto desde el foramen ciego de la lengua hasta el lóbulo piramidal del tiroides","Del conducto de Stenon","Del conducto de Wharton","De la hendidura branquial"],0,"TEMA 42","difícil","El quiste del conducto tirogloso deriva de un remanente embrionario que va desde el foramen ciego de la lengua hasta el lóbulo piramidal del tiroides."]
];

window.topic42Curated = topic42Curated;

const previousTopicMenu42 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu42();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 42'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 42</span><h3>${esc((topics[42]||{}).title||'TEMA 42')}</h3><p>${topic42Curated.length} preguntas · tiroides y tejidos blandos</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 42', topic42Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 42</span><h3>${esc((topics[42]||{}).title||'TEMA 42')}</h3><p>${topic42Curated.length} preguntas · tiroides y tejidos blandos</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 42', topic42Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\\s+(\\d+)/); return m && Number(m[1]) > 42; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
