// Banco curado del TEMA 13.
const topic13Curated = [
["¿Cuál es la finalidad principal de los medios de contraste en las exploraciones radiográficas?",["Disminuir la dosis de radiación administrada al paciente.","Mejorar la visualización de las estructuras del organismo.","Sustituir la radiación por ondas ultrasónicas.","Evitar la necesidad de realizar distintas proyecciones."],1,"TEMA 13","medio","Los medios de contraste modifican la diferencia de atenuación entre estructuras y permiten visualizar mejor órganos, cavidades o vasos que de otro modo se distinguirían peor."],
["¿Cuál de los siguientes se considera un medio de contraste negativo o radiotransparente?",["Sulfato de bario.","Contraste yodado.","Aire.","Gadolinio."],2,"TEMA 13","medio","Un contraste negativo atenúa poco los rayos X y aparece radiotransparente. El aire es el ejemplo clásico, frente al bario o al yodo, que son contrastes positivos."],
["¿Qué función desempeñan principalmente los contrastes negativos en las exploraciones digestivas?",["Aumentar la absorción de radiación de la mucosa.","Distender las paredes intestinales y separarlas de la mucosa.","Recubrir la mucosa con una capa radiopaca.","Reducir la viscosidad del contenido intestinal."],1,"TEMA 13","medio","Los contrastes negativos, como el aire o el CO₂, permiten distender el tubo digestivo y crear contraste con la pared, facilitando la visualización de la mucosa."],
["¿En cuál de las siguientes exploraciones se utiliza habitualmente un contraste negativo como el aire?",["Enema opaco de doble contraste.","Urografía intravenosa.","Histerosalpingografía.","Artrografía."],0,"TEMA 13","medio","En el enema de doble contraste se combina un contraste positivo, habitualmente bario, con aire para distender el colon y mejorar la visualización de su mucosa."],
["En una arteriografía con dióxido de carbono, su administración debe realizarse:",["Siempre por encima del diafragma.","Únicamente por vía intravenosa.","Por debajo del diafragma.","Exclusivamente por vía oral."],2,"TEMA 13","medio","El CO₂ como contraste vascular se utiliza en territorios por debajo del diafragma. Su empleo por encima del diafragma está contraindicado por el riesgo de alcanzar la circulación cerebral o coronaria."],
["¿Cuál de los siguientes es un contraste positivo no yodado utilizado en exploraciones intestinales?",["Sulfato de bario.","Dióxido de carbono.","Lipiodol.","Contraste yodado no iónico."],0,"TEMA 13","medio","El sulfato de bario es un contraste positivo porque absorbe los rayos X y produce opacificación. Es el contraste clásico para numerosas exploraciones del aparato digestivo."],
["Para que el sulfato de bario sea adecuado para una exploración digestiva debe ser:",["Poco viscoso y de rápida eliminación.","Suficientemente viscoso para fluir y recubrir la mucosa.","Insoluble y completamente sólido.","Altamente osmolar para producir distensión intestinal."],1,"TEMA 13","medio","La suspensión de bario debe tener una viscosidad adecuada para desplazarse por el tubo digestivo y, al mismo tiempo, adherirse y recubrir la mucosa para mostrarla correctamente."],
["¿Cuál de las siguientes puede ser una complicación del sulfato de bario?",["Neumonitis química por aspiración.","Hipoglucemia grave.","Insuficiencia hepática inmediata.","Hipertensión arterial permanente."],0,"TEMA 13","medio","Si el bario se aspira puede producir una complicación pulmonar importante. Por eso, ante determinadas situaciones de riesgo, se valoran otras alternativas de contraste."],
["¿Qué puede producir la extravasación peritoneal de sulfato de bario debido a una perforación intestinal?",["Fibrosis extensa.","Hiperventilación.","Edema cerebral.","Bradicardia."],0,"TEMA 13","medio","Si existe una perforación intestinal y el bario pasa a la cavidad peritoneal, puede desencadenar una reacción inflamatoria intensa y fibrosis, por lo que debe evitarse cuando se sospecha perforación."],
["Los contrastes yodados hidrosolubles son ampliamente utilizados porque:",["Solo pueden administrarse por vía intravenosa.","Pueden utilizarse en diferentes cavidades, naturales o patológicas.","Son siempre liposolubles.","No presentan ninguna interacción con el organismo."],1,"TEMA 13","medio","Los contrastes yodados hidrosolubles pueden emplearse en múltiples estudios y vías de administración, tanto intravasculares como en distintas cavidades, según la indicación."],
["¿Cuál de los siguientes factores influye en el grado de opacificación producido por un contraste yodado hidrosoluble?",["La velocidad de inyección.","El color del contraste.","El tamaño del recipiente utilizado.","La posición del paciente exclusivamente."],0,"TEMA 13","medio","La velocidad de inyección influye en la concentración de contraste que alcanza una determinada zona y, por tanto, en la intensidad y el momento de la opacificación."],
["¿Cómo se clasifican los contrastes yodados hidrosolubles según el radical asociado?",["Hidrosolubles y liposolubles.","Monómeros y dímeros.","Iónicos y no iónicos.","Positivos y negativos."],2,"TEMA 13","medio","Los contrastes yodados hidrosolubles se clasifican, entre otros criterios, en iónicos y no iónicos según su comportamiento y estructura química en solución."],
["¿Qué característica presentan los contrastes yodados iónicos al entrar en contacto con la sangre?",["No generan partículas con carga eléctrica.","Generan partículas con carga eléctrica y pueden producir alteraciones hidroelectrolíticas.","Se convierten inmediatamente en gases.","Disminuyen siempre la osmolaridad plasmática."],1,"TEMA 13","medio","Los contrastes iónicos se disocian en solución y generan partículas con carga eléctrica. Este comportamiento se relaciona con una mayor osmolaridad y con más efectos fisiológicos."],
["¿Por qué se ha reducido el uso de los contrastes yodados iónicos?",["Porque no contienen yodo.","Por su elevada osmolaridad y mayor incidencia de efectos secundarios y reacciones adversas.","Porque son demasiado poco radiopacos.","Porque solo pueden utilizarse por vía oral."],1,"TEMA 13","medio","Los contrastes iónicos tradicionales presentan una osmolaridad elevada, asociada a una mayor incidencia de molestias y reacciones adversas. Por ello se extendió el uso de alternativas de menor osmolaridad."],
["¿Qué característica distingue a los contrastes yodados no iónicos?",["Generan numerosas partículas con carga eléctrica.","Contienen radicales hidrofílicos que permiten la hidrosolubilidad sin carga eléctrica.","Son derivados del aceite de dormidera.","Son siempre dímeros iónicos."],1,"TEMA 13","medio","Los contrastes no iónicos incorporan grupos hidrofílicos que permiten que la molécula sea soluble en agua sin disociarse en partículas cargadas eléctricamente."],
["¿Qué diferencia fundamental existe entre un monómero y un dímero en los contrastes yodados?",["El monómero contiene dos anillos de benceno y el dímero uno.","El monómero contiene un anillo de benceno y el dímero dos.","Los monómeros son siempre iónicos y los dímeros siempre no iónicos.","Los monómeros son liposolubles y los dímeros hidrosolubles."],1,"TEMA 13","medio","Un monómero de contraste yodado contiene un anillo de benceno triyodado; un dímero está formado por dos estructuras de este tipo unidas. Esta diferencia influye en su osmolaridad."],
["¿Cuál de los siguientes factores influye en la viscosidad de un contraste?",["La concentración de la solución.","La edad del paciente exclusivamente.","El número de proyecciones realizadas.","El tamaño del detector."],0,"TEMA 13","medio","La concentración de la solución es uno de los factores que más influye en su viscosidad: al aumentar la concentración de contraste, normalmente aumenta también la viscosidad."],
["Respecto a la osmolaridad de los contrastes yodados, ¿cuál de las siguientes asociaciones es correcta?",["Isoosmolares — monómeros iónicos.","Hiperosmolares — monómeros iónicos.","Hiperosmolares — dímeros no iónicos.","Baja osmolaridad — exclusivamente dímeros no iónicos."],1,"TEMA 13","medio","Los monómeros iónicos se disocian en solución y presentan una osmolaridad elevada; por ello los monómeros iónicos tradicionales son hiperosmolares respecto al plasma."],
["¿Cuál de los siguientes es un uso actual de los contrastes yodados liposolubles?",["Urografía intravenosa convencional.","Fistulografía.","Enema opaco.","Exploración oral del tracto gastrointestinal."],1,"TEMA 13","medio","Los contrastes yodados liposolubles tienen usos más específicos. Entre ellos se encuentra la fistulografía, donde pueden utilizarse para delimitar trayectos fistulosos."],
["¿Cuál de las siguientes afirmaciones sobre los contrastes yodados es correcta?",["Tienen una vida media aproximada de 24 horas y se eliminan exclusivamente por vía biliar.","Tienen una vida media aproximada de 2 horas y la mayoría se elimina por vía renal.","Se elimina únicamente el 10 % durante las primeras 24 horas.","Su eliminación se produce exclusivamente por vía intestinal."],1,"TEMA 13","medio","Los contrastes yodados hidrosolubles presentan una vida media plasmática aproximada de unas 2 horas en condiciones normales y se eliminan principalmente por vía renal."]
];
window.topic13Curated = topic13Curated;

// El Tema 13 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank13 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank13().filter(q=>q[3]!=="TEMA 13"); };
