const topic32Curated = [
["¿Cuál es el principio fundamental que debe guiar la realización de una exploración radiológica pediátrica?",["Utilizar siempre los mismos parámetros que en adultos","Obtener la máxima dosis posible para garantizar la imagen","Adaptar la técnica a la edad y constitución, utilizando la mínima dosis necesaria","Evitar cualquier tipo de inmovilización"],2,"TEMA 32","medio","En pediatría la técnica debe adaptarse a la edad y constitución del paciente, utilizando la mínima dosis necesaria para obtener una imagen diagnóstica."],
["En un adolescente de gran tamaño corporal, la técnica radiográfica:",["Debe ser siempre idéntica a la de un lactante","Puede aproximarse a protocolos de adulto, manteniendo las medidas de protección cuando no interfieran","Debe realizarse siempre con los parámetros más bajos posibles independientemente de la región","No requiere protección porque ya tiene características de adulto"],1,"TEMA 32","medio","En pacientes próximos a la constitución adulta pueden utilizarse técnicas similares a las de adultos, manteniendo siempre las medidas de protección adecuadas."],
["En radiología pediátrica, la inmovilización tiene como finalidad principal:",["Aumentar la dosis absorbida","Evitar el movimiento y reducir la posibilidad de repetir la exploración","Sustituir la colimación","Aumentar el tiempo de exposición"],1,"TEMA 32","medio","Su objetivo principal es evitar el movimiento durante la exposición y reducir así la posibilidad de obtener imágenes no diagnósticas y tener que repetirlas."],
["Respecto a la colaboración de un familiar durante una exploración pediátrica:",["Nunca debe permitirse","Puede facilitar la cooperación e inmovilización del niño cuando sea apropiado","Sustituye siempre al técnico","Permite prescindir de las medidas de protección"],1,"TEMA 32","medio","La presencia de un familiar puede facilitar la cooperación e inmovilización del niño cuando sea apropiado, siempre respetando las medidas de protección."],
["En un recién nacido sometido a una exploración portátil, una prioridad especialmente importante es:",["Utilizar tiempos de exposición prolongados","Maximizar la protección del paciente y de los pacientes próximos","Evitar cualquier adaptación de los parámetros","Utilizar siempre protocolos de adulto"],1,"TEMA 32","medio","La prioridad es proteger al paciente y evitar irradiaciones innecesarias de otros pacientes próximos, adaptando la técnica al pequeño tamaño del neonato."],
["¿Cuál de las siguientes medidas NO sería adecuada para optimizar la dosis en pediatría?",["Colimación apropiada","Tiempo de exposición reducido","Activar las herramientas de reducción de dosis disponibles","Aumentar innecesariamente el campo irradiado para evitar repeticiones"],3,"TEMA 32","medio","Aumentar innecesariamente el campo irradiado incrementa la exposición sin aportar beneficio. La colimación, los tiempos cortos y las herramientas de reducción de dosis ayudan a optimizarla."],
["La dosis indicada para una radiografía pediátrica de tórax PA o AP se sitúa aproximadamente entre:",["0,005 y 0,03 mGy","0,05 y 0,3 mGy","0,5 y 3 mGy","5 y 30 mGy"],1,"TEMA 32","medio","El rango de dosis indicado en el material para una radiografía pediátrica de tórax PA o AP es aproximadamente de 0,05–0,3 mGy."],
["En un niño pequeño, el kilovoltaje orientativo para una radiografía de tórax es aproximadamente:",["30 kV","60 kV","100 kV","150 kV obligatoriamente"],1,"TEMA 32","medio","Para un niño pequeño, el kilovoltaje orientativo indicado para la radiografía de tórax es aproximadamente 60 kV."],
["En pacientes pediátricos de tamaño próximo al adulto, el rango de kilovoltaje indicado para tórax puede llegar aproximadamente hasta:",["70 kV","90 kV","120 kV","150 kV"],3,"TEMA 32","medio","En pacientes pediátricos de tamaño próximo al adulto, el rango indicado para tórax puede llegar aproximadamente hasta 120 kV."],
["¿Por qué se utilizan tiempos de exposición cortos en radiología pediátrica?",["Para aumentar la magnificación","Para reducir el artefacto producido por el movimiento","Para aumentar la dosis","Para evitar la colimación"],1,"TEMA 32","medio","Los tiempos cortos reducen la borrosidad producida por los movimientos, especialmente importantes en pacientes pediátricos con dificultad para permanecer quietos."],
["La DFP ideal indicada para una radiografía pediátrica de tórax es:",["50 cm","100 cm",">182 cm","250 cm obligatoriamente"],2,"TEMA 32","difícil","Para la radiografía pediátrica de tórax se indica una distancia foco-película ideal de más de 182 cm, favoreciendo además la reducción de la magnificación cardíaca."],
["Respecto al tamaño del foco en radiología pediátrica, ¿cuál es la combinación correcta?",["Foco ≤5 mm; recomendado 3–4 mm","Foco ≤2 mm; recomendado aproximadamente 0,6–1,2 mm","Foco ≥2 mm; recomendado 4–5 mm","El tamaño del foco no tiene importancia"],1,"TEMA 32","difícil","Se indica un foco ≤2 mm, siendo recomendable aproximadamente 0,6–1,2 mm, para favorecer una buena resolución espacial."],
["En fluoroscopia pediátrica, la utilización del procedimiento debe plantearse:",["De forma rutinaria en todos los pacientes","Solo cuando sea imprescindible","Siempre con fluoroscopia continua","Sin necesidad de valorar la dosis"],1,"TEMA 32","medio","En pediatría la fluoroscopia debe utilizarse únicamente cuando sea imprescindible, porque la exposición puede acumularse rápidamente."],
["¿Qué modalidad de fluoroscopia contribuye especialmente a reducir la dosis?",["Fluoroscopia continua","Fluoroscopia pulsada","Magnificación electrónica permanente","Aumento del número de imágenes"],1,"TEMA 32","medio","La fluoroscopia pulsada reduce la dosis al disminuir el número de pulsos emitidos respecto a la fluoroscopia continua."],
["En un equipo fluoroscópico pediátrico, el panel plano actúa como:",["Generador de rayos X","Receptor digital de imagen","Sistema de refrigeración","Sistema de inmovilización"],1,"TEMA 32","medio","El panel plano es el receptor digital de imagen del equipo fluoroscópico; recibe los rayos X y permite formar la imagen."],
["En un recién nacido prematuro, la utilización de una fuente de calor o infrarrojos durante el procedimiento se relaciona principalmente con:",["El aumento de la resolución espacial","Las dificultades de termorregulación","La reducción del contraste","La disminución del tamaño del campo"],1,"TEMA 32","medio","Los recién nacidos prematuros tienen dificultades para mantener la temperatura corporal, por lo que puede ser necesario utilizar fuentes de calor o infrarrojos durante el procedimiento."],
["Ante una sospecha de perforación intestinal en un paciente pediátrico, ¿qué elemento técnico puede resultar especialmente útil?",["Rayo horizontal","Compresión máxima","Inspiración forzada","Magnificación electrónica"],0,"TEMA 32","difícil","El rayo horizontal permite detectar aire libre intraperitoneal que puede quedar distribuido en posición no dependiente."],
["En un estudio gastrointestinal pediátrico, el bario está contraindicado especialmente cuando existe:",["Estreñimiento","Sospecha de perforación gastrointestinal","Reflujo gastroesofágico","Dolor abdominal inespecífico"],1,"TEMA 32","medio","El bario está contraindicado ante sospecha de perforación gastrointestinal porque su salida fuera de la luz intestinal puede provocar complicaciones."],
["Si existe sospecha de perforación gastrointestinal, una alternativa al bario es:",["Contraste yodado hidrosoluble","Aire exclusivamente","Gadolinio intravenoso","Sulfato de bario más concentrado"],0,"TEMA 32","medio","Ante sospecha de perforación se utiliza un contraste yodado hidrosoluble, que resulta más apropiado en esta situación."],
["¿Por qué se prefieren los contrastes hidrosolubles isoosmolares en determinadas situaciones neonatales?",["Porque aumentan deliberadamente la osmolaridad plasmática","Porque disminuyen el riesgo de alteraciones relacionadas con la osmolaridad","Porque producen mayor irritación intestinal","Porque contienen bario"],1,"TEMA 32","difícil","Los contrastes hidrosolubles isoosmolares disminuyen el riesgo de alteraciones relacionadas con cambios importantes de osmolaridad."],
["La aspiración de un contraste hiperosmolar puede provocar:",["Neumonitis química","Neumotórax espontáneo","Hemorragia cerebral","Osteopenia"],0,"TEMA 32","medio","Si se aspira un contraste hiperosmolar puede producirse neumonitis química, por lo que debe evitarse especialmente en pacientes con riesgo de aspiración."],
["En el esofagograma pediátrico, el estudio debe abarcar aproximadamente desde:",["La laringe hasta el píloro","La nasofaringe hasta el fundus gástrico","El estómago hasta el yeyuno","El colon hasta el recto"],1,"TEMA 32","medio","El esofagograma debe estudiar aproximadamente desde la nasofaringe hasta el fundus gástrico, permitiendo valorar el trayecto esofágico y su relación con el estómago."],
["En el estudio gastrointestinal superior pediátrico, uno de los objetivos anatómicos fundamentales es valorar:",["La articulación ileocecal exclusivamente","La unión duodeno-yeyunal","El recto","La vejiga"],1,"TEMA 32","medio","Uno de los objetivos fundamentales del estudio gastrointestinal superior es valorar la unión duodeno-yeyunal, además del resto del tracto estudiado."],
["Durante un tránsito gastrointestinal superior pediátrico, respecto al reflujo:",["Debe provocarse sistemáticamente","Debe provocarse mediante compresión abdominal","No debe provocarse artificialmente","Es irrelevante"],2,"TEMA 32","difícil","El reflujo no debe provocarse artificialmente durante el estudio. Si aparece de forma espontánea, se documenta."],
["En el estudio del intestino delgado pediátrico, los controles radiográficos indicados son aproximadamente:",["5, 10 y 20 minutos","15, 30 minutos y 1 hora","30 minutos, 2 y 4 horas","Solo una imagen final"],1,"TEMA 32","medio","Los controles radiográficos indicados son aproximadamente a los 15 y 30 minutos y a la hora, según el material."],
["En un enema pediátrico convencional, ¿cuál de las siguientes situaciones constituye una contraindicación?",["Perforación de colon","Estreñimiento","Sospecha de enfermedad de Hirschsprung","Invaginación intestinal"],0,"TEMA 32","medio","La perforación de colon constituye una contraindicación para realizar un enema convencional."],
["En un recién nacido al que se realiza un enema, el contraste preferido es:",["Bario exclusivamente","Contraste hidrosoluble isoosmolar","Contraste hiperosmolar siempre","Contraste intravenoso"],1,"TEMA 32","difícil","En el recién nacido se prefiere un contraste hidrosoluble isoosmolar, especialmente en determinadas situaciones neonatales."],
["Durante un enema pediátrico, el llenado completo del colon puede confirmarse mediante:",["Únicamente la visualización del recto","Reflujo del contraste hacia el intestino delgado o identificación de referencias ileocecales","La desaparición del contraste del recto","La ausencia de contraste en el ciego"],1,"TEMA 32","difícil","El llenado completo puede confirmarse mediante el reflujo del contraste hacia el intestino delgado o identificando referencias anatómicas ileocecales."],
["Ante una invaginación intestinal pediátrica, la técnica diagnóstica de elección es:",["Radiografía simple exclusivamente","Ecografía","Resonancia magnética","Radiografía de tórax"],1,"TEMA 32","medio","La ecografía es la técnica diagnóstica de elección y permite identificar la típica imagen de asas intestinales concéntricas."],
["Además de diagnosticar una invaginación intestinal, la ecografía puede permitir:",["Reducirla mediante un enema de suero sin utilizar radiación ionizante","Sustituir siempre la cirugía","Administrar contraste intravenoso","Realizar una CUMS"],0,"TEMA 32","difícil","La ecografía puede utilizarse para guiar la reducción mediante enema, evitando radiación ionizante cuando se realiza bajo control ecográfico."],
["En el estudio de la enfermedad de Hirschsprung, la sonda rectal debe:",["Ser lo más grande posible y llevar balón inflado","Ser blanda, de pequeño calibre y sin inflar el balón","Introducirse profundamente hasta el colon descendente","Utilizar siempre balón de gran volumen"],1,"TEMA 32","difícil","La sonda debe ser blanda y de pequeño calibre, y no se debe inflar el balón, para evitar distender artificialmente la zona estudiada."],
["En la enfermedad de Hirschsprung, el objetivo radiológico fundamental es identificar:",["La válvula ileocecal","La zona de transición","El fundus gástrico","La pelvis renal"],1,"TEMA 32","medio","El objetivo fundamental del estudio radiológico es identificar la zona de transición entre el segmento afectado y el intestino de calibre normal."],
["En el íleo meconial neonatal, el enema con contraste hidrosoluble puede tener además una función:",["Diagnóstica y terapéutica","Exclusivamente preventiva","Exclusivamente anestésica","Exclusivamente vascular"],0,"TEMA 32","medio","El enema con contraste hidrosoluble puede tener una doble función, diagnóstica y terapéutica, ayudando a movilizar el meconio."],
["En la cistouretrografía miccional seriada (CUMS), el objetivo principal incluye valorar:",["Únicamente la vejiga","Vejiga, uretra y especialmente la existencia de reflujo vesicoureteral","Solo los riñones","Únicamente el uréter distal"],1,"TEMA 32","medio","La CUMS permite estudiar vejiga y uretra y, especialmente, detectar la existencia de reflujo vesicoureteral durante la micción."],
["Se realiza una CUMS a un niño pequeño para estudiar un posible reflujo vesicoureteral. ¿Cuál de las siguientes combinaciones es la más correcta?",["Cateterización aséptica, contraste yodado, control fluoroscópico y valoración durante la micción","Catéter con balón de gran calibre, bario y radiografía única al finalizar","Contraste intravenoso y proyección AP exclusivamente","Sin cateterización, utilizando únicamente una radiografía simple"],0,"TEMA 32","difícil","La técnica correcta incluye cateterización aséptica, administración de contraste yodado, control fluoroscópico y valoración de la vejiga y uretra durante la micción."]
];

window.topic32Curated = topic32Curated;

const previousTopicMenu32 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu32();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 32'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 32</span><h3>${esc((topics[32]||{}).title||'TEMA 32')}</h3><p>${topic32Curated.length} preguntas · radiología pediátrica</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 32', topic32Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 32</span><h3>${esc((topics[32]||{}).title||'TEMA 32')}</h3><p>${topic32Curated.length} preguntas · radiología pediátrica</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 32', topic32Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 32; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
