// Banco curado del TEMA 6. Preguntas redactadas manualmente a partir del contenido real del tema.
const topic6Curated=[
['¿Cuál es la unidad básica de información en informática?',['El bit','El byte','El píxel','La matriz'],0,'TEMA 6','fácil'],
['¿Cuántos bits forman un byte?',['8','4','16','32'],0,'TEMA 6','fácil'],
['¿Qué representa un píxel en una imagen digital?',['La unidad mínima de imagen a la que se asigna un valor','El conjunto total de píxeles de una imagen','La cantidad de bits de almacenamiento','La densidad de píxeles por pulgada'],0,'TEMA 6','fácil'],
['¿Qué indica la profundidad de color de una imagen digital?',['El número de colores diferentes que puede representar un píxel','El número total de píxeles de la imagen','La densidad de píxeles por unidad de superficie','El tamaño del archivo en bytes'],0,'TEMA 6','fácil'],
['¿Qué se entiende por matriz en una imagen digital?',['El número total de píxeles que forman la imagen','El número de colores que puede representar un píxel','La densidad de píxeles por pulgada','La cantidad de bits de un byte'],0,'TEMA 6','fácil'],
['¿Qué expresa la resolución de una imagen digital?',['La densidad de píxeles por unidad de superficie','El número total de píxeles','El número de colores por píxel','El tamaño del archivo en bytes'],0,'TEMA 6','fácil'],
['¿En qué unidad se puede expresar la resolución de una imagen digital?',['Píxeles por pulgada (ppi)','Bytes por píxel','Bits por pulgada exclusivamente','Kilovoltios por pulgada'],0,'TEMA 6','medio'],
['¿Qué ocurre en un sistema de imagen digital cuando los rayos X llegan al receptor?',['Se recogen y cuantifican los valores correspondientes a los píxeles y se les asigna un valor numérico','Impresionan directamente una placa radiográfica','Generan una imagen visible sin ningún procesamiento','Se convierten exclusivamente en luz visible para el observador'],0,'TEMA 6','medio'],
['¿Cuál es una diferencia fundamental entre una imagen analógica y una digital?',['La imagen digital representa la información mediante valores numéricos asociados a los píxeles','La imagen analógica está formada siempre por píxeles','La imagen digital necesita obligatoriamente una placa radiográfica','La imagen analógica se almacena siempre como un archivo electrónico'],0,'TEMA 6','fácil'],
['¿Qué elemento constituye la unidad básica de almacenamiento de información según la terminología informática del tema?',['El byte','El píxel','La matriz','El bit de color'],0,'TEMA 6','fácil'],
['Una imagen digital tiene una matriz de 512 × 512. ¿Qué representa este dato?',['El número de píxeles distribuidos en filas y columnas','La profundidad de color de cada píxel','La resolución expresada en ppi','El tamaño del archivo en bytes'],0,'TEMA 6','medio'],
['¿Qué relación existe entre la matriz y el número total de píxeles de una imagen?',['El número total de píxeles se obtiene multiplicando las dimensiones de la matriz','La matriz indica únicamente el número de colores','La matriz indica únicamente el tamaño del archivo','La matriz y el número de píxeles no están relacionados'],0,'TEMA 6','medio'],
['¿Qué característica permite diferenciar una imagen digital por el número de niveles de color disponibles para cada píxel?',['La profundidad de color','La matriz','La resolución','El byte'],0,'TEMA 6','medio'],
['¿Qué sucede al aumentar la profundidad de color?',['Cada píxel puede representar un mayor número de colores o niveles','Disminuye necesariamente el número de píxeles','Se reduce siempre la resolución espacial','La imagen deja de ser digital'],0,'TEMA 6','medio'],
['¿Cuál de las siguientes unidades representa una cantidad de información binaria?',['Bit','Píxel','Ppi','Matriz'],0,'TEMA 6','fácil'],
['¿Qué modalidad de imagen se menciona como ejemplo de proceso electrónico en la evolución hacia la digitalización?',['Ecografía','Radiografía convencional analógica','Radiografía con película exclusivamente','Fluoroscopia analógica exclusivamente'],0,'TEMA 6','medio'],
['¿Qué modalidades contribuyeron al desarrollo de sistemas informatizados en diagnóstico por imagen?',['TAC y resonancia magnética, junto con otras modalidades digitalizadas','Únicamente la radiografía convencional con película','Solo la fluoroscopia analógica','Exclusivamente la fotografía médica'],0,'TEMA 6','medio'],
['¿Qué sistemas informáticos permiten sistematizar, organizar y gestionar la gran cantidad de imágenes producidas en diagnóstico por imagen?',['RIS y PACS','Bit y byte','Píxel y matriz','kV y mAs'],0,'TEMA 6','fácil'],
['¿Qué significa que los valores de los píxeles de una imagen digital estén cuantificados?',['Que la información de la imagen se representa mediante valores numéricos','Que todos los píxeles tienen necesariamente el mismo valor','Que la imagen se ha impreso sobre película','Que los píxeles se han eliminado de la imagen'],0,'TEMA 6','medio'],
['¿Cuál es la principal diferencia en la formación de la imagen entre el sistema analógico y el digital descrita en el tema?',['En el analógico los rayos X impresionan una placa; en el digital se cuantifican electrónicamente los valores recibidos por los píxeles','En el analógico se utilizan píxeles y en el digital una placa','Ambos sistemas forman la imagen exactamente del mismo modo','El digital no utiliza radiación para formar imágenes radiográficas'],0,'TEMA 6','medio'],
['¿Qué término informático se utiliza para denominar a la unidad básica de información binaria?',['Bit','Byte','Píxel','Ppi'],0,'TEMA 6','fácil'],
['¿Qué término informático se utiliza para una secuencia de 8 bits?',['Byte','Bit','Píxel','Matriz'],0,'TEMA 6','fácil'],
['Si una imagen tiene una resolución de 100 ppi, ¿qué expresa principalmente este valor?',['Que contiene 100 píxeles por pulgada','Que cada píxel contiene 100 bits','Que la imagen tiene 100 píxeles en total','Que el archivo ocupa 100 bytes'],0,'TEMA 6','medio'],
['¿Qué relación existe entre píxel y resolución?',['La resolución expresa la densidad de píxeles por unidad de superficie','El píxel expresa la densidad de píxeles por unidad de superficie','Son términos que designan exactamente lo mismo','La resolución indica únicamente el número de colores'],0,'TEMA 6','medio'],
['¿Qué información aporta la matriz de una imagen digital?',['Permite conocer cómo se distribuyen los píxeles en filas y columnas y, por tanto, el número total de píxeles','Indica directamente el número de colores de cada píxel','Indica exclusivamente el tamaño físico del paciente','Determina por sí sola el número de bits de cada byte'],0,'TEMA 6','medio'],
['¿Qué consecuencia tiene disponer de un mayor número de píxeles en una misma superficie?',['Aumenta la densidad de píxeles y puede mejorar la resolución espacial','Disminuye siempre la cantidad de información','Reduce necesariamente la profundidad de color a cero','Convierte una imagen digital en analógica'],0,'TEMA 6','difícil'],
['¿Cuál de las siguientes afirmaciones describe mejor una imagen digital?',['Es un archivo electrónico en el que los valores de los píxeles están representados numéricamente','Es una imagen que solo puede observarse mediante una película radiográfica','Es una imagen formada exclusivamente por señales analógicas','Es una imagen que no puede almacenarse ni procesarse informáticamente'],0,'TEMA 6','fácil'],
['¿Por qué la digitalización de las imágenes favoreció el desarrollo de los sistemas informáticos en diagnóstico por imagen?',['Porque permite almacenar, organizar, gestionar y distribuir grandes cantidades de información de imagen en formato electrónico','Porque elimina la necesidad de representar la imagen mediante píxeles','Porque impide el procesamiento informático de las imágenes','Porque obliga a utilizar exclusivamente películas radiográficas'],0,'TEMA 6','medio'],
['¿Qué sistema está orientado específicamente al almacenamiento y distribución de imágenes médicas?',['PACS','RIS','Bit','Byte'],0,'TEMA 6','fácil'],
['¿Qué sistema está relacionado con la gestión de la información radiológica y el flujo de trabajo?',['RIS','PACS','Píxel','Matriz'],0,'TEMA 6','medio'],
['Una imagen digital presenta una matriz de 1024 × 1024 píxeles. ¿Cuántos píxeles contiene?',['1.048.576','2.048','10.240','1.024'],0,'TEMA 6','difícil'],
['¿Qué afirmación diferencia correctamente profundidad de color y resolución?',['La profundidad de color se refiere a los colores representables por píxel y la resolución a la densidad de píxeles','Ambas expresan el número de colores por píxel','La resolución expresa siempre el tamaño del archivo','La profundidad de color indica exclusivamente el número total de píxeles'],0,'TEMA 6','difícil']
];
const topic6Specific=topic6Curated;

// Integración aislada del TEMA 6: se ejecuta después de tests-bank.js y solo amplía el menú por temas.
const topic6MenuOverride=()=>{
  const generated=[...buildTopicBank(),...topic1Curated,...topic2Curated,...topic3Curated,...topic4Specific,...topic5Specific,...topicSpecific,...topic6Curated];
  const byTopic={};
  generated.forEach(q=>(byTopic[q[3]]??=[]).push(q));
  const entries=Object.keys(byTopic).sort((a,b)=>+a.split(' ')[1]-+b.split(' ')[1]);
  ws.hidden=false;
  ws.innerHTML=`<div class="study-material"><p class="eyebrow">TEST POR TEMAS</p><h2>📚 Elige un tema</h2><p>Cada tema tiene un banco propio de preguntas generado a partir del contenido real. El número disponible aparece en cada tarjeta.</p><div class="cards">${entries.map((n,i)=>`<button class="module-card" data-topic="${i}"><span class="module-number">${n}</span><h3>${esc((topics[n.split(' ')[1]]||{}).title||n)}</h3><p>${byTopic[n].length} preguntas disponibles</p><span class="module-action">Entrenar →</span></button>`).join('')}</div></div>`;
  ws.querySelectorAll('[data-topic]').forEach((b,i)=>b.onclick=()=>session(entries[i],byTopic[entries[i]]));
};
topicMenu=topic6MenuOverride;
