// Test curado del TEMA 33 · ESTUDIO RADIOLÓGICO DE LA MAMA, MX Y GALACTO MX
const topic33Curated = [
  ["¿Cuál es el objetivo principal de la mamografía?", ["Obtener imágenes de alta resolución y buen contraste para detectar patología mamaria", "Valorar exclusivamente la movilidad de la mama", "Estudiar únicamente los ganglios axilares", "Sustituir siempre a la ecografía"], 0, "TEMA 33", "fácil", "La mamografía busca imágenes de alta resolución y buen contraste que permitan detectar y caracterizar patología mamaria, especialmente lesiones pequeñas."],
  ["¿Entre qué costillas se extiende aproximadamente la mama según el material?", ["De la segunda a la séptima costilla", "De la primera a la cuarta costilla", "De la cuarta a la décima costilla", "De la séptima a la duodécima costilla"], 0, "TEMA 33", "medio", "Según el material, la mama se extiende aproximadamente desde la segunda hasta la séptima costilla."],
  ["¿Qué estructuras forman una especie de picos que unen el tejido mamario con la piel?", ["Los ligamentos de Cooper", "Los conductos galactóforos", "La fascia retromamaria", "Los músculos pectorales"], 0, "TEMA 33", "fácil", "Los ligamentos de Cooper son estructuras fibrosas que atraviesan el tejido mamario y conectan la fascia profunda con la piel, formando prolongaciones o picos."],
  ["¿Cuántos conductos mayores se abren aproximadamente en el pezón?", ["Entre 8 y 20", "Entre 1 y 4", "Entre 20 y 40", "Más de 50"], 0, "TEMA 33", "medio", "Aproximadamente 8–20 conductos galactóforos se abren en el pezón."],
  ["¿Qué sucede con la mama durante la involución asociada a la edad?", ["Disminuyen las células acinares y aumenta el componente fibrótico", "Aumentan siempre los acinos y disminuye la fibrosis", "Desaparecen todos los conductos", "Se transforma exclusivamente en tejido muscular"], 0, "TEMA 33", "medio", "Con la edad disminuyen las células acinares y aumenta progresivamente el componente fibroso."],
  ["¿Qué sistema de nomenclatura se utiliza habitualmente para identificar y localizar lesiones mamarias?", ["División en cuadrantes tomando el pezón como centro", "División en ocho segmentos sin referencia anatómica", "Clasificación exclusivamente por profundidad", "Numeración según el tamaño de la lesión"], 0, "TEMA 33", "fácil", "La división en cuadrantes tomando el pezón como centro permite localizar de forma estandarizada las lesiones mamarias."],
  ["¿Qué materiales puede utilizar el ánodo del equipo de mamografía para favorecer un buen contraste?", ["Molibdeno o rodio", "Plomo o aluminio", "Cobre o hierro", "Selenio o silicio"], 0, "TEMA 33", "medio", "El molibdeno y el rodio permiten obtener un espectro de rayos X adecuado para conseguir buen contraste en el tejido mamario."],
  ["¿Qué tamaño de puntos focales se indica en el material para mamografía?", ["0,3 y 0,1 mm", "1 y 2 mm", "3 y 5 mm", "0,8 y 1,5 mm"], 0, "TEMA 33", "medio", "Los tamaños indicados son 0,3 mm y 0,1 mm, permitiendo trabajar con un foco pequeño para mejorar la resolución espacial."],
  ["¿Cuál es una de las principales ventajas de una buena compresión mamaria?", ["Reduce la dosis y la borrosidad por movimiento", "Aumenta la radiación dispersa", "Disminuye la resolución espacial", "Hace innecesaria la correcta colocación"], 0, "TEMA 33", "fácil", "La compresión reduce el grosor de la mama, disminuye la dosis necesaria y limita la borrosidad producida por el movimiento."],
  ["¿Qué efecto tiene la compresión sobre la resolución espacial en mamografía?", ["La mejora al disminuir las distancias entre los tejidos", "La empeora siempre", "No tiene ningún efecto", "La elimina por completo"], 0, "TEMA 33", "medio", "Al comprimir se reducen las distancias entre las diferentes estructuras mamarias, facilitando su diferenciación."],
  ["¿Cómo se realiza habitualmente la mamografía respecto a la posición de la paciente?", ["En bipedestación", "En decúbito supino", "En decúbito prono", "Siempre sentada"], 0, "TEMA 33", "fácil", "La mamografía se realiza habitualmente en bipedestación, permitiendo colocar y comprimir correctamente la mama."],
  ["¿Qué característica debe tener una mamografía técnicamente adecuada respecto a las dos mamas?", ["Deben estar lo más simétricas posible y proyectar la mayor cantidad de tejido posible", "Una mama debe quedar siempre fuera del campo", "Solo debe incluirse el pezón", "La simetría no tiene importancia"], 0, "TEMA 33", "medio", "Ambas mamas deben quedar lo más comparables posible y debe incluirse la mayor cantidad de tejido mamario viable."],
  ["En la proyección OML de mamografía, ¿qué angulación del tubo se indica en el material?", ["45°", "15°", "30°", "90°"], 0, "TEMA 33", "fácil", "La proyección oblicua medio-lateral se realiza con una angulación del tubo de aproximadamente 45°."],
  ["En la proyección OML, ¿qué estructura debe visualizarse cruzando la mitad superior de la placa?", ["El pectoral mayor", "El esternón", "La clavícula completa", "El dorsal ancho"], 0, "TEMA 33", "medio", "El músculo pectoral mayor debe visualizarse y sirve además como referencia para valorar la correcta inclusión del tejido posterior."],
  ["En la proyección CC, el tubo se coloca con el rayo:", ["Perpendicular al suelo", "A 45° respecto al suelo", "Paralelo al suelo", "Siempre a 20°"], 0, "TEMA 33", "fácil", "En la proyección craneocaudal, el rayo se dirige perpendicular al suelo."],
  ["¿Qué debe incluir idealmente la proyección CC?", ["Todo el tejido fibroglandular", "Solo el cuadrante superior externo", "Únicamente la región retroareolar", "Solo la cola axilar"], 0, "TEMA 33", "medio", "Idealmente debe incluirse todo el tejido fibroglandular, evitando dejar zonas mamarias fuera del campo."],
  ["¿Qué proyección adicional es útil para estudiar lesiones de la mitad lateral de la mama?", ["CC exagerada lateralmente", "Proyección valle", "LM", "Caudo craneal modificada"], 0, "TEMA 33", "fácil", "La CC exagerada lateralmente desplaza el tejido lateral hacia el campo y resulta útil cuando interesa estudiar una lesión situada en esa zona."],
  ["¿Para qué sirve especialmente la proyección de cola axilar o Cleopatra?", ["Para separar y visualizar mejor la cola axilar y localizar lesiones en ella", "Para estudiar exclusivamente el tejido medial", "Para sustituir siempre a la proyección CC", "Para visualizar únicamente el pezón"], 0, "TEMA 33", "medio", "La proyección de cola axilar o Cleopatra permite separar y visualizar mejor la cola axilar, facilitando la localización de lesiones en esta región."],
  ["En la proyección Cleopatra, ¿qué angulación del tubo se indica?", ["20° y paralelo a la cola axilar", "45° y perpendicular a la cola", "90° y paralelo al esternón", "10° y paralelo al suelo"], 0, "TEMA 33", "difícil", "En la proyección Cleopatra, el tubo se angula aproximadamente 20° y se coloca paralelo a la cola axilar, adaptándose a su orientación."],
  ["¿Qué objetivo tiene la proyección valle?", ["Visualizar el tejido situado cerca del esternón", "Separar exclusivamente la cola axilar", "Estudiar la región posterior del hombro", "Valorar únicamente el pezón"], 0, "TEMA 33", "fácil", "La proyección valle permite visualizar mejor el tejido situado cerca del esternón, especialmente las regiones mediales profundas."],
  ["¿Cuándo puede ser especialmente útil la proyección ML de 90°?", ["Cuando una lesión se ve en la OML pero no en la CC y se quiere comprobar si es real o una superposición", "Solo para estudiar el esternón", "Únicamente en pacientes con prótesis", "Para sustituir la compresión"], 0, "TEMA 33", "medio", "La ML de 90° ayuda a determinar si una lesión que aparece en la OML pero no en la CC corresponde a una lesión real o a una superposición de tejidos."],
  ["¿Qué proyecciones perpendiculares pueden ser necesarias para la colocación de un arpón?", ["Dos proyecciones perpendiculares entre sí", "Dos proyecciones idénticas", "Solo una proyección CC", "Solo una proyección OML"], 0, "TEMA 33", "medio", "Para localizar correctamente la lesión en el espacio se necesitan dos proyecciones perpendiculares entre sí."],
  ["¿Cuándo puede ser preferible una proyección LM frente a una ML?", ["Cuando existe una lesión en los tejidos mediales de la mama", "Cuando solo interesa la cola axilar", "Cuando se quiere evitar toda compresión", "Solo en la mama masculina"], 0, "TEMA 33", "medio", "La LM puede ser preferible cuando la lesión está situada en los tejidos mediales, ya que puede mejorar su representación."],
  ["¿En qué pacientes puede utilizarse especialmente la proyección caudo-craneal modificada?", ["Mujeres con mucha cifosis, mamas pequeñas y varones", "Solo mujeres jóvenes", "Solo pacientes con prótesis", "Exclusivamente pacientes en decúbito"], 0, "TEMA 33", "difícil", "Puede ser especialmente útil en mujeres con mucha cifosis, mamas pequeñas y varones, cuando la posición estándar resulta más difícil."],
  ["¿Qué sistema se utiliza para estandarizar los hallazgos y los informes mamográficos?", ["BIRADS", "PACS", "DICOM", "RIS"], 0, "TEMA 33", "fácil", "BI-RADS es el sistema estandarizado utilizado para describir los hallazgos mamográficos y establecer categorías que orientan el manejo."],
  ["¿Cuál es la lesión sólida más frecuente de la mama según el material?", ["Fibroadenoma", "Quiste", "Carcinoma ductal", "Mastopatía fibroquística"], 0, "TEMA 33", "medio", "El fibroadenoma es la lesión sólida benigna más frecuente de la mama según el material."],
  ["¿Qué característica es típica de los quistes mamarios según el material?", ["Suelen verse como densidades redondeadas y bien definidas", "Siempre presentan márgenes espiculados", "Solo aparecen después de la menopausia", "Son siempre lesiones malignas"], 0, "TEMA 33", "medio", "Los quistes mamarios suelen aparecer como densidades redondeadas y bien definidas en mamografía."],
  ["¿Cuál es el tipo histológico de cáncer de mama más frecuente indicado en el material?", ["Carcinoma ductal", "Carcinoma lobulillar", "Enfermedad de Paget", "Fibroadenoma"], 0, "TEMA 33", "fácil", "El carcinoma ductal es el tipo histológico de cáncer de mama más frecuente indicado en el material."],
  ["¿Dónde puede situarse una prótesis mamaria en relación con el músculo pectoral?", ["Retroglandular o retropectoral", "Intracutánea o intraósea", "Subdérmica o intrapulmonar", "Exclusivamente retroesternal"], 0, "TEMA 33", "fácil", "Una prótesis mamaria puede encontrarse en posición retroglandular o retropectoral, según su relación con el músculo pectoral."],
  ["¿En qué consiste básicamente la técnica de Eklund en pacientes con prótesis mamarias?", ["Desplazar la prótesis hacia atrás y traccionar el tejido mamario hacia delante", "Comprimir directamente la prótesis con máxima fuerza", "Retirar temporalmente la prótesis", "Evitar todas las proyecciones estándar"], 0, "TEMA 33", "medio", "La técnica de Eklund consiste en desplazar la prótesis hacia atrás y traccionar el tejido mamario hacia delante para poder comprimir y visualizar la mayor cantidad posible de tejido."],
  ["¿Qué procedimiento permite obtener cilindros de tejido para el diagnóstico de una lesión mamaria?", ["BAG (biopsia con aguja gruesa)", "PAAF exclusivamente", "Galactografía", "Tomosíntesis"], 0, "TEMA 33", "fácil", "La biopsia con aguja gruesa permite obtener cilindros de tejido que posteriormente pueden estudiarse anatomopatológicamente."],
  ["¿Qué técnica intervencionista mamaria se basa en el cálculo de coordenadas de la lesión?", ["Estereotaxia mediante mamografía", "Ecografía Doppler", "Galactografía", "Técnica de Eklund"], 0, "TEMA 33", "medio", "La estereotaxia utiliza imágenes mamográficas para calcular las coordenadas espaciales de una lesión y dirigir con precisión el procedimiento intervencionista."],
  ["En la galactografía, ¿qué tipo de contraste se utiliza y cómo se obtienen las imágenes?", ["Contraste yodado hidrosoluble radiopaco, con proyecciones CC y lateral sin compresión", "Bario, con proyecciones OML y CC con compresión", "Gadolinio, únicamente en lateral", "Microburbujas, sin radiografía"], 0, "TEMA 33", "difícil", "La galactografía utiliza contraste yodado hidrosoluble radiopaco y se realizan proyecciones CC y lateral, sin compresión, para estudiar los conductos galactóforos."],
  ["¿Cuál es una indicación de la galactografía?", ["Secreción patológica por el pezón", "Dolor mamario inespecífico como única indicación", "Cualquier fibroadenoma conocido", "Cribado rutinario de todas las mujeres"], 0, "TEMA 33", "medio", "La galactografía está especialmente indicada ante una secreción patológica por el pezón, para investigar alteraciones de los conductos." ]
];

window.topic33Curated = topic33Curated;

const previousTopicMenu33 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu33();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 33'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 33</span><h3>${esc((topics[33]||{}).title||'TEMA 33')}</h3><p>${topic33Curated.length} preguntas · mama, mamografía y galactografía</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 33', topic33Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 33</span><h3>${esc((topics[33]||{}).title||'TEMA 33')}</h3><p>${topic33Curated.length} preguntas · mama, mamografía y galactografía</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 33', topic33Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 33; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
