// Banco curado del TEMA 8. Preguntas redactadas a partir del contenido real del tema.
const topic8Curated = [
  ['¿Qué característica distingue al sistema CR frente a un sistema de captura digital directa?', ['La imagen se registra primero en un soporte que debe ser procesado por un lector','La imagen se obtiene en tiempo real mediante una capa de selenio amorfo','La radiación se convierte directamente en carga eléctrica en una matriz TFT','El detector necesita un centelleador para generar la señal inicial'], 0, 'TEMA 8', 'medio'],
  ['Tras exponer un soporte de imagen de un sistema CR, ¿qué ocurre en el lector?', ['El soporte es extraído del chasis y su información se obtiene mediante lectura láser','El chasis se revela químicamente antes de obtener la imagen','El soporte se convierte directamente en una señal eléctrica mediante selenio amorfo','El panel se sincroniza con el tubo y transmite la imagen por radiofrecuencia'], 0, 'TEMA 8', 'medio'],
  ['¿Qué compuesto es el más utilizado en el soporte de imagen de los sistemas CR?', ['Fluorobromuro de bario','Selenio amorfo','Yoduro de cesio','Oxisulfuro de gadolinio'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué fenómeno permite recuperar en forma de luz la energía almacenada en el soporte de imagen CR?', ['Luminiscencia fotoestimulada','Fluorescencia convencional','Electroluminiscencia','Termoluminiscencia'], 0, 'TEMA 8', 'medio'],
  ['¿Qué relación existe entre la luz ultravioleta liberada por el soporte CR y la radiación que recibió?', ['La intensidad de la luz es proporcional a la radiación recibida','La intensidad de la luz es independiente de la radiación recibida','La luz solo aparece si el soporte no ha recibido radiación','La luz sustituye al conversor analógico/digital'], 0, 'TEMA 8', 'medio'],
  ['¿Qué función desempeña el fotomultiplicador durante la lectura de un soporte CR?', ['Recoger la luz ultravioleta liberada por el soporte','Convertir los rayos X directamente en carga eléctrica','Borrar la información residual del soporte','Sincronizar el tubo de rayos X con el detector'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué sucede con la información obtenida del soporte CR antes de convertirse en imagen digital?', ['Se transforma mediante un conversor analógico/digital de información luminosa a datos numéricos','Se transforma mediante un centelleador en luz visible','Se almacena en una película para su posterior revelado','Se convierte directamente en una señal de ultrasonidos'], 0, 'TEMA 8', 'medio'],
  ['¿Cómo se prepara un soporte CR después de haber sido leído para poder reutilizarlo?', ['Se borra exponiéndolo a luz blanca intensa','Se borra calentándolo a alta temperatura','Se destruye y se sustituye por un panel plano','Se vuelve a irradiar con rayos X'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué función cumple la estación de trabajo en el procesamiento de una imagen CR?', ['Procesa la imagen mediante filtros y algoritmos hasta obtener la imagen diagnóstica','Realiza la lectura láser del soporte de imagen','Genera la diferencia de potencial del detector','Convierte los rayos X en luz mediante un centelleador'], 0, 'TEMA 8', 'medio'],
  ['¿Qué característica define al sistema DX descrito en el tema?', ['El material de captura y la electrónica de lectura están integrados en un mismo dispositivo','La imagen queda almacenada en un soporte CR que debe extraerse del chasis','La captura depende de una película convencional','La imagen solo puede obtenerse después de revelar el detector'], 0, 'TEMA 8', 'fácil'],
  ['¿Cuál es la principal diferencia en el tiempo de obtención de la imagen entre CR y DX?', ['DX permite disponer de la imagen digital en pocos segundos tras la exposición','CR siempre proporciona la imagen antes que DX','Ambos requieren exactamente el mismo proceso de lectura','DX necesita revelar el soporte antes de mostrar la imagen'], 0, 'TEMA 8', 'medio'],
  ['En un detector de captura directa, ¿qué transformación experimentan los fotones de rayos X?', ['Se transforman directamente en una señal eléctrica','Se transforman primero en luz y después en señal eléctrica','Se almacenan en una placa y se liberan mediante láser','Se convierten primero en ultrasonidos'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué material constituye la capa encargada de captar los rayos X en un detector de captura directa?', ['Selenio amorfo','Yoduro de cesio','Oxisulfuro de gadolinio','Silicio amorfo'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué función tiene la capa de condensadores y transistores TFT en un detector de captura directa?', ['Recoger y organizar la carga eléctrica generada para formar la información de la imagen','Convertir los rayos X en luz visible','Eliminar la señal residual mediante luz blanca','Generar los fotones de rayos X'], 0, 'TEMA 8', 'medio'],
  ['¿Qué elemento transforma la carga eléctrica de la matriz de un detector de captura directa en información digital?', ['El conversor analógico/digital','El fotomultiplicador','El centelleador','El soporte de imagen'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué función desempeña la base de cristal en un detector de captura directa?', ['Proporcionar soporte y aislamiento al resto de componentes','Convertir los rayos X en luz','Recoger la luz del centelleador','Generar la diferencia de potencial'], 0, 'TEMA 8', 'medio'],
  ['Durante la captura directa descrita en el tema, ¿qué efecto produce la diferencia de potencial aplicada al selenio?', ['Favorece que la carga generada por los fotones se transfiera hacia la matriz','Convierte el selenio en un centelleador','Hace que el detector emita luz ultravioleta','Borra automáticamente la imagen anterior'], 0, 'TEMA 8', 'difícil'],
  ['¿Qué caracteriza a la captura indirecta frente a la captura directa?', ['Los rayos X se convierten primero en fotones de luz y posteriormente en carga eléctrica','Los rayos X generan directamente la carga eléctrica en el selenio','La imagen se obtiene mediante un soporte CR','No existe conversión de la radiación en señal eléctrica'], 0, 'TEMA 8', 'medio'],
  ['¿Qué combinación corresponde a los materiales centelleadores indicados para la captura indirecta?', ['Yoduro de cesio y oxisulfuro de gadolinio','Selenio amorfo y silicio amorfo','Fluorobromuro de bario y selenio','Plomo y aluminio'], 0, 'TEMA 8', 'fácil'],
  ['En un detector de captura indirecta, ¿qué componente recibe la luz producida por el centelleador?', ['Los fotodiodos de silicio amorfo','La capa de selenio amorfo','El fotomultiplicador del lector CR','El soporte de imagen del chasis'], 0, 'TEMA 8', 'medio'],
  ['¿Cuál es la secuencia correcta de conversión en un detector de captura indirecta?', ['Rayos X → luz → carga eléctrica → señal digital','Rayos X → carga eléctrica → luz → señal digital','Rayos X → luz → rayos X → señal digital','Rayos X → señal digital → luz → carga eléctrica'], 0, 'TEMA 8', 'medio'],
  ['¿Qué elemento diferencia principalmente la matriz de un detector indirecto respecto a la de uno directo?', ['En la captura indirecta la matriz incorpora fotodiodos de silicio amorfo','En la captura indirecta la matriz está formada por selenio amorfo','En la captura indirecta no existe matriz','En la captura indirecta la matriz está formada por fluorobromuro de bario'], 0, 'TEMA 8', 'difícil'],
  ['¿Qué se entiende por panel plano integrado?', ['Un detector instalado en la mesa o en el dispositivo mural y sincronizado con el tubo','Un detector portátil que siempre se utiliza mediante cable','Un soporte CR que debe introducirse en un lector','Un panel reservado exclusivamente para biopsias mamarias'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué característica define a un panel plano portátil?', ['Puede desplazarse y conectarse al procesador mediante cable','Está fijado permanentemente a la mesa','Necesita un lector CR para obtener la imagen','Solo puede utilizarse en mamografía'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué ventaja funcional aporta un casete inalámbrico respecto a un panel portátil conectado por cable?', ['Permite transmitir los datos de forma inalámbrica y puede utilizarse tanto en bucky como en disparo libre','Necesita obligatoriamente un lector CR','No necesita batería para funcionar','Solo puede utilizarse en el dispositivo mural'], 0, 'TEMA 8', 'medio'],
  ['¿Qué aplicaciones se señalan para los paneles planos?', ['Radiografía general, radiología vascular y mamografía con las adaptaciones correspondientes','Exclusivamente mamografía','Solo radiología dental y maxilofacial','Únicamente radioscopia'], 0, 'TEMA 8', 'fácil'],
  ['¿Por qué los sistemas de captura destinados a mamografía necesitan modificaciones específicas?', ['Para mejorar la resolución espacial y el contraste necesarios para obtener una imagen diagnóstica óptima','Para sustituir la matriz digital por una película convencional','Para eliminar la necesidad de compresión mamaria','Para reducir deliberadamente la resolución de la imagen'], 0, 'TEMA 8', 'medio'],
  ['¿Qué sistema se asocia principalmente al uso de intensificadores de imagen según el tema?', ['DDC','CR','DX de captura directa','DX de captura indirecta'], 0, 'TEMA 8', 'fácil'],
  ['¿Qué resolución espacial se indica para los sistemas DDC?', ['Entre 512 × 512 y 1024 × 1024 píxeles','Entre 64 × 64 y 128 × 128 píxeles','Entre 2048 × 2048 y 4096 × 4096 píxeles','Entre 16 × 16 y 32 × 32 píxeles'], 0, 'TEMA 8', 'medio'],
  ['¿Qué función desempeña el panel CCD en un sistema DDC?', ['Recibir la luz generada por el centelleador y generar una carga','Captar directamente los rayos X mediante selenio amorfo','Borrar la imagen mediante luz blanca','Almacenar la imagen en un soporte CR'], 0, 'TEMA 8', 'medio'],
  ['¿Qué componente del sistema DDC transforma la carga de las celdas en una magnitud digital?', ['El conversor analógico/digital','El centelleador','El panel CCD','El fotomultiplicador'], 0, 'TEMA 8', 'fácil'],
  ['¿Cuál de las siguientes situaciones corresponde a un uso de DDC indicado en el tema?', ['Un arco quirúrgico utilizado en radioscopia/radiografía','Una radiografía general realizada con un casete inalámbrico','Una mamografía digital para estudio completo de la mama','Un estudio CR con lectura mediante láser'], 0, 'TEMA 8', 'medio'],
  ['¿En qué contexto de mamografía se menciona el uso de DDC?', ['En localizaciones de zonas de biopsia','Como sistema exclusivo para todas las mamografías','Para sustituir siempre los sistemas CR','Únicamente para reconstrucciones tridimensionales'], 0, 'TEMA 8', 'medio'],
  ['¿Qué combinación incluye únicamente tecnologías citadas como principales en los sistemas adaptados para mamografía digital?', ['CR, DX, DX de captura directa, acoplamiento óptico y recuento de fotones','CR, ecografía Doppler, TAC y PET','DDC, resonancia magnética y gamma cámara','Película convencional, fluoroscopia y ecografía'], 0, 'TEMA 8', 'difícil'],
  ['Un equipo necesita obtener una imagen digital sin extraer un soporte de imagen del chasis para introducirlo en un lector. ¿Qué sistema encaja mejor con esta descripción?', ['DX','CR','DDC','Un sistema convencional de película'], 0, 'TEMA 8', 'medio'],
  ['En un detector directo, si la capa de selenio amorfo deja de realizar correctamente su función, ¿qué etapa de la adquisición se vería afectada de forma más inmediata?', ['La conversión inicial de los rayos X en carga eléctrica','La transmisión inalámbrica de los datos','El borrado del soporte mediante luz blanca','La lectura de un chasis CR'], 0, 'TEMA 8', 'difícil'],
  ['En un detector indirecto, si el centelleador no transforma adecuadamente los rayos X en luz, ¿qué consecuencia tendría?', ['Se comprometería la generación posterior de carga eléctrica por los fotodiodos','El fotomultiplicador aumentaría automáticamente la resolución','El soporte CR se borraría antes de la exposición','La matriz TFT convertiría directamente los rayos X en luz'], 0, 'TEMA 8', 'difícil'],
  ['¿Qué afirmación compara correctamente CR, DX y DDC?', ['CR requiere leer un soporte previamente expuesto; DX integra captura y lectura; DDC se basa en un sistema con centelleador, panel CCD y conversión A/D','CR y DX requieren siempre un lector externo; DDC utiliza únicamente selenio amorfo','DX necesita un soporte CR; CR utiliza un panel CCD; DDC utiliza únicamente película','Los tres sistemas utilizan exactamente el mismo proceso de captura'], 0, 'TEMA 8', 'difícil'],
  ['¿Cuál es la secuencia más coherente desde la exposición hasta la imagen diagnóstica en un sistema CR?', ['Exposición del soporte → lectura láser → recogida de luz → conversión A/D → procesado digital','Exposición → conversión directa en carga por selenio → centelleador → procesado','Exposición → revelado químico → fotomultiplicador → conversión A/D','Exposición → transmisión inalámbrica → borrado con luz blanca → lectura láser'], 0, 'TEMA 8', 'difícil']
];

// Sustituye únicamente la tarjeta del TEMA 8 que ya genera el sistema.
const topic8OriginalTopicMenu = topicMenu;
topicMenu = function(){
  topic8OriginalTopicMenu();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const buttons = [...cards.querySelectorAll('button.module-card')];
  const existing = buttons.find(btn => (btn.textContent || '').includes('TEMA 8'));
  if(existing){
    existing.onclick = () => session('TEMA 8', topic8Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 8</span><h3>${esc((topics[8]||{}).title||'TEMA 8')}</h3><p>${topic8Curated.length} preguntas disponibles</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 8', topic8Curated);
  cards.appendChild(button);
};
