// Banco curado del TEMA 15.
const topic15Curated = [
["¿Cuál es la finalidad principal de los contrastes utilizados en resonancia magnética?",["Reducir las diferencias entre los tejidos.","Incrementar las diferencias de señal entre los tejidos.","Eliminar la señal de los líquidos.","Sustituir las secuencias de resonancia magnética."],1,"TEMA 15","medio","Los contrastes en RM modifican las propiedades magnéticas de los tejidos y permiten aumentar las diferencias de señal entre ellos. Así pueden hacerse más visibles determinadas estructuras o lesiones."],
["¿Cuál de los siguientes es un ejemplo de contraste natural en resonancia magnética?",["El aire pulmonar.","El líquido amniótico.","El sulfato de bario.","El yodo intravenoso."],1,"TEMA 15","medio","Un contraste natural es una sustancia del propio organismo que proporciona un contraste útil sin necesidad de administrar un agente externo. El líquido amniótico es un ejemplo de contraste natural por su diferente comportamiento de señal respecto a los tejidos que lo rodean."],
["¿Qué líquido puede actuar como contraste natural en una colangiografía por resonancia magnética?",["La bilis.","El líquido sinovial exclusivamente.","El plasma sanguíneo.","El aire intestinal."],0,"TEMA 15","medio","La colangiografía por RM aprovecha la elevada señal de los líquidos en determinadas secuencias, por lo que la bilis permite visualizar de forma natural la vía biliar sin necesidad de administrar contraste intravenoso."],
["¿Cuál es el contraste químico más utilizado en resonancia magnética?",["El yodo unido a un quelante.","El gadolinio unido a un agente quelante.","El sulfato de bario.","El dióxido de carbono."],1,"TEMA 15","medio","El gadolinio es el ion paramagnético utilizado como base de numerosos contrastes de RM. Se administra unido a un agente quelante, que ayuda a mantenerlo estable y reduce la presencia de gadolinio libre."],
["¿En qué pueden diferenciarse las distintas marcas de contrastes de gadolinio?",["En su osmolaridad, viscosidad y estabilidad.","Únicamente en el color de la solución.","Solo en la vía de administración.","Exclusivamente en su temperatura de almacenamiento."],0,"TEMA 15","medio","Los distintos agentes de gadolinio pueden presentar diferencias en características físico-químicas como osmolaridad, viscosidad y estabilidad del complejo. No son simplemente productos diferentes por su color o temperatura de almacenamiento."],
["¿Cuál es una función fundamental del agente quelante unido al gadolinio?",["Aumentar la producción de gadolinio libre.","Favorecer la estabilidad del compuesto.","Impedir su administración intravenosa.","Eliminar completamente su efecto paramagnético."],1,"TEMA 15","medio","El quelante se une al gadolinio para formar un complejo más estable. Esta unión limita la liberación del ion gadolinio libre y permite utilizar sus propiedades paramagnéticas como contraste."],
["¿Qué tipo de quelante proporciona mayor estabilidad y menor tendencia a liberar gadolinio libre?",["El quelante cíclico o con estructura cónica.","Un quelante sin estructura definida.","Un quelante exclusivamente liposoluble.","Un quelante sin capacidad de unión al gadolinio."],0,"TEMA 15","medio","Los quelantes cíclicos presentan una estructura que envuelve de forma más estable al gadolinio y, en general, tienen menor tendencia a liberar gadolinio libre que los complejos menos estables."],
["¿Cuál es la vía de administración más frecuente de los contrastes en resonancia magnética?",["Oral.","Rectal.","Intravenosa.","Subcutánea."],2,"TEMA 15","medio","La vía intravenosa es la más habitual para los contrastes utilizados en RM, especialmente cuando se pretende estudiar vascularización, perfusión o realce de determinadas lesiones. Existen también contrastes y preparaciones administrados por otras vías según el estudio."],
["¿Qué efecto produce principalmente el gadolinio sobre los tiempos de relajación?",["Alarga T1 y T2.","Acorta T1 y puede acortar T2.","Elimina completamente T1.","No modifica los tiempos de relajación."],1,"TEMA 15","medio","El gadolinio es paramagnético y aumenta las velocidades de relajación. A concentraciones habituales de contraste destaca el acortamiento de T1, aunque también puede producir acortamiento de T2 cuando la concentración es suficientemente alta."],
["¿Qué efecto sobre la imagen produce el acortamiento de T1 por el gadolinio?",["Hipointensidad en T1.","Hiperintensidad en T1.","Ausencia de señal en T1.","Hiperintensidad exclusivamente en T2."],1,"TEMA 15","medio","Al acortarse el tiempo de relajación T1, los tejidos que captan gadolinio recuperan su magnetización longitudinal más rápidamente. En una secuencia potenciada en T1 esto se traduce habitualmente en un aumento de señal o hiperintensidad."],
["¿Qué efecto sobre la imagen puede producir el acortamiento de T2 por el gadolinio?",["Hipointensidad en T2.","Hiperintensidad en T2.","Ausencia de señal exclusivamente en T1.","Aumento de la señal de todos los tejidos."],0,"TEMA 15","medio","Cuando la concentración de gadolinio es suficientemente elevada, el acortamiento de T2 provoca una pérdida de señal. Por eso una concentración alta de contraste puede producir hipointensidad en imágenes potenciadas en T2."],
["¿Cómo se visualiza el contraste de gadolinio en una exploración de resonancia magnética?",["Como una sustancia visible directamente por sí misma.","A través de sus efectos sobre la señal de los tejidos.","Mediante radiación ionizante.","Por su densidad radiológica."],1,"TEMA 15","medio","El gadolinio no se observa directamente como si fuera una sustancia independiente. Se detecta por el efecto que produce sobre los tiempos de relajación y, en consecuencia, sobre la señal de los tejidos en la imagen de RM."],
["¿Qué tipo de secuencias se utilizan habitualmente para obtener imágenes posteriores a la administración de gadolinio?",["Secuencias potenciadas en T1.","Exclusivamente secuencias potenciadas en T2.","Solo secuencias de difusión.","Únicamente secuencias de densidad protónica."],0,"TEMA 15","medio","Las secuencias potenciadas en T1 son las más utilizadas después de administrar gadolinio porque el acortamiento de T1 produce un aumento de señal en las zonas que captan contraste, facilitando la valoración del realce."],
["¿Para qué sirve la imagen previa a la administración de contraste en un estudio dinámico?",["Para utilizarla como máscara en la sustracción posterior.","Para eliminar todas las imágenes posteriores.","Para sustituir las fases dinámicas.","Para calcular exclusivamente el tiempo de exploración."],0,"TEMA 15","medio","La imagen precontraste puede utilizarse como máscara para realizar una sustracción. Al restarla de las imágenes posteriores se eliminan o reducen las estructuras que permanecen sin cambios y se resalta el realce producido por el contraste."],
["¿Qué tipo de secuencia permite habitualmente obtener múltiples fases durante un estudio dinámico con contraste?",["Una secuencia Gradient Echo rápida.","Una secuencia exclusivamente de eco de espín lenta.","Una secuencia sin codificación espacial.","Una secuencia de radiografía convencional."],0,"TEMA 15","medio","Las secuencias Gradient Echo rápidas permiten adquirir imágenes en poco tiempo y repetir la adquisición después de la administración de contraste. Esto hace posible obtener distintas fases de un estudio dinámico."],
["¿Qué característica define a los contrastes intracelulares utilizados en el estudio hepático?",["Son captados por células hepáticas y pueden mejorar la caracterización de lesiones.","Permanecen exclusivamente en el espacio vascular.","No permiten estudiar el parénquima hepático.","Solo pueden administrarse por vía oral."],0,"TEMA 15","medio","Los contrastes hepatocitarios o intracelulares son captados por los hepatocitos. Esta captación permite obtener información adicional sobre las lesiones hepáticas y ayuda a diferenciar lesiones con y sin componente hepatocitario funcional."],
["¿Qué característica presentan los contrastes mixtos utilizados en resonancia magnética hepática?",["Combinan propiedades extracelulares e intracelulares.","Actúan únicamente como contraste oral.","No presentan fase tardía.","Solo permiten estudiar vasos sanguíneos."],0,"TEMA 15","medio","Los contrastes mixtos tienen inicialmente un comportamiento extracelular y, posteriormente, una parte de su efecto depende de la captación hepatocitaria. Por eso permiten valorar tanto fases dinámicas como información hepatobiliar tardía."],
["En las imágenes tardías hepáticas, ¿qué puede indicar la ausencia de captación del contraste intracelular?",["Ausencia de hepatocitos en la lesión.","Presencia obligatoria de hepatocitos normales.","Aumento de la función hepatocitaria.","Presencia de aire en la lesión."],0,"TEMA 15","medio","En la fase hepatobiliar, la captación del contraste depende de la presencia y funcionamiento de hepatocitos. Una lesión que no contiene hepatocitos funcionales puede quedar sin captación y verse más hipointensa respecto al parénquima hepático."],
["¿Qué característica diferencia a los contrastes intravasculares de los agentes extracelulares inespecíficos?",["Permanecen más tiempo en el espacio vascular.","Se eliminan exclusivamente por vía biliar.","No producen aumento de señal sanguínea.","No pueden utilizarse en estudios angiográficos."],0,"TEMA 15","medio","Los contrastes intravasculares están diseñados para permanecer en el compartimento vascular durante más tiempo que los agentes extracelulares convencionales. Esta característica puede ser útil para estudios angiográficos y de caracterización vascular."],
["¿Qué son los contrastes superparamagnéticos mencionados en el tema?",["Partículas de óxido de hierro, actualmente en desuso.","Microburbujas de gas para ecografía.","Quelatos de yodo para TC.","Suspensiones de sulfato de bario."],0,"TEMA 15","medio","Los contrastes superparamagnéticos mencionados en el tema son partículas basadas en óxido de hierro que producen efectos magnéticos intensos, especialmente sobre T2 y T2*. Estos agentes han tenido un uso limitado y actualmente están en desuso para muchas de sus antiguas indicaciones."]
];
window.topic15Curated = topic15Curated;

// El Tema 15 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank15 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank15().filter(q=>q[3]!=='TEMA 15'); };
