// Banco curado del TEMA 19. Radiología convencional: miembro superior.
const topic19Curated = [
["En una radiografía de hombro se pretende valorar la articulación glenohumeral y detectar posibles cambios óseos, osteofitos, fracturas o calcificaciones. ¿Qué proyección constituye una de las proyecciones básicas para este objetivo?",["West Point","AP","Fisk","Stryker"],1,"TEMA 19","fácil","La AP es una de las proyecciones básicas del hombro y permite valorar la articulación, estructuras óseas y posibles alteraciones."],
["Para complementar una proyección AP de hombro y valorar específicamente la alineación articular y la cavidad glenoidea, ¿qué proyección resulta especialmente adecuada?",["Axial","Outlet","Alexander","Rockwood"],0,"TEMA 19","medio","La axial complementa la AP y permite valorar mejor la relación entre la cabeza humeral y la cavidad glenoidea."],
["Durante el estudio de un hombro traumatizado se realiza una proyección lateral escapular. Esta proyección es especialmente útil para:",["Valorar exclusivamente la corredera bicipital","Detectar luxaciones de hombro y valorar el manguito rotador","Estudiar únicamente la articulación acromioclavicular","Visualizar el escafoides"],1,"TEMA 19","medio","La lateral escapular es especialmente útil para detectar luxaciones del hombro y valorar la relación de las estructuras escapulares."],
["¿Qué combinación relaciona correctamente una proyección del hombro con la lesión que permite valorar?",["West Point — lesión de Hill-Sachs","Outlet View — lesión de Bankart","West Point — lesión de Bankart","Grashey — lesión de Chauffeur"],2,"TEMA 19","medio","La West Point está diseñada para estudiar el borde anteroinferior de la glenoides, zona donde puede aparecer la lesión de Bankart."],
["Una lesión de Hill-Sachs afecta a:",["El borde anteroinferior de la glenoides","La cara posterolateral de la cabeza humeral","La apófisis coronoides del cúbito","La cabeza del radio"],1,"TEMA 19","fácil","La lesión de Hill-Sachs es una impactación de la cara posterolateral de la cabeza humeral, típica de una luxación anterior del hombro."],
["En una proyección AP de hombro con rotación externa, ¿qué estructura se visualiza específicamente?",["Troquín","Troquíter","Apófisis coracoides","Corredera bicipital"],1,"TEMA 19","fácil","Con la rotación externa, el troquíter queda mejor perfilado."],
["En una proyección AP de hombro con rotación interna, la estructura que se visualiza es:",["Troquíter","Troquín","Acromion","Glenoides"],1,"TEMA 19","fácil","La rotación interna coloca el troquín en una posición que permite visualizarlo mejor."],
["¿Qué asociación entre rotación y estructura es correcta?",["Rotación externa → troquín","Rotación interna → troquíter","Rotación externa → troquíter","Ambas rotaciones muestran el troquíter"],2,"TEMA 19","fácil","Regla fácil: rotación externa → troquíter; rotación interna → troquín."],
["Un paciente presenta un traumatismo de hombro y no puede movilizar el brazo. ¿Qué proyección puede utilizarse cuando existe imposibilidad para moverlo?",["Transtorácica de Lawrence","West Point","Grashey","Alexander"],0,"TEMA 19","medio","La transtóracica de Lawrence permite estudiar el hombro cuando el paciente no puede movilizar el brazo, utilizando el tórax como vía de proyección."],
["La proyección Grashey está diseñada específicamente para:",["Visualizar la corredera bicipital","Visualizar la articulación glenohumeral sin superposición de la cabeza humeral sobre la glenoides","Detectar exclusivamente lesiones de Hill-Sachs","Valorar la articulación acromioclavicular"],1,"TEMA 19","medio","La Grashey obtiene una visión más limpia de la articulación glenohumeral, evitando la superposición de la cabeza humeral sobre la glenoides."],
["¿Qué proyección está diseñada específicamente para visualizar el surco intertubercular o corredera bicipital?",["Rockwood","Fisk","Stryker","Velpeau"],1,"TEMA 19","fácil","La proyección de Fisk permite visualizar específicamente la corredera bicipital o surco intertubercular."],
["La proyección Rockwood está especialmente indicada para valorar:",["El acromion","El escafoides","La cabeza del radio","La articulación radiocubital distal"],0,"TEMA 19","fácil","Rockwood se utiliza especialmente para valorar el acromion y el espacio subacromial."],
["¿Qué proyección del hombro se utiliza específicamente para detectar lesiones óseas de la cara posterolateral de la cabeza humeral, como la lesión de Hill-Sachs?",["Alexander","Stryker","Fisk","Grashey"],1,"TEMA 19","medio","Stryker está indicada para buscar defectos óseos en la cara posterolateral de la cabeza humeral, especialmente una lesión de Hill-Sachs."],
["Un paciente traumatizado no puede realizar la abducción necesaria para una proyección axial convencional. ¿Cuál de las siguientes técnicas está específicamente diseñada para pacientes que no pueden abducir el brazo?",["Velpeau","Alexander","Fisk","West Point"],0,"TEMA 19","medio","Velpeau es una alternativa cuando el paciente no puede realizar la abducción necesaria para una axial convencional."],
["En el estudio radiográfico de la articulación acromioclavicular mediante la proyección AP axial de Alexander, el rayo central se angula aproximadamente:",["5º caudal","10º cefálico","15º cefálico","30º caudal"],2,"TEMA 19","medio","En la AP axial de Alexander, el rayo central se dirige aproximadamente 15º cefálico."],
["En una sospecha de subluxación o luxación acromioclavicular, Alexander recomienda realizar:",["Solo una AP","AP y lateral","Solo una axial","AP y oblicua de mano"],1,"TEMA 19","medio","Ante sospecha de luxación o subluxación acromioclavicular, se realizan AP y lateral para valorar correctamente la articulación."],
["Para realizar correctamente una proyección AP de antebrazo, la posición descrita en el material es:",["Codo flexionado 90º y mano en pronación","Mano en supinación y codo extendido","Mano en pronación y codo flexionado","Codo en máxima flexión y mano en supinación"],1,"TEMA 19","fácil","Para la AP de antebrazo, la posición indicada es mano en supinación y codo extendido."],
["En una radiografía AP de antebrazo correctamente realizada, ¿qué debe incluirse?",["Únicamente el radio","Únicamente el cúbito","Desde la muñeca hasta la porción distal del húmero","Desde la mano hasta la cabeza humeral"],2,"TEMA 19","medio","El estudio debe abarcar el antebrazo completo y las articulaciones de ambos extremos, desde la muñeca hasta la porción distal del húmero."],
["Para realizar una proyección lateral de antebrazo, el codo debe colocarse:",["En extensión completa","A 45º","A 90º","En máxima flexión"],2,"TEMA 19","fácil","En la lateral de antebrazo, la flexión del codo a 90º permite conseguir la posición lateral adecuada."],
["En la proyección lateral de antebrazo, ¿cuál de los siguientes criterios corresponde a una imagen correctamente posicionada?",["Epicóndilos humerales separados","Epicóndilos humerales superpuestos","Radio y cúbito completamente separados distalmente","Tuberosidad radial orientada posteriormente"],1,"TEMA 19","medio","Los epicóndilos humerales deben quedar superpuestos, uno de los criterios fundamentales de una lateral correctamente posicionada."],
["En una proyección AP de codo, la posición correcta requiere:",["Codo flexionado 90º","Codo totalmente extendido","Codo flexionado 45º","Antebrazo perpendicular al chasis"],1,"TEMA 19","fácil","La AP de codo se realiza con el codo totalmente extendido para obtener correctamente la articulación."],
["Durante una proyección lateral de codo, ¿qué estructura debe visualizarse de perfil?",["Cabeza humeral","Olécranon y cúbito","Clavícula","Troquíter"],1,"TEMA 19","fácil","En la lateral, el olécranon y el cúbito deben quedar claramente perfilados para valorar la articulación del codo."],
["Un paciente presenta sospecha de fractura de la cabeza del radio. ¿Qué proyección especial del codo puede proporcionar una mejor visualización de esta estructura?",["AP con rotación interna","AP con rotación externa","AP de antebrazo","Lateral de húmero"],1,"TEMA 19","medio","La AP con rotación externa permite visualizar mejor la cabeza y el cuello del radio, especialmente útil ante sospecha de fractura."],
["En la proyección AP de codo con rotación interna, se visualiza mejor:",["La cabeza y cuello del radio","La apófisis coronoides del cúbito y la tróclea de perfil","El troquíter","La corredera bicipital"],1,"TEMA 19","medio","La rotación interna permite estudiar mejor la apófisis coronoides y la tróclea de perfil."],
["¿Qué proyección del codo está diseñada para estudiar tanto el húmero distal como la región proximal del radio y cúbito cuando existe una flexión aguda?",["Condilorradial","Flexión aguda de codo","Alexander","Schneck"],1,"TEMA 19","medio","La técnica de flexión aguda de codo está indicada cuando existe una flexión importante que impide realizar las proyecciones convencionales."],
["La proyección condilorradial permite:",["Desenfilar la cabeza del radio respecto a la apófisis coronoides y al cóndilo de la tróclea humeral","Visualizar exclusivamente el olécranon","Estudiar la articulación acromioclavicular","Visualizar el escafoides"],0,"TEMA 19","difícil","La condilorradial tiene como objetivo desenfilar la cabeza del radio respecto a la apófisis coronoides y al cóndilo de la tróclea humeral."],
["Un paciente presenta una fractura de antebrazo. En la radiografía se observa una fractura del cúbito asociada a una luxación de la cabeza del radio. ¿Qué lesión corresponde?",["Galeazzi","Monteggia","Colles","Smith"],1,"TEMA 19","medio","Monteggia = fractura de cúbito asociada a luxación de la cabeza del radio."],
["¿Qué combinación es correcta respecto a las luxofracturas del antebrazo?",["Monteggia → radio + luxación distal","Galeazzi → cúbito + luxación radial","Monteggia → cúbito + luxación radial","Galeazzi → húmero + luxación del codo"],2,"TEMA 19","medio","Monteggia se asocia a fractura de cúbito y luxación de la cabeza radial; Galeazzi se asocia a fractura distal del radio con lesión de la articulación radiocubital distal."],
["Un paciente sufre una caída apoyando la mano extendida y presenta una fractura distal del radio típica. ¿Qué lesión debe considerarse especialmente?",["Smith","Colles","Monteggia","Hill-Sachs"],1,"TEMA 19","fácil","La fractura de Colles es la fractura distal del radio típica tras una caída sobre la mano extendida."],
["¿Qué proyección se utiliza específicamente para obtener una visión frontal del escafoides?",["Muñeca lateral","Muñeca PA","Muñeca de Schneck","Mano oblicua"],2,"TEMA 19","medio","La proyección de Schneck es específica para obtener una mejor visualización frontal del escafoides."],
["En el estudio radiográfico de la mano, la proyección oblicua tiene como finalidad principal:",["Sustituir a la proyección PA","Complementar la PA evitando determinadas superposiciones","Visualizar exclusivamente el radio","Estudiar únicamente la articulación del codo"],1,"TEMA 19","fácil","La oblicua complementa la PA y aporta información adicional al reducir determinadas superposiciones entre estructuras."],
["Ante un estudio radiográfico del húmero, una proyección AP correctamente realizada debe permitir visualizar:",["Solo la cabeza humeral","Solo el tercio distal","El húmero completo, incluyendo las articulaciones del hombro y del codo","Únicamente la diáfisis"],2,"TEMA 19","fácil","La AP debe abarcar todo el húmero e incluir las articulaciones del hombro y del codo para que el estudio sea completo."],
["En la proyección lateral de húmero descrita en el material, la mano del paciente se coloca:",["Sobre la cabeza","Sobre el abdomen","Detrás de la espalda","Sobre el hombro contrario"],1,"TEMA 19","fácil","En la lateral de húmero descrita, la mano se coloca sobre el abdomen para facilitar la posición lateral."],
["¿Qué lesión está relacionada con una luxación de hombro y una fractura de la cabeza humeral?",["Lesión de Bankart","Lesión de Hill-Sachs","Fractura de Chauffeur","Fractura de Smith"],1,"TEMA 19","medio","Hill-Sachs es la lesión ósea de la cabeza humeral asociada a una luxación de hombro; Bankart afecta al reborde glenoideo."],
["Un paciente presenta dolor de muñeca y sospecha de una fractura de escafoides que no resulta evidente en la proyección PA convencional. ¿Qué proyección específica debe considerarse?",["Schneck","Alexander","Fisk","Outlet"],0,"TEMA 19","medio","Si la sospecha de fractura de escafoides no se aprecia bien en la PA convencional, se recurre a la proyección específica de Schneck."]
];
window.topic19Curated = topic19Curated;

// El Tema 19 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank19 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank19().filter(q=>q[3]!=='TEMA 19'); };
