// Test curado del TEMA 40 · EXPLORACIÓN ECOGRÁFICA DEL APARATO GENITAL FEMENINO
const topic40Curated = [
  ["¿Cuál de las siguientes afirmaciones sobre la ecografía de la pelvis femenina es correcta?", ["Utiliza radiación ionizante y requiere contraste intravenoso.", "Es una técnica invasiva cuya principal utilidad es el estudio ovárico.", "Es una modalidad ampliamente disponible, no utiliza radiación y proporciona información diagnóstica útil.", "Su principal limitación es que no permite obtener imágenes en tiempo real."], 2, "TEMA 40", "fácil", "La ecografía pélvica es una técnica ampliamente disponible, no invasiva y sin radiación ionizante. Además, permite obtener imágenes en tiempo real, por lo que resulta especialmente útil para valorar el útero, los ovarios y otras estructuras pélvicas."],
  ["En una mujer en edad fértil, el tamaño aproximado habitual de los ovarios es:", ["1 × 1 × 1 cm", "2 × 1 × 1 cm", "3 × 2 × 2 cm", "5 × 4 × 3 cm"], 2, "TEMA 40", "fácil", "En la edad fértil, el tamaño aproximado descrito para los ovarios es de 3 × 2 × 2 cm. Es una referencia orientativa, ya que el tamaño ovárico puede variar con la edad y con la situación hormonal."],
  ["Una paciente presenta un ovario difícil de localizar por su posición. ¿Cuál es la referencia anatómica más útil para su localización ecográfica?", ["El borde externo de los músculos iliopsoas.", "El borde interno de los vasos ilíacos.", "El fondo vesical.", "El borde externo del recto."], 1, "TEMA 40", "difícil", "El borde interno de los vasos ilíacos es una referencia anatómica especialmente útil para localizar los ovarios. Aunque suelen encontrarse medialmente respecto a estos vasos, pueden cambiar de posición y localizarse en lugares como el fondo de saco de Douglas o en posiciones suprauterinas."],
  ["¿Cuál es la secuencia correcta de desarrollo folicular?", ["Primordial → secundario → primario → De Graaf.", "Primario → primordial → secundario → De Graaf.", "Primordial → primario → secundario → maduro o de De Graaf.", "Primordial → De Graaf → primario → secundario."], 2, "TEMA 40", "medio", "El desarrollo folicular sigue la secuencia primordial → primario → secundario → maduro o de De Graaf. El folículo primordial es la etapa inicial y, mediante sucesivas fases de desarrollo, alcanza la madurez."],
  ["¿Cuál de los siguientes segmentos de la trompa de Falopio corresponde a la porción central y más larga?", ["Intersticial.", "Ístmico.", "Ampular.", "Infundibular."], 2, "TEMA 40", "medio", "La porción ampular es la parte central y más larga de la trompa de Falopio. La trompa se divide en porciones intersticial, ístmica, ampular, infundibular y fímbrica, desde su origen uterino hasta el extremo distal."],
  ["Respecto a la zona fímbrica de la trompa de Falopio, señale la afirmación correcta:", ["Es el segmento muscular más estrecho próximo al útero.", "Corresponde al extremo distal del infundíbulo y presenta prolongaciones que rodean parte del ovario.", "Atraviesa el músculo uterino antes de alcanzar la cavidad endometrial.", "Es la zona donde se produce exclusivamente la implantación."], 1, "TEMA 40", "medio", "Las fimbrias son prolongaciones del extremo distal del infundíbulo que rodean parcialmente el ovario y facilitan la captación del ovocito tras la ovulación. La porción estrecha próxima al útero es el istmo, no la zona fímbrica."],
  ["¿Cuál de las siguientes NO corresponde a una de las cuatro partes descritas del útero?", ["Fondo.", "Cuerpo.", "Istmo.", "Ligamento ancho."], 3, "TEMA 40", "fácil", "El ligamento ancho no es una parte anatómica del útero. En la división descrita en el tema se consideran fondo, cuerpo, istmo y cuello uterino; el ligamento ancho es una estructura peritoneal relacionada con el útero y sus anexos."],
  ["¿Qué capa uterina es la más externa y forma lateralmente los ligamentos anchos?", ["Endometrio.", "Miometrio.", "Perimetrio.", "Estrato basal."], 2, "TEMA 40", "medio", "El perimetrio es la cubierta externa del útero. El miometrio es la capa muscular y el endometrio reviste internamente la cavidad uterina. El estrato basal forma parte del endometrio, por lo que tampoco puede ser la capa externa."],
  ["Durante la menstruación, ¿qué parte del endometrio se descama?", ["Exclusivamente el estrato basal.", "La capa funcional formada por los estratos compacto y esponjoso.", "Todo el miometrio.", "Únicamente el estrato compacto."], 1, "TEMA 40", "medio", "Durante la menstruación se descama la capa funcional del endometrio, formada por los estratos compacto y esponjoso. El estrato basal permanece y permite regenerar el endometrio durante el siguiente ciclo."],
  ["¿Cuál de las siguientes asociaciones entre fase del ciclo y aspecto ecográfico endometrial es correcta?", ["Semana 1 → aumento máximo del espesor endometrial.", "Semana 2 → banda hipoecogénica alrededor de la línea cavitaria.", "Semanas 3–4 → desaparición completa de la línea cavitaria.", "Fase menstrual → banda hiperecogénica rodeada de halo hipoecogénico."], 1, "TEMA 40", "difícil", "Según el esquema descrito en el tema, durante la segunda semana aparece una banda hipoecogénica alrededor de la línea cavitaria. El aspecto endometrial cambia a lo largo del ciclo, por lo que conocer la fase menstrual es importante para interpretar correctamente la imagen."],
  ["Durante las semanas 3–4 del ciclo, en la fase secretora:", ["Disminuye el espesor endometrial y desaparece la línea cavitaria.", "Aumenta el espesor endometrial y la línea cavitaria queda rodeada por una banda hiperecogénica y un halo hipoecogénico.", "El endometrio apenas es visible.", "Aparece exclusivamente una banda hipoecogénica."], 1, "TEMA 40", "difícil", "En la fase secretora aumenta el espesor del endometrio y la línea cavitaria queda rodeada por una banda hiperecogénica y un halo hipoecogénico. Estos cambios son fisiológicos y están relacionados con la preparación del endometrio para una posible implantación."],
  ["¿Cuál de las siguientes NO constituye una indicación de la ecografía pélvica?", ["Sangrado posmenopáusico.", "Localización de dispositivos intrauterinos.", "Incontinencia o prolapso.", "Necesidad de utilizar radiación ionizante para valorar la pelvis."], 3, "TEMA 40", "fácil", "La ecografía no necesita radiación ionizante. Sí está indicada, entre otras situaciones, ante sangrado posmenopáusico, para localizar dispositivos intrauterinos y para valorar incontinencia o prolapso. Por tanto, la necesidad de utilizar radiación ionizante no es una indicación ecográfica."],
  ["Antes de iniciar una exploración ecográfica ginecológica, la anamnesis es especialmente importante porque:", ["Permite prescindir de la exploración ecográfica.", "Tiene valor orientativo y es indispensable para interpretar correctamente las imágenes.", "Solo es necesaria en pacientes posmenopáusicas.", "Sustituye al estudio Doppler."], 1, "TEMA 40", "medio", "La anamnesis aporta información clínica imprescindible para orientar e interpretar correctamente la exploración. Datos como el motivo de consulta, fase del ciclo, gestaciones, cirugías previas, anticoncepción o características del dolor pueden modificar la interpretación de los hallazgos."],
  ["Para la ecografía transabdominal de la pelvis femenina, la preparación vesical adecuada consiste en:", ["Vejiga completamente vacía.", "Buena repleción vesical.", "Vejiga vacía salvo en mujeres posmenopáusicas.", "Repleción exclusivamente mediante contraste ecográfico."], 1, "TEMA 40", "fácil", "La ecografía transabdominal requiere una buena repleción vesical. La vejiga llena proporciona una ventana acústica adecuada y desplaza las asas intestinales, facilitando la visualización de las estructuras pélvicas."],
  ["En la exploración transabdominal, la vejiga llena resulta especialmente útil porque:", ["Impide visualizar el útero.", "Actúa como ventana acústica para el estudio pélvico.", "Elimina las asas intestinales de forma permanente.", "Permite visualizar directamente las trompas normales."], 1, "TEMA 40", "medio", "La vejiga llena actúa como una ventana acústica porque su contenido líquido permite una buena transmisión del ultrasonido y facilita la visualización de las estructuras pélvicas posteriores. No hace que las trompas normales sean directamente visibles: estas generalmente no se identifican si no están dilatadas."],
  ["En una ecografía transabdominal, ¿cuál es la secuencia inicial de exploración descrita?", ["Plano axial sobre el ovario derecho y posteriormente plano sagital.", "Plano sagital sobre el eje uterovaginal y posteriormente barrido transversal para localizar los anejos.", "Plano coronal sobre la vejiga seguido de Doppler.", "Plano transversal sobre el cuello uterino seguido de exploración rectal."], 1, "TEMA 40", "medio", "La exploración comienza en plano sagital sobre el eje uterovaginal y después se realiza un barrido transversal para localizar los anejos. Esta sistemática permite estudiar primero el útero y después recorrer ambos lados de la pelvis de forma ordenada."],
  ["En la ecografía transvaginal, la preparación vesical recomendada es:", ["Vejiga muy llena para crear una ventana acústica.", "Vejiga vacía o con poca cantidad de orina.", "Llenado vesical mediante sondaje.", "No existe ninguna recomendación respecto a la vejiga."], 1, "TEMA 40", "fácil", "En la vía transvaginal se recomienda una vejiga vacía o con poca cantidad de orina. A diferencia de la vía transabdominal, no se necesita la vejiga como ventana acústica porque la sonda está muy próxima a los órganos ginecológicos."],
  ["¿Cuál de las siguientes características corresponde a la sonda utilizada en la ecografía transvaginal?", ["Sonda convexa de baja frecuencia exclusivamente.", "Sonda endocavitaria de alta frecuencia con extremo convexo y ángulo variable.", "Sonda sectorial de alta frecuencia exclusivamente.", "Sonda lineal superficial de 3–5 MHz."], 1, "TEMA 40", "medio", "La exploración transvaginal utiliza una sonda endocavitaria de alta frecuencia, con extremo convexo y ángulo variable. Su diseño permite aproximarse a las estructuras pélvicas y obtener una elevada resolución."],
  ["Durante la ecografía transvaginal, en el plano sagital:", ["El fondo uterino aparece a la derecha y el cuello a la izquierda de la pantalla.", "El fondo uterino aparece a la izquierda y el cuello a la derecha.", "Ambos aparecen siempre en el centro de la pantalla.", "El cuello uterino no puede identificarse."], 1, "TEMA 40", "medio", "En la orientación descrita para el plano sagital transvaginal, el fondo uterino aparece a la izquierda y el cuello uterino a la derecha de la pantalla. Conocer esta orientación evita errores al interpretar las imágenes y localizar las estructuras."],
  ["En el plano axial de una ecografía transvaginal, debido a la orientación de la imagen:", ["El ovario derecho aparece en el sector derecho de la pantalla.", "El ovario izquierdo aparece siempre en el sector derecho.", "El ovario derecho puede verse en el sector izquierdo de la pantalla y viceversa.", "La lateralidad ovárica no puede determinarse."], 2, "TEMA 40", "difícil", "En el plano axial la orientación de la imagen hace que la lateralidad pueda parecer invertida respecto a la pantalla: el ovario derecho puede verse en el sector izquierdo y el izquierdo en el derecho. Por eso hay que interpretar la orientación anatómica y no asumir que derecha de pantalla equivale a derecha del paciente."],
  ["La sonohisterografía consiste en:", ["Estudiar exclusivamente las trompas mediante contraste yodado.", "Estudiar la cavidad uterina mediante ecografía transvaginal mientras se introduce suero salino mediante un catéter balón.", "Estudiar los ovarios después de llenar la vejiga.", "Valorar el útero mediante radiología convencional."], 1, "TEMA 40", "medio", "La sonohisterografía combina la ecografía transvaginal con la introducción de suero salino en la cavidad uterina mediante un catéter con balón. El líquido distiende la cavidad y mejora la visualización de sus alteraciones internas."],
  ["Una de las principales utilidades de la sonohisterografía es:", ["Diferenciar un quiste folicular de un endometrioma.", "Diferenciar miomas submucosos de pólipos pediculados.", "Diagnosticar exclusivamente la torsión ovárica.", "Valorar el flujo de las arterias uterinas."], 1, "TEMA 40", "medio", "Al distender la cavidad uterina con suero, la sonohisterografía delimita mejor las lesiones intracavitarias y ayuda a diferenciar miomas submucosos de pólipos pediculados. No es una técnica destinada exclusivamente al estudio ovárico ni al Doppler de las arterias uterinas."],
  ["¿Cuál de las siguientes situaciones constituye una contraindicación de la sonohisterografía?", ["Infertilidad.", "Sangrado vaginal.", "Posibilidad de embarazo.", "Sospecha de adherencias."], 2, "TEMA 40", "medio", "La posibilidad de embarazo es una contraindicación porque la técnica implica introducir un catéter y líquido dentro de la cavidad uterina. En cambio, el sangrado vaginal, la infertilidad y la sospecha de adherencias pueden constituir indicaciones según el contexto clínico."],
  ["Durante una sonohisterografía, una vez colocado el catéter en la cavidad endometrial:", ["Se infla el balón con aproximadamente 2 mL de suero salino y posteriormente se administra lentamente el suero.", "Se infla el balón con 20 mL de contraste yodado.", "Se introduce inmediatamente aire a presión.", "Se vacía completamente la cavidad uterina antes de introducir la sonda."], 0, "TEMA 40", "difícil", "Una vez colocado el catéter, el balón se infla con aproximadamente 2 mL de suero salino y después se administra el suero lentamente para distender la cavidad. La administración progresiva ayuda a evitar turbulencias y artefactos que dificulten la valoración del endometrio."],
  ["La sonohisterosalpingografía se diferencia de la sonohisterografía fundamentalmente porque:", ["Utiliza radiación ionizante.", "Utiliza contraste ecográfico para valorar la permeabilidad tubárica.", "Se realiza exclusivamente por vía transrectal.", "No permite estudiar las trompas."], 1, "TEMA 40", "medio", "La sonohisterosalpingografía utiliza contraste ecográfico para valorar la permeabilidad de las trompas. Permite seguir el paso del contraste por el lumen tubárico y comprobar su salida hacia la cavidad peritoneal, sin utilizar radiación ionizante."],
  ["¿Cuándo puede resultar especialmente útil la ecografía transrectal en la pelvis femenina?", ["Como primera elección obligatoria en todas las pacientes.", "En mujeres vírgenes o cuando la vía vaginal no es posible, y como guía para determinados procedimientos intervencionistas.", "Únicamente para estudiar el endometrio durante la menstruación.", "Solo cuando la vejiga está completamente llena."], 1, "TEMA 40", "medio", "La vía transrectal puede ser útil en mujeres vírgenes o cuando la vía vaginal no es posible por estrechez o dolor. También puede emplearse como guía para determinados procedimientos intervencionistas, por lo que no es una vía obligatoria de primera elección para todas las pacientes."],
  ["Respecto a la posición uterina, señale la afirmación correcta:", ["La retroversión siempre indica patología.", "La lateroversión siempre indica una masa pélvica.", "La anteversión es frecuente y la retroversión o lateroversión pueden ser variantes no patológicas.", "La posición uterina es independiente de la repleción vesical y rectal."], 2, "TEMA 40", "medio", "La anteversión es una posición frecuente, mientras que la retroversión y la lateroversión también pueden ser variantes anatómicas no patológicas. La posición uterina puede verse influida por la repleción vesical o rectal, la presión intraabdominal y la laxitud ligamentosa."],
  ["La línea endometrial normal se describe como:", ["Una banda gruesa hiperecogénica que siempre corresponde a tejido sólido.", "Un fino trazo ecogénico central que representa la interfase entre las dos capas endometriales adheridas.", "Una estructura anecoica permanente que representa la cavidad uterina llena de líquido.", "Una estructura exclusivamente visible mediante Doppler."], 1, "TEMA 40", "medio", "La línea endometrial es un fino trazo ecogénico central que representa la interfase entre las dos capas endometriales adheridas. No equivale a una cavidad llena de líquido ni es una estructura que dependa del Doppler."],
  ["Respecto a los ovarios normales, señale la opción correcta:", ["Son siempre homogéneamente anecoicos.", "La corteza periférica puede ser menos ecogénica y la médula central más ecogénica.", "La médula es siempre menos ecogénica que la corteza.", "Los folículos periféricos son necesariamente lesiones patológicas."], 1, "TEMA 40", "medio", "En el ovario normal, la corteza periférica puede ser menos ecogénica y la médula central más ecogénica. Los folículos se desarrollan en la corteza y pueden verse como pequeñas estructuras quísticas; su presencia no significa por sí misma patología."],
  ["Una mujer en la mitad de su ciclo presenta pequeños quistes foliculares periféricos de aproximadamente 2–2,5 cm. ¿Cuál es la interpretación más adecuada?", ["Son necesariamente quistes ováricos patológicos.", "Son compatibles con cambios foliculares que pueden considerarse fisiológicos.", "Son diagnósticos de ovario poliquístico.", "Son característicos de un cistoadenocarcinoma."], 1, "TEMA 40", "medio", "Durante la mitad del ciclo pueden observarse folículos que alcanzan aproximadamente 2–2,5 cm y que representan cambios fisiológicos. Un folículo de este tamaño no debe confundirse automáticamente con un quiste patológico ni con ovarios poliquísticos."],
  ["¿Cuál de las siguientes características orienta hacia un quiste folicular?", ["Lesión anecogénica periférica, de paredes lisas y generalmente menor de 3 cm.", "Lesión sólida con vascularización interna.", "Lesión compleja con nódulos murales vascularizados.", "Lesión bilateral con puentes hiperecogénicos centrales."], 0, "TEMA 40", "fácil", "El quiste folicular suele ser anecogénico, periférico, de paredes lisas y generalmente menor de 3 cm. Se trata de una lesión funcional que puede desaparecer espontáneamente durante el ciclo siguiente. Los nódulos murales vascularizados o una lesión sólida obligan a pensar en otras entidades."],
  ["Una paciente presenta una lesión ovárica dolorosa a mitad de ciclo, con patrón interno reticular y sin flujo interno. Si se rompe, puede producir hemoperitoneo. ¿Cuál es la lesión más probable?", ["Quiste paraovárico.", "Quiste hemorrágico.", "Cistoadenoma seroso.", "Quiste folicular simple."], 1, "TEMA 40", "difícil", "El dolor a mitad de ciclo, el patrón interno reticular y la ausencia de flujo interno son características típicas de un quiste hemorrágico. La sangre puede darle una apariencia compleja o incluso seudósólida. Si se rompe, puede producir hemoperitoneo."],
  ["¿Cuál de las siguientes características favorece el diagnóstico de ovarios poliquísticos?", ["Un único quiste ovárico que desaparece tras dos ciclos.", "Múltiples microquistes periféricos, aumento del volumen ovárico y puentes hiperecogénicos centrales.", "Una lesión parauterina independiente del ovario.", "Una lesión quística con nódulos murales vascularizados."], 1, "TEMA 40", "difícil", "El patrón descrito en el tema incluye múltiples microquistes periféricos, aumento del volumen ovárico y puentes estromales hiperecogénicos centrales. Esto debe diferenciarse de un quiste funcional único, que puede desaparecer con el ciclo."],
  ["Una lesión quística parauterina se encuentra próxima a un ovario normal, localizada en el seno del ligamento ancho y sin dependencia del ovario ni del útero. ¿Cuál es el diagnóstico más compatible?", ["Quiste folicular.", "Endometrioma.", "Quiste paraovárico.", "Cistoadenocarcinoma mucinoso."], 2, "TEMA 40", "medio", "El dato clave es que la lesión está próxima a un ovario normal pero no depende de él ni del útero. Esa localización, habitualmente relacionada con el ligamento ancho, es característica de un quiste paraovárico."],
  ["Una paciente joven presenta una masa ovárica compleja con componentes hiperecogénicos que producen sombra acústica y atenuación del sonido. La lesión contiene tejidos derivados de diferentes capas embrionarias y su principal complicación es la torsión. ¿Cuál es el diagnóstico más probable?", ["Endometrioma.", "Quiste hemorrágico.", "Teratoma maduro o quiste dermoide.", "Cistoadenoma seroso."], 2, "TEMA 40", "difícil", "El teratoma maduro o quiste dermoide puede contener tejidos derivados de distintas capas embrionarias y producir componentes hiperecogénicos, sombra acústica y atenuación. Es especialmente frecuente en pacientes jóvenes y una de sus complicaciones principales es la torsión ovárica."]
];

window.topic40Curated = topic40Curated;

const previousTopicMenu40 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu40();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 40'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 40</span><h3>${esc((topics[40]||{}).title||'TEMA 40')}</h3><p>${topic40Curated.length} preguntas · genital femenino</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 40', topic40Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 40</span><h3>${esc((topics[40]||{}).title||'TEMA 40')}</h3><p>${topic40Curated.length} preguntas · genital femenino</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 40', topic40Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 40; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
