// Banco curado del TEMA 3 · tubo de rayos X.
const topic3Curated = [
['¿Qué componente del tubo de rayos X es responsable de la emisión termoiónica?',['El filamento del cátodo','El blanco del ánodo','La coraza protectora','La ventana de salida'],0,'TEMA 3','fácil'],
['¿Cuál es la función principal de la copa de enfoque del cátodo?',['Concentrar los electrones hacia el punto focal','Aumentar la tensión del tubo','Absorber la radiación de fuga','Refrigerar el ánodo'],0,'TEMA 3','fácil'],
['¿Qué material se utiliza habitualmente en el filamento del tubo de rayos X por su elevado punto de fusión?',['Tungsteno','Cobre','Plomo','Aluminio'],0,'TEMA 3','fácil'],
['¿Qué función desempeña principalmente el ánodo en el tubo de rayos X?',['Recibir los electrones y convertir parte de su energía en rayos X','Emitir electrones por efecto termoiónico','Colimar el haz de radiación','Proteger al paciente de la radiación dispersa'],0,'TEMA 3','fácil'],
['¿Por qué se utiliza tungsteno como material del blanco del ánodo?',['Por su alto número atómico y elevado punto de fusión','Por su bajo número atómico y bajo punto de fusión','Porque es un material ferromagnético','Porque es completamente transparente a los rayos X'],0,'TEMA 3','medio'],
['¿Qué porcentaje aproximado de la energía cinética de los electrones se transforma en rayos X en un tubo convencional?',['Alrededor del 1 %','Alrededor del 25 %','Alrededor del 50 %','Alrededor del 90 %'],0,'TEMA 3','medio'],
['¿En qué se transforma principalmente la energía restante de los electrones al impactar sobre el ánodo?',['En calor','En radiación gamma','En ultrasonidos','En luz visible'],0,'TEMA 3','fácil'],
['¿Qué ventaja principal aporta un ánodo giratorio frente a uno fijo?',['Permite repartir el calor sobre una superficie mayor del blanco','Elimina completamente la radiación de frenado','Evita la emisión termoiónica','Reduce a cero la producción de calor'],0,'TEMA 3','medio'],
['¿Qué se entiende por punto focal real?',['La zona física del blanco sobre la que impactan los electrones','El tamaño aparente del foco desde el paciente','La zona de salida del haz útil','La superficie externa de la coraza'],0,'TEMA 3','medio'],
['¿Qué principio permite obtener un punto focal efectivo menor que el punto focal real?',['Principio del foco lineal','Ley del inverso del cuadrado','Efecto fotoeléctrico','Principio de exclusión de Pauli'],0,'TEMA 3','medio'],
['¿Qué relación existe entre el tamaño del punto focal efectivo y el ángulo del ánodo?',['Al disminuir el ángulo del ánodo, disminuye el tamaño del foco efectivo','Al disminuir el ángulo del ánodo, aumenta siempre el tamaño del foco efectivo','El ángulo del ánodo no influye','El foco efectivo desaparece'],0,'TEMA 3','difícil'],
['¿Qué efecto del ánodo hace que la intensidad del haz sea mayor en el lado del cátodo que en el lado del ánodo?',['Efecto talón del ánodo','Efecto Compton','Efecto fotoeléctrico','Efecto Doppler'],0,'TEMA 3','fácil'],
['¿Cómo debe orientarse habitualmente el paciente cuando se quiere aprovechar el efecto talón para una parte anatómica de mayor espesor?',['La parte más gruesa hacia el lado del cátodo','La parte más gruesa hacia el lado del ánodo','La parte más gruesa siempre hacia el centro','La orientación es indiferente'],0,'TEMA 3','medio'],
['¿Qué parámetro controla principalmente la energía o poder de penetración del haz de rayos X?',['La tensión del tubo (kV)','La corriente del tubo (mA)','El tiempo de exposición','La distancia foco-película'],0,'TEMA 3','fácil'],
['¿Qué parámetro determina principalmente la cantidad de radiación X producida?',['El producto mAs','El kV exclusivamente','La distancia foco-detector','El tamaño del campo exclusivamente'],0,'TEMA 3','fácil'],
['Si se duplica el mAs manteniendo constantes los demás factores, ¿qué ocurre aproximadamente con la cantidad de radiación producida?',['Se duplica','Se reduce a la mitad','Se cuadruplica','No cambia'],0,'TEMA 3','fácil'],
['¿Qué ocurre generalmente al aumentar el kV manteniendo constantes los demás factores?',['Aumenta la energía y la penetración del haz','Disminuye la energía del haz','Disminuye siempre la cantidad de fotones a la mitad','No cambia el espectro de rayos X'],0,'TEMA 3','medio'],
['¿Cuál es la función de la coraza del tubo de rayos X?',['Proporcionar protección radiológica y aislamiento eléctrico, además de facilitar la refrigeración','Generar electrones por efecto termoiónico','Aumentar directamente el kV','Colimar el haz dentro del paciente'],0,'TEMA 3','fácil'],
['¿Qué material se incorpora a la coraza para reducir la radiación de fuga?',['Plomo','Tungsteno','Aluminio','Cobre'],0,'TEMA 3','fácil'],
['¿Qué función cumple el aceite contenido en la coraza del tubo?',['Favorecer el aislamiento eléctrico y la refrigeración','Aumentar la emisión termoiónica','Filtrar la radiación dispersa del paciente','Generar los rayos X'],0,'TEMA 3','medio'],
['¿Qué elemento del tubo permite la salida del haz útil de rayos X hacia el exterior?',['La ventana del tubo','El filamento','La copa de enfoque','El rotor'],0,'TEMA 3','fácil'],
['¿Qué componente permite hacer girar el ánodo en los tubos de ánodo rotatorio?',['El estator y el rotor','El colimador y el filtro','El filamento y la copa de enfoque','La ventana y la coraza'],0,'TEMA 3','medio'],
['¿Qué consecuencia tiene aumentar excesivamente la temperatura del ánodo?',['Puede producir daños en el blanco y limitar la capacidad de carga del tubo','Aumenta indefinidamente la vida útil del tubo','Elimina la radiación de frenado','Reduce siempre la producción de calor'],0,'TEMA 3','medio'],
['¿Qué objetivo persigue la filtración inherente y añadida del haz de rayos X?',['Eliminar fotones de baja energía que contribuirían a la dosis sin mejorar adecuadamente la imagen','Aumentar la radiación de baja energía','Reducir exclusivamente el tamaño del punto focal','Aumentar la corriente del tubo'],0,'TEMA 3','medio']
];
window.topic3Curated = topic3Curated;
