// Banco curado del TEMA 1 · preguntas históricas y evolución de la imagen médica.
const topic1Curated = [
['¿Quién descubrió los rayos X?',['Wilhelm Conrad Röntgen','Thomas Edison','Godfrey Hounsfield','Allan Cormack'],0,'TEMA 1','fácil','Wilhelm Conrad Röntgen descubrió los rayos X en 1895 mientras investigaba fenómenos relacionados con tubos de descarga.'],
['¿En qué año descubrió Wilhelm Conrad Röntgen los rayos X?',['1895','1890','1905','1911'],0,'TEMA 1','fácil','Röntgen descubrió los rayos X en 1895, un acontecimiento que marcó el inicio de la radiología.'],
['¿Qué fecha corresponde a la primera radiografía de la mano de la esposa de Röntgen?',['22 de diciembre de 1895','8 de noviembre de 1895','22 de diciembre de 1896','1 de enero de 1896'],0,'TEMA 1','medio','La radiografía de la mano de Anna Bertha Röntgen se realizó el 22 de diciembre de 1895 y es una de las primeras imágenes radiográficas de la historia.'],
['¿Qué ocurrió el 8 de noviembre de 1895?',['Röntgen descubrió los rayos X','Röntgen realizó la primera radiografía de la mano de su esposa','Se obtuvo la primera imagen de TAC','Se desarrolló la primera RM clínica'],0,'TEMA 1','fácil','El 8 de noviembre de 1895 Röntgen observó los efectos de una radiación desconocida que posteriormente denominó rayos X.'],
['¿Qué científico aparece relacionado con el descubrimiento del radio?',['Marie Curie','Röntgen','Salomon','Hounsfield'],0,'TEMA 1','fácil','Marie Curie está vinculada al descubrimiento y estudio del radio y del polonio, trabajos fundamentales para el desarrollo de la radiactividad.'],
['¿En qué año recibió Marie Curie el Premio Nobel de Química por sus trabajos relacionados con el radio y el polonio?',['1911','1895','1913','1952'],0,'TEMA 1','medio','Marie Curie recibió en 1911 el Premio Nobel de Química por sus trabajos sobre el radio y el polonio.'],
['¿Quién está relacionado con el desarrollo inicial de la mamografía mediante el estudio radiológico de la mama?',['Albert Salomon','Marie Curie','Wilhelm Röntgen','Raymond Damadian'],0,'TEMA 1','medio','Albert Salomon estudió radiológicamente piezas de mama y está relacionado con los primeros trabajos sistemáticos de mamografía.'],
['¿En qué año se sitúa el trabajo de Salomon relacionado con la mamografía?',['1913','1911','1952','1972'],0,'TEMA 1','medio','El trabajo de Albert Salomon sobre el estudio radiológico de la mama se sitúa en 1913.'],
['¿Qué científicos recibieron el Premio Nobel de Física de 1952 por sus trabajos fundamentales sobre la resonancia magnética nuclear?',['Félix Bloch y Edward Purcell','Hounsfield y Cormack','Lauterbur y Mansfield','Röntgen y Curie'],0,'TEMA 1','medio','Félix Bloch y Edward Purcell recibieron el Nobel de Física de 1952 por sus trabajos fundamentales sobre la resonancia magnética nuclear.'],
['¿Qué acontecimiento relacionado con la tomografía computarizada se sitúa en 1972?',['Primer protocolo de TAC cerebral','Introducción del TAC helicoidal','Primeras imágenes de RM','Primera promoción de técnicos de rayos'],0,'TEMA 1','medio','En 1972 se presentó el primer protocolo de tomografía computarizada cerebral, asociado al desarrollo inicial del TAC.'],
['¿Qué investigadores aparecen relacionados con el desarrollo del PET en la cronología histórica?',['Michael E. Phelps y Edward J. Hoffman','Hounsfield y Cormack','Bloch y Purcell','Lauterbur y Mansfield'],0,'TEMA 1','difícil','Michael E. Phelps y Edward J. Hoffman están relacionados con el desarrollo inicial de la tomografía por emisión de positrones (PET).'],
['¿Qué acontecimiento se sitúa en 1977 en la cronología histórica del tema?',['Primera promoción de técnicos de rayos','Primer protocolo de TAC cerebral','Primeras imágenes de TAC','Introducción del TAC helicoidal'],0,'TEMA 1','medio','En 1977 se sitúa en esta cronología la primera promoción de técnicos de rayos.'],
['¿Qué investigadores están asociados al desarrollo de las imágenes de TAC?',['Godfrey Hounsfield y Allan Cormack','Lauterbur y Mansfield','Bloch y Purcell','Röntgen y Salomon'],0,'TEMA 1','fácil','Godfrey Hounsfield y Allan Cormack están asociados al desarrollo de la tomografía computarizada y recibieron el Nobel de Fisiología o Medicina en 1979.'],
['¿En qué año se sitúa la introducción del TAC helicoidal?',['1990','1972','1979','2003'],0,'TEMA 1','medio','La introducción del TAC helicoidal se sitúa en 1990, una evolución importante respecto a la adquisición convencional por cortes.'],
['¿En qué año se sitúa la referencia histórica a la titulación de Técnico Superior en Imagen para el Diagnóstico (TSID)?',['1995','1990','2003','2014'],0,'TEMA 1','medio','En 1995 se sitúa la referencia histórica a la titulación de Técnico Superior en Imagen para el Diagnóstico (TSID).'],
['¿Qué investigadores recibieron el Premio Nobel de Fisiología o Medicina de 2003 por sus descubrimientos relacionados con la resonancia magnética?',['Paul C. Lauterbur y Peter Mansfield','Godfrey Hounsfield y Allan Cormack','Félix Bloch y Edward Purcell','Michael Phelps y Edward Hoffman'],0,'TEMA 1','medio','Paul C. Lauterbur y Peter Mansfield recibieron el Nobel de Fisiología o Medicina de 2003 por descubrimientos relacionados con la resonancia magnética.'],
['¿Qué titulación corresponde actualmente a la formación profesional superior del ámbito de la imagen para el diagnóstico y la medicina nuclear?',['Técnico Superior en Imagen para el Diagnóstico y Medicina Nuclear','Técnico Superior en Radiología Médica','Técnico Especialista en Radiodiagnóstico','Técnico Superior en Diagnóstico por Imagen'],0,'TEMA 1','fácil','La titulación actual es Técnico Superior en Imagen para el Diagnóstico y Medicina Nuclear, que integra la formación en ambas áreas.'],
['¿En qué se centraban buena parte de las investigaciones que precedieron al descubrimiento de los rayos X?',['En el estudio de las descargas eléctricas en gases a diferentes presiones','En el desarrollo de equipos de resonancia magnética','En la obtención de imágenes mediante ultrasonidos','En el desarrollo de detectores digitales'],0,'TEMA 1','medio','Antes del descubrimiento de los rayos X, buena parte de la investigación se centraba en las descargas eléctricas a través de gases y en los fenómenos producidos en tubos de descarga.'],
['¿Qué modificación del ánodo permitió mejorar las condiciones de producción de rayos X al reducir la concentración del impacto sobre una zona fija?',['La incorporación del ánodo giratorio','La eliminación del ánodo','La sustitución del ánodo por un detector digital','La incorporación de un colimador automático'],0,'TEMA 1','medio','El ánodo giratorio reparte el impacto de los electrones sobre una pista más amplia, facilitando la gestión térmica y permitiendo trabajar con mayores cargas.'],
['¿Qué científico está relacionado con las primeras aplicaciones militares del sónar, antecedente de las aplicaciones posteriores de los ultrasonidos?',['Paul Langevin','Wilhelm Röntgen','Godfrey Hounsfield','Allan Cormack'],0,'TEMA 1','difícil','Paul Langevin desarrolló aplicaciones del sónar basadas en ultrasonidos; estos trabajos constituyen un antecedente importante de las aplicaciones posteriores de los ultrasonidos.'],
];
window.topic1Curated = topic1Curated;
