// Banco curado del TEMA 18.
const topic18Curated = [
["¿Cuáles son las cinco densidades radiológicas básicas?",["Aire, grasa, agua, calcio y metal.","Aire, músculo, sangre, hueso y metal.","Grasa, agua, músculo, calcio y contraste.","Aire, líquido, músculo, hueso y contraste."],0,"TEMA 18","fácil","Las cinco densidades básicas se ordenan de menor a mayor atenuación como aire, grasa, agua/tejidos blandos, calcio/hueso y metal. Memorizar este orden ayuda a interpretar rápidamente una radiografía."],
["¿Qué densidad radiológica presenta menor atenuación de los rayos X?",["Metal.","Calcio.","Grasa.","Aire."],3,"TEMA 18","fácil","El aire atenúa muy poco los rayos X y por eso aparece radiolúcido, es decir, más oscuro en la radiografía. La grasa atenúa algo más, seguida de agua/tejidos blandos, calcio y metal."],
["En una radiografía, ¿qué material presenta habitualmente la mayor atenuación de los rayos X?",["Aire.","Grasa.","Agua.","Metal."],3,"TEMA 18","fácil","El metal presenta una atenuación muy elevada, por lo que bloquea gran parte de los rayos X y aparece muy radiopaco, es decir, blanco o muy claro en la imagen."],
["La finalidad de reducir al máximo el tiempo de exposición durante una exploración radiográfica es:",["Aumentar siempre la magnificación.","Reducir el efecto de movimiento y mejorar la nitidez de la imagen.","Eliminar la necesidad de utilizar protección radiológica.","Aumentar la distancia foco-película."],1,"TEMA 18","medio","Un tiempo de exposición corto reduce la posibilidad de que el paciente se mueva durante la adquisición. Menos movimiento significa menos borrosidad cinética y, por tanto, mayor nitidez."],
["Para conseguir una radiografía de calidad, además de controlar el movimiento, es importante:",["Inmovilizar o mantener correctamente al paciente durante la exposición.","Aumentar siempre el tiempo de exposición.","Colocar al paciente siempre en decúbito.","Utilizar siempre el mismo factor técnico."],0,"TEMA 18","fácil","La inmovilización o una posición estable evita movimientos durante la exposición. No existe una posición ni unos factores técnicos únicos: deben adaptarse a la exploración y a la anatomía estudiada."],
["¿Qué efecto puede producir el movimiento del paciente durante la exposición radiográfica?",["Aumento de la resolución espacial.","Borrosidad de la imagen.","Disminución de la magnificación.","Aumento de la densidad del tejido."],1,"TEMA 18","fácil","El movimiento durante la exposición hace que los bordes de las estructuras queden desplazados y poco definidos. El resultado es borrosidad por movimiento, que puede dificultar la interpretación."],
["Al realizar una radiografía, la elección de la técnica debe tener en cuenta principalmente:",["Únicamente el tamaño del receptor.","El tamaño y las características de la zona anatómica que se va a estudiar.","Únicamente la edad del paciente.","Exclusivamente la distancia foco-receptor."],1,"TEMA 18","medio","La técnica radiográfica debe adaptarse a la región anatómica: grosor, composición y características de la zona influyen en la elección de los factores técnicos. No basta con considerar un único parámetro."],
["¿Qué información debe conocer el técnico para definir correctamente una proyección radiológica?",["Solo la posición del paciente.","La posición del paciente, la dirección y el punto de incidencia del haz.","Solo el tamaño del receptor de imagen.","Únicamente los factores técnicos."],1,"TEMA 18","medio","Para describir una proyección hay que saber cómo está colocado el paciente y cómo atraviesa el haz la anatomía: dirección del rayo central y punto de entrada/incidencia. La posición por sí sola no define la proyección."],
["¿Qué elemento describe la orientación del paciente respecto al receptor de imagen?",["La posición.","La incidencia.","La distancia foco-receptor.","La colimación."],0,"TEMA 18","fácil","La posición describe la relación y orientación del paciente respecto al receptor y al espacio. La incidencia, en cambio, se refiere al recorrido del haz de rayos X y a cómo entra en el cuerpo."],
["En la nomenclatura radiológica, una proyección debe definirse teniendo en cuenta:",["Únicamente la parte anatómica estudiada.","La dirección del haz de rayos X y su punto de entrada y salida.","Exclusivamente la posición del receptor.","Solo el lado anatómico explorado."],1,"TEMA 18","medio","Una proyección se define por la dirección que sigue el haz a través del paciente y por sus puntos de entrada y salida. Por eso una misma región anatómica puede estudiarse mediante diferentes proyecciones."],
["¿Cuál de las siguientes corresponde a una denominación de posición oblicua representada en el material?",["Oblicua anterior derecha.","Decúbito lateral inferior.","Supino posterior.","Vertical oblicua izquierda."],0,"TEMA 18","medio","Una posición oblicua se identifica indicando el sentido de la oblicuidad y el lado correspondiente. 'Oblicua anterior derecha' es una denominación anatómica de posición válida."],
["¿Cuál de las siguientes parejas corresponde a posiciones oblicuas diferentes?",["Oblicua anterior derecha y oblicua posterior derecha.","Supino anterior y supino posterior.","Decúbito superior y decúbito inferior.","Lateral anterior y lateral posterior."],0,"TEMA 18","medio","Las posiciones oblicuas pueden diferenciarse según sean anteriores o posteriores y según el lado. Por eso una oblicua anterior derecha y una oblicua posterior derecha son posiciones distintas."],
["En la denominación de una posición oblicua, ¿qué información permite diferenciar una oblicua anterior derecha de una oblicua anterior izquierda?",["El tamaño del receptor.","El lado hacia el que se orienta el paciente.","La distancia foco-paciente.","El tiempo de exposición."],1,"TEMA 18","medio","La diferencia entre derecha e izquierda identifica el lado hacia el que se orienta el paciente. El tamaño del receptor, la distancia y el tiempo de exposición son parámetros técnicos, no parte de esa denominación."],
["¿Qué debe determinarse antes de realizar una proyección radiológica para conseguir una correcta representación anatómica?",["Únicamente el kilovoltaje.","La posición del paciente y la orientación del haz de rayos X.","Solo la distancia foco-receptor.","Únicamente el tamaño del campo."],1,"TEMA 18","medio","Antes de exponer hay que colocar correctamente al paciente y establecer la trayectoria del haz. Una mala posición o una orientación incorrecta puede provocar una representación anatómica inadecuada aunque los factores técnicos sean correctos."],
["¿Qué objetivo tiene adaptar correctamente la posición del paciente antes de realizar una radiografía?",["Conseguir una representación adecuada de la estructura anatómica que se quiere estudiar.","Aumentar siempre la dosis recibida.","Eliminar la necesidad de colimar.","Evitar cualquier tipo de inmovilización."],0,"TEMA 18","fácil","La posición se adapta para mostrar correctamente la anatomía de interés y obtener la proyección solicitada. Una buena colocación no pretende aumentar la dosis ni sustituye la colimación o la inmovilización cuando son necesarias."],
["¿Qué debe indicar una correcta descripción de una proyección radiológica?",["Únicamente el nombre de la región anatómica.","La posición del paciente, la dirección del haz y el punto de incidencia.","Solo el lado derecho o izquierdo.","Únicamente los valores de kV y mAs."],1,"TEMA 18","medio","La descripción completa relaciona la posición del paciente con el recorrido del haz y su punto de incidencia. Los kV y mAs son factores técnicos y no sustituyen la descripción de la proyección."],
["¿Por qué es importante conocer la terminología de las posiciones y proyecciones radiológicas?",["Porque permite utilizar una nomenclatura común y realizar correctamente las exploraciones.","Porque determina exclusivamente la dosis de radiación.","Porque sustituye la identificación anatómica del paciente.","Porque permite prescindir de las instrucciones al paciente."],0,"TEMA 18","fácil","La terminología permite que técnicos y demás profesionales utilicen un lenguaje común y preciso. Así se puede identificar y realizar la exploración de forma coherente y reproducible."],
["¿Qué aspectos deben tenerse en cuenta además de la posición y la proyección para realizar correctamente una radiografía?",["Únicamente el tamaño corporal del paciente.","Las medidas de protección radiológica y los factores técnicos.","Solo la distancia entre el paciente y el receptor.","Exclusivamente la edad del paciente."],1,"TEMA 18","medio","Una radiografía correcta no depende solo de colocar al paciente y elegir la proyección. También hay que aplicar las medidas de protección radiológica y seleccionar los factores técnicos adecuados para la exploración."],
["Si una estructura anatómica no queda correctamente incluida o centrada en la imagen, ¿qué elemento relacionado con la realización de la radiografía debe revisarse especialmente?",["El punto de incidencia y la dirección del haz.","Únicamente la edad del paciente.","El color del receptor.","La marca del equipo."],0,"TEMA 18","medio","Si la anatomía no queda bien centrada o incluida, hay que revisar dónde y cómo se dirigió el haz, especialmente el punto de incidencia y su dirección. La colimación y el centrado también deben comprobarse en la práctica."],
["¿Cuál de las siguientes afirmaciones resume correctamente los aspectos fundamentales para realizar una radiografía de calidad?",["Basta con elegir correctamente el receptor de imagen.","Es necesario controlar la posición e inmovilización del paciente, la proyección, el haz de rayos X, la colimación y los factores técnicos.","Lo más importante es aumentar el tiempo de exposición.","La posición del paciente no influye si los factores técnicos son correctos."],1,"TEMA 18","difícil","La calidad radiográfica depende de varios elementos que deben trabajar juntos: colocación e inmovilización del paciente, proyección, centrado y dirección del haz, colimación y factores técnicos adecuados. Un solo parámetro correcto no compensa errores en los demás."]
];
window.topic18Curated = topic18Curated;

// El Tema 18 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank18 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank18().filter(q=>q[3]!=='TEMA 18'); };
