// Test curado del TEMA 41 · EXPLORACIÓN ECOGRÁFICA DE LA MAMA
const topic41Curated = [
  ["¿Qué frecuencia central mínima deben tener los transductores lineales utilizados en la ecografía mamaria?", ["5 MHz", "7 MHz", "10 MHz", "15 MHz"], 2, "TEMA 41", "fácil", "En ecografía mamaria se utilizan transductores lineales de alta frecuencia, con una frecuencia central mínima de 10 MHz. Las altas frecuencias proporcionan una mejor resolución espacial, algo especialmente importante para estudiar estructuras superficiales como la mama."],
  ["En la ecografía mamaria, la ganancia debe ajustarse inicialmente de forma que:", ["El músculo pectoral sea el valor central de referencia.", "La grasa sea el valor central.", "La lesión tenga siempre la máxima ecogenicidad.", "Los tejidos fibrosos aparezcan anecoicos."], 1, "TEMA 41", "medio", "La ganancia debe ajustarse inicialmente tomando la grasa como referencia central de la escala de grises. Esto permite obtener una representación equilibrada de los tejidos y valorar correctamente las diferencias de ecogenicidad entre ellos."],
  ["¿Cuál de las siguientes asociaciones respecto a la ecogenicidad es CORRECTA?", ["Anecoica → masas sólidas.", "Hipoecogénica → quistes simples.", "Ecogénica → ligamentos de Cooper y tejido fibroso.", "Hiperecogénica → quistes simples."], 2, "TEMA 41", "medio", "Los ligamentos de Cooper y el tejido fibroso presentan un aspecto ecogénico debido a que producen numerosos ecos. En cambio, un quiste simple es típicamente anecoico y una masa sólida puede ser hipoecogénica."],
  ["Respecto a las zonas focales, señale la opción CORRECTA:", ["Deben situarse siempre por encima de la lesión.", "Deben situarse al mismo nivel que la lesión.", "Solo pueden utilizarse focos multifocales.", "El foco no influye en la visualización de la lesión."], 1, "TEMA 41", "medio", "La zona focal debe situarse al mismo nivel que la lesión que queremos estudiar. El foco permite optimizar la resolución lateral en esa profundidad y, por tanto, mejorar la visualización y caracterización de la lesión."],
  ["En cuanto a la profundidad del campo de visión durante la ecografía mamaria:", ["Debe ser siempre inferior a 2 cm.", "Debe ser exactamente de 4 cm.", "Debe ser de al menos 4 cm y permitir visualizar el músculo pectoral en el margen posterior.", "Debe ser superior a 10 cm en todas las pacientes."], 2, "TEMA 41", "difícil", "El campo de visión debe alcanzar al menos 4 cm de profundidad y permitir visualizar el músculo pectoral en el margen posterior. Esto garantiza que se ha explorado adecuadamente el espesor mamario y no se ha limitado el campo antes de llegar a estructuras profundas."],
  ["La posición de la paciente en decúbito supino con el brazo por encima de la cabeza tiene como finalidad principal:", ["Aumentar el espesor mamario y visualizar mejor las lesiones profundas.", "Reducir el espesor mamario y estirar el pectoral.", "Evitar el movimiento respiratorio.", "Comprimir la mama contra la camilla."], 1, "TEMA 41", "fácil", "Colocar a la paciente en decúbito supino con el brazo por encima de la cabeza ayuda a reducir el espesor de la mama y estirar el músculo pectoral, facilitando la exploración sistemática y la visualización de las estructuras profundas."],
  ["Para estudiar una lesión localizada lateralmente o en la axila, la posición recomendada es:", ["Decúbito prono.", "Decúbito supino estricto.", "Posición oblicua.", "Posición sentada obligatoriamente."], 2, "TEMA 41", "fácil", "Para explorar lesiones situadas lateralmente o próximas a la axila puede utilizarse una posición oblicua, que facilita el acceso al tejido lateral y a la región axilar."],
  ["Una paciente presenta una lesión que únicamente puede palparse cuando está de pie. ¿Qué posición puede utilizarse para la exploración?", ["Sentada.", "Decúbito prono.", "Trendelenburg.", "Decúbito lateral exclusivamente."], 0, "TEMA 41", "fácil", "Si una lesión solamente es palpable cuando la paciente está de pie, puede realizarse la exploración en posición sentada. La posición debe adaptarse a la localización y a las condiciones en las que el hallazgo puede identificarse mejor."],
  ["En relación con la documentación de los hallazgos ecográficos, el tamaño de una lesión debe documentarse:", ["En un único plano.", "Solo mediante una imagen sin medidas.", "Mostrando los ejes en al menos dos planos.", "Únicamente mediante una medición del diámetro máximo."], 2, "TEMA 41", "medio", "Una lesión debe medirse en al menos dos planos, para representar adecuadamente sus dimensiones. Una única medida no permite conocer correctamente el tamaño tridimensional de la lesión."],
  ["Además de las imágenes con las medidas de la lesión, debe obtenerse al menos:", ["Una imagen sin medidas que incluya lateralidad, localización y orientación del transductor.", "Una imagen exclusivamente en plano radial.", "Una imagen sin información del paciente.", "Una imagen únicamente del músculo pectoral."], 0, "TEMA 41", "medio", "Además de las imágenes con las medidas, debe obtenerse al menos una imagen sin mediciones que documente adecuadamente el hallazgo, incluyendo la información necesaria para identificar su lateralidad, localización y orientación del transductor. Esto mejora la documentación y reproducibilidad del estudio."],
  ["Una exploración ecográfica mamaria se considera reproducible cuando:", ["Se realiza siempre con el mismo ecógrafo.", "Se utilizan exclusivamente imágenes en tiempo real.", "Otro radiólogo puede reproducir el estudio tras visualizar las imágenes previas.", "Se realizan exactamente cuatro imágenes por mama."], 2, "TEMA 41", "medio", "Una exploración reproducible es aquella en la que otro profesional puede reconocer y reproducir el estudio a partir de las imágenes obtenidas. Por eso es fundamental documentar correctamente la localización, orientación y características de los hallazgos."],
  ["Durante la exploración en tiempo real, ¿cuál de las siguientes posibilidades permite la ecografía?", ["Identificar artefactos y valorar la movilidad de las lesiones.", "Valorar únicamente la ecogenicidad.", "Evitar la valoración de la relación con otras estructuras.", "Sustituir siempre a la mamografía."], 0, "TEMA 41", "medio", "Una de las grandes ventajas de la ecografía es que permite observar las estructuras en tiempo real, lo que facilita identificar artefactos y valorar aspectos dinámicos como la movilidad o determinados cambios de una lesión con la presión del transductor."],
  ["Respecto a la presión ejercida con el transductor:", ["Debe ser siempre máxima para mejorar la penetración.", "Debe ser mínima, aumentando únicamente cuando sea necesario valorar colapsabilidad o rigidez.", "Nunca debe modificarse durante el estudio.", "Debe ser suficiente para comprimir completamente la mama."], 1, "TEMA 41", "medio", "La presión debe ser inicialmente mínima, evitando deformar innecesariamente los tejidos. Puede aumentarse cuando interese valorar características como la colapsabilidad o rigidez. Una presión excesiva podría modificar artificialmente el aspecto de determinadas lesiones."],
  ["¿Qué estándar se utiliza para la superposición de los planos durante la exploración mamaria?", ["Longitudinal/transversal.", "Sagital/coronal.", "Radial/antirradial.", "Axial/oblicuo."], 2, "TEMA 41", "fácil", "En la mama se utiliza como referencia la orientación radial y antirradial, relacionada con la disposición anatómica de los conductos mamarios. Estos planos permiten estudiar sistemáticamente el tejido y describir de forma reproducible la orientación de las lesiones."],
  ["El sistema BI-RADS de ultrasonidos fue introducido en 2003 por:", ["WHO.", "European Society of Radiology.", "American College of Radiology.", "FDA."], 2, "TEMA 41", "fácil", "El BI-RADS para ecografía fue introducido en 2003 por el American College of Radiology (ACR). Su objetivo es estandarizar la descripción de los hallazgos mamarios y facilitar una clasificación y comunicación homogéneas."],
  ["Según la clasificación de los márgenes de una masa, un margen microlobulado presenta:", ["Líneas puntiagudas que se proyectan desde la masa.", "Esquinas afiladas.", "Aspecto festoneado.", "Transición abrupta y perfectamente definida."], 2, "TEMA 41", "medio", "Un margen microlobulado presenta un contorno festoneado, formado por pequeñas lobulaciones. Es importante distinguirlo de otros márgenes: el angular presenta esquinas y el espiculado muestra líneas que se proyectan desde la masa."],
  ["¿Cuál de las siguientes características corresponde a un margen espiculado?", ["Aspecto festoneado.", "Líneas puntiagudas que se proyectan desde la masa.", "Ausencia de diferencia entre masa y tejido.", "Halo ecogénico bien definido."], 1, "TEMA 41", "medio", "El margen espiculado se caracteriza por la presencia de líneas o prolongaciones puntiagudas que se proyectan desde la masa hacia el tejido circundante. Es un hallazgo de especial importancia en la caracterización ecográfica de una masa."],
  ["En cuanto a la atenuación posterior, el realce se caracteriza por:", ["Disminución de los ecos posteriores.", "Ausencia completa de ecos internos.", "Aumento de los ecos posteriores.", "Presencia simultánea de sombra y realce."], 2, "TEMA 41", "fácil", "El realce posterior consiste en un aumento de los ecos situados detrás de una lesión. Se produce cuando la lesión atenúa menos el haz de ultrasonidos que los tejidos circundantes. Es diferente de la sombra acústica posterior, en la que disminuyen los ecos."],
  ["¿Cuál de las siguientes NO pertenece a los hallazgos descritos como posibles alteraciones del tejido adyacente?", ["Edema.", "Distorsión estructural.", "Engrosamiento cutáneo.", "Aumento de la frecuencia del transductor."], 3, "TEMA 41", "fácil", "Entre las alteraciones que pueden observarse en el tejido adyacente se encuentran el edema, la distorsión estructural y el engrosamiento cutáneo. La frecuencia del transductor es un parámetro técnico del estudio, no una alteración del tejido."],
  ["¿Cuál de las siguientes es una indicación de la ecografía mamaria según el tema?", ["Exclusivamente el estudio de mujeres mayores de 50 años.", "Evaluación inicial de masas palpables en mujeres menores de 30 años, lactantes y embarazadas.", "Sustitución sistemática de la mamografía en el cribado.", "Exclusivamente la valoración de quistes simples."], 1, "TEMA 41", "medio", "La ecografía tiene especial importancia como evaluación inicial de masas mamarias en mujeres menores de 30 años, así como durante el embarazo y la lactancia. En estos grupos resulta especialmente útil por las características del tejido mamario y por las circunstancias clínicas."],
  ["Una lesión mamaria palpable ya identificada previamente mediante RM debe buscarse ecográficamente:", ["Sin tener en cuenta su localización en la RM, ya que la ecografía es independiente.", "Prestando especial atención para asegurar una correcta correlación con el hallazgo previo.", "Únicamente en posición sentada.", "Solo mediante Doppler."], 1, "TEMA 41", "difícil", "Cuando existe una lesión identificada previamente mediante RM, la búsqueda ecográfica debe realizarse procurando una correcta correlación con el hallazgo de RM. La ecografía puede utilizarse para localizar y caracterizar la lesión y, cuando es posible, facilitar su evaluación o intervención."],
  ["¿Cuál de las siguientes opciones describe CORRECTAMENTE una masa hipoecogénica?", ["Presenta ausencia de ecos internos.", "Tiene un bajo nivel de ecos en toda la lesión.", "Tiene la misma ecogenicidad que la grasa.", "Presenta mayor ecogenicidad que la grasa."], 1, "TEMA 41", "medio", "Una masa hipoecogénica presenta un nivel de ecos bajo en toda la lesión en comparación con el tejido de referencia. No significa ausencia total de ecos: esa característica corresponde a una estructura anecoica, como puede ser un quiste simple."],
  ["¿Cuál de las siguientes pertenece a los casos especiales contemplados en BI-RADS?", ["Distorsión estructural.", "Engrosamiento cutáneo.", "Microquistes agrupados.", "Margen angular."], 2, "TEMA 41", "medio", "Los microquistes agrupados aparecen contemplados entre los casos especiales descritos en BI-RADS. Es importante no confundirlos con descriptores generales de una masa, como el margen angular o la orientación."],
  ["En relación con la vascularización de una lesión, BI-RADS contempla:", ["Únicamente vascularización presente dentro de la lesión.", "Solo vascularización ausente o presente.", "Vascularización en la lesión, junto a ella o difusamente incrementada en el tejido adyacente, entre otras posibilidades.", "Exclusivamente vascularización arterial."], 2, "TEMA 41", "difícil", "La valoración vascular mediante Doppler puede describirse de diferentes formas: puede existir vascularización dentro de la lesión, junto a ella o un aumento difuso de la vascularización en el tejido adyacente, entre otras posibilidades. Por tanto, no se limita simplemente a decir “vascularización presente o ausente”."],
  ["¿Cuál de las siguientes NO figura entre las indicaciones de la ecografía mamaria recogidas en el tema?", ["Guía intervencionista de mama y axila.", "Planificación de radioterapia.", "Evaluación de implantes.", "Sustitución obligatoria de la mamografía en todas las mujeres."], 3, "TEMA 41", "fácil", "La ecografía mamaria tiene múltiples indicaciones, entre ellas la guía de procedimientos intervencionistas, la evaluación de implantes y la planificación de radioterapia. No sustituye de forma obligatoria a la mamografía en todas las mujeres; ambas técnicas pueden complementarse según la situación clínica."]
];

window.topic41Curated = topic41Curated;

const previousTopicMenu41 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu41();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 41'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 41</span><h3>${esc((topics[41]||{}).title||'TEMA 41')}</h3><p>${topic41Curated.length} preguntas · ecografía mamaria</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 41', topic41Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 41</span><h3>${esc((topics[41]||{}).title||'TEMA 41')}</h3><p>${topic41Curated.length} preguntas · ecografía mamaria</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 41', topic41Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 41; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
