// Banco curado del TEMA 3 · tubo de rayos X.
const topic3Curated = [
['¿Qué componente del tubo de rayos X es responsable de la emisión termoiónica?',['El filamento del cátodo','El blanco del ánodo','La coraza protectora','La ventana de salida'],0,'TEMA 3','fácil'],'El filamento del cátodo se calienta y libera electrones por emisión termoiónica.',
['¿Cuál es la función principal de la copa de enfoque del cátodo?',['Concentrar los electrones hacia el punto focal','Aumentar la tensión del tubo','Absorber la radiación de fuga','Refrigerar el ánodo'],0,'TEMA 3','fácil'],'La copa de enfoque, cargada negativamente, concentra los electrones emitidos para dirigirlos hacia el punto focal del ánodo.',
['¿Qué material se utiliza habitualmente en el filamento del tubo de rayos X por su elevado punto de fusión?',['Tungsteno','Cobre','Plomo','Aluminio'],0,'TEMA 3','fácil'],'El tungsteno soporta las altas temperaturas del filamento gracias a su elevado punto de fusión y buena capacidad para mantener la emisión.',
['¿Qué función desempeña principalmente el ánodo en el tubo de rayos X?',['Recibir los electrones y convertir parte de su energía en rayos X','Emitir electrones por efecto termoiónico','Colimar el haz de radiación','Proteger al paciente de la radiación dispersa'],0,'TEMA 3','fácil'],'El ánodo recibe los electrones procedentes del cátodo y transforma su energía cinética principalmente en calor y, en una pequeña parte, en rayos X.',
['¿Por qué se utiliza tungsteno como material del blanco del ánodo?',['Por su alto número atómico y elevado punto de fusión','Por su bajo número atómico y bajo punto de fusión','Porque es un material ferromagnético','Porque es completamente transparente a los rayos X'],0,'TEMA 3','medio'],'El tungsteno combina un número atómico alto, favorable para producir rayos X, con un punto de fusión muy elevado, necesario para soportar el calor.',
['¿Qué porcentaje aproximado de la energía cinética de los electrones se transforma en rayos X en un tubo convencional?',['Alrededor del 1 %','Alrededor del 25 %','Alrededor del 50 %','Alrededor del 90 %'],0,'TEMA 3','medio'],'En un tubo convencional, aproximadamente el 1 % de la energía de los electrones se convierte en rayos X; la gran mayoría se transforma en calor.',
['¿En qué se transforma principalmente la energía restante de los electrones al impactar sobre el ánodo?',['En calor','En radiación gamma','En ultrasonidos','En luz visible'],0,'TEMA 3','fácil'],'La mayor parte de la energía restante se deposita en el blanco del ánodo como calor, por eso la gestión térmica es fundamental.',
['¿Qué ventaja principal aporta un ánodo giratorio frente a uno fijo?',['Permite repartir el calor sobre una superficie mayor del blanco','Elimina completamente la radiación de frenado','Evita la emisión termoiónica','Reduce a cero la producción de calor'],0,'TEMA 3','medio'],'El ánodo giratorio distribuye el impacto de los electrones por una pista más extensa del blanco y permite disipar mejor el calor.',
['¿Qué se entiende por punto focal real?',['La zona física del blanco sobre la que impactan los electrones','El tamaño aparente del foco desde el paciente','La zona de salida del haz útil','La superficie externa de la coraza'],0,'TEMA 3','medio'],'El punto focal real es la superficie física del blanco del ánodo sobre la que incide el haz de electrones.',
['¿Qué principio permite obtener un punto focal efectivo menor que el punto focal real?',['Principio del foco lineal','Ley del inverso del cuadrado','Efecto fotoeléctrico','Principio de exclusión de Pauli'],0,'TEMA 3','medio'],'El principio del foco lineal aprovecha la inclinación del blanco: el foco efectivo visto desde el receptor resulta menor que la zona real de impacto.',
['¿Qué relación existe entre el tamaño del punto focal efectivo y el ángulo del ánodo?',['Al disminuir el ángulo del ánodo, disminuye el tamaño del foco efectivo','Al disminuir el ángulo del ánodo, aumenta siempre el tamaño del foco efectivo','El ángulo del ánodo no influye','El foco efectivo desaparece'],0,'TEMA 3','difícil'],'Al disminuir el ángulo del ánodo, disminuye el tamaño del foco efectivo, aunque también aumenta el efecto talón y condiciona la capacidad térmica.',
['¿Qué efecto del ánodo hace que la intensidad del haz sea mayor en el lado del cátodo que en el lado del ánodo?',['Efecto talón del ánodo','Efecto Compton','Efecto fotoeléctrico','Efecto Doppler'],0,'TEMA 3','fácil'],'El efecto talón se debe a la autoabsorción de fotones dentro del material del ánodo; por eso la intensidad es mayor hacia el lado del cátodo.',
['¿Cómo debe orientarse habitualmente el paciente cuando se quiere aprovechar el efecto talón para una parte anatómica de mayor espesor?',['La parte más gruesa hacia el lado del cátodo','La parte más gruesa hacia el lado del ánodo','La parte más gruesa siempre hacia el centro','La orientación es indiferente'],0,'TEMA 3','medio'],'Como el lado del cátodo tiene mayor intensidad, se coloca allí la parte anatómica más gruesa para compensar la diferencia de exposición.',
['¿Qué parámetro controla principalmente la energía o poder de penetración del haz de rayos X?',['La tensión del tubo (kV)','La corriente del tubo (mA)','El tiempo de exposición','La distancia foco-película'],0,'TEMA 3','fácil'],'El kV determina principalmente la energía de los fotones y, por tanto, el poder de penetración del haz.',
['¿Qué parámetro determina principalmente la cantidad de radiación X producida?',['El producto mAs','El kV exclusivamente','La distancia foco-detector','El tamaño del campo exclusivamente'],0,'TEMA 3','fácil'],'El mAs determina principalmente la cantidad de electrones que llegan al ánodo y, con ello, la cantidad de radiación X producida.',
['Si se duplica el mAs manteniendo constantes los demás factores, ¿qué ocurre aproximadamente con la cantidad de radiación producida?',['Se duplica','Se reduce a la mitad','Se cuadruplica','No cambia'],0,'TEMA 3','fácil'],'Si se duplica el mAs manteniendo todo lo demás constante, aproximadamente se duplica la cantidad de radiación producida.',
['¿Qué ocurre generalmente al aumentar el kV manteniendo constantes los demás factores?',['Aumenta la energía y la penetración del haz','Disminuye la energía del haz','Disminuye siempre la cantidad de fotones a la mitad','No cambia el espectro de rayos X'],0,'TEMA 3','medio'],'Al aumentar el kV aumentan la energía media y máxima de los fotones y, en general, también la cantidad de radiación producida.',
['¿Cuál es la función de la coraza del tubo de rayos X?',['Proporcionar protección radiológica y aislamiento eléctrico, además de facilitar la refrigeración','Generar electrones por efecto termoiónico','Aumentar directamente el kV','Colimar el haz dentro del paciente'],0,'TEMA 3','fácil'],'La coraza protege frente a la radiación de fuga, proporciona aislamiento eléctrico y contiene elementos que ayudan a gestionar el calor.',
['¿Qué material se incorpora a la coraza para reducir la radiación de fuga?',['Plomo','Tungsteno','Aluminio','Cobre'],0,'TEMA 3','fácil'],'El plomo se incorpora a la coraza porque atenúa eficazmente la radiación y ayuda a mantener la radiación de fuga dentro de los límites establecidos.',
['¿Qué función cumple el aceite contenido en la coraza del tubo?',['Favorecer el aislamiento eléctrico y la refrigeración','Aumentar la emisión termoiónica','Filtrar la radiación dispersa del paciente','Generar los rayos X'],0,'TEMA 3','medio'],'El aceite proporciona aislamiento eléctrico y ayuda a transferir el calor desde el tubo hacia la coraza para favorecer su disipación.',
['¿Qué elemento del tubo permite la salida del haz útil de rayos X hacia el exterior?',['La ventana del tubo','El filamento','La copa de enfoque','El rotor'],0,'TEMA 3','fácil'],'La ventana es la zona de salida diseñada para que el haz útil de rayos X abandone el tubo con la menor atenuación posible.',
['¿Qué componente permite hacer girar el ánodo en los tubos de ánodo rotatorio?',['El estator y el rotor','El colimador y el filtro','El filamento y la copa de enfoque','La ventana y la coraza'],0,'TEMA 3','medio'],'En un ánodo rotatorio, el rotor está asociado al ánodo dentro de la envolvente y el estator externo genera el campo magnético que lo hace girar.',
['¿Qué consecuencia tiene aumentar excesivamente la temperatura del ánodo?',['Puede producir daños en el blanco y limitar la capacidad de carga del tubo','Aumenta indefinidamente la vida útil del tubo','Elimina la radiación de frenado','Reduce siempre la producción de calor'],0,'TEMA 3','medio'],'Una temperatura excesiva puede dañar el blanco, deformar componentes y limitar la capacidad de carga, reduciendo la vida útil del tubo.',
['¿Qué objetivo persigue la filtración inherente y añadida del haz de rayos X?',['Eliminar fotones de baja energía que contribuirían a la dosis sin mejorar adecuadamente la imagen','Aumentar la radiación de baja energía','Reducir exclusivamente el tamaño del punto focal','Aumentar la corriente del tubo'],0,'TEMA 3','medio'],'La filtración elimina fotones de baja energía que serían absorbidos principalmente por el paciente y aportarían dosis sin contribuir de forma útil a la imagen.'
];
window.topic3Curated = topic3Curated;
