// Test curado del TEMA 31 · RADIOLOGÍA CONVENCIONAL EN PORTÁTIL, UCI Y QUIRÓFANO
const topic31Curated = [
  ["La radiología portátil se utiliza principalmente para realizar exploraciones:", ["En cualquier sala de radiología convencional", "Fuera de una sala plomada, cuando el paciente no puede desplazarse", "Exclusivamente dentro de quirófano", "Solo en UCI"], 1, "TEMA 31", "medio", "La radiología portátil permite realizar estudios fuera de la sala convencional cuando las condiciones clínicas impiden trasladar al paciente. No significa que pueda utilizarse sin las medidas de protección y seguridad correspondientes."],
  ["¿Cuál es una indicación característica de la radiología portátil en la UCI?", ["Pacientes que pueden desplazarse sin dificultad", "Pacientes que necesitan únicamente estudios dentales", "Pacientes críticos que no pueden ser movilizados", "Pacientes que precisan exclusivamente mamografía"], 2, "TEMA 31", "medio", "En la UCI muchos pacientes están conectados a dispositivos y presentan un estado clínico que hace poco seguro o imposible su traslado. La radiología portátil permite obtener las imágenes directamente junto a la cama."],
  ["En quirófano, la función principal de la radiología portátil es:", ["Realizar exclusivamente estudios preoperatorios", "Proporcionar control radiológico durante la intervención", "Sustituir siempre al ecógrafo", "Evitar cualquier procedimiento fluoroscópico"], 1, "TEMA 31", "medio", "El equipo portátil, especialmente el arco en C, permite obtener imágenes durante la intervención para controlar la posición de estructuras, implantes o material quirúrgico."],
  ["Antes de introducir un chasis o detector en una habitación de aislamiento o en un entorno con exigencias higiénicas, lo adecuado es:", ["Dejarlo descubierto para evitar artefactos", "Cubrirlo con una bolsa protectora adecuada", "Sumergirlo en líquido desinfectante", "Utilizarlo sin protección si es digital"], 1, "TEMA 31", "medio", "La cubierta protectora evita contaminar el detector y permite mantener las condiciones de higiene del entorno. Ser digital no elimina la necesidad de protección frente a contaminación."],
  ["¿Qué característica de la fluoroscopia pulsada contribuye a reducir la dosis respecto a una emisión continua equivalente?", ["Aumenta el número de imágenes por segundo", "Elimina la necesidad de colimar", "Emite radiación de forma intermitente", "Aumenta automáticamente el tamaño del campo"], 2, "TEMA 31", "difícil", "La fluoroscopia pulsada emite radiación en pulsos en lugar de mantener una emisión continua. Al reducir el tiempo efectivo de emisión puede disminuir la dosis, siempre dependiendo de la frecuencia de pulsos y de la configuración del equipo."],
  ["Durante una exploración con arco en C, la magnificación electrónica mediante el intensificador puede:", ["Eliminar la radiación dispersa", "Reducir siempre la dosis al paciente", "Incrementar la dosis necesaria", "Sustituir la colimación"], 2, "TEMA 31", "difícil", "La magnificación electrónica del intensificador puede requerir un aumento de la tasa de dosis para mantener una señal adecuada. Por eso no debe confundirse con el zoom digital, que amplía una imagen ya adquirida sin aumentar por sí mismo la exposición."],
  ["El zoom digital de una imagen obtenida con un sistema digital:", ["Aumenta directamente la dosis al paciente", "Amplía la imagen sin aumentar por sí mismo la dosis", "Obliga a repetir la exposición", "Solo puede utilizarse en fluoroscopia"], 1, "TEMA 31", "difícil", "El zoom digital modifica la visualización de los datos de una imagen ya adquirida. Al no realizar una nueva exposición, no incrementa por sí mismo la dosis recibida por el paciente."],
  ["El arco en C es:", ["Un equipo fijo de radiología convencional", "Un equipo móvil de fluoroscopia", "Un detector portátil exclusivamente", "Un sistema de revelado automático"], 1, "TEMA 31", "medio", "El arco en C es un sistema móvil de fluoroscopia formado por un brazo en forma de C que integra el tubo de rayos X y el receptor de imagen."],
  ["En un arco en C convencional, el intensificador de imagen actúa como:", ["Generador de alta tensión", "Receptor de imagen", "Colimador", "Transformador"], 1, "TEMA 31", "medio", "En los arcos en C convencionales, el intensificador transforma los rayos X en una imagen visible que posteriormente puede procesarse y visualizarse en el monitor."],
  ["El sistema automático de control de dosis de un equipo de fluoroscopia tiene como finalidad principal:", ["Regular la tasa de dosis a la entrada del paciente", "Determinar la posición del paciente", "Eliminar toda la radiación dispersa", "Aumentar siempre el tiempo de exposición"], 0, "TEMA 31", "difícil", "El control automático de exposición o de tasa de dosis ajusta los parámetros del equipo para mantener una señal de imagen adecuada. Su objetivo es adaptar la emisión, no eliminar la radiación dispersa ni aumentar siempre el tiempo."],
  ["La proyección más habitual en una radiografía portátil de tórax es:", ["PA", "AP", "Lateral derecha", "Oblicua posterior"], 1, "TEMA 31", "medio", "En los estudios portátiles el paciente suele estar encamado, por lo que la proyección AP es la más habitual. La PA requiere normalmente una posición que el paciente crítico no puede adoptar."],
  ["En un paciente encamado, la posición más habitual para realizar una radiografía portátil de tórax es:", ["Bipedestación", "Decúbito prono", "Decúbito supino", "Sedestación obligatoria"], 2, "TEMA 31", "medio", "El decúbito supino es la posición más frecuente en pacientes encamados porque es la que suele poder mantenerse con mayor seguridad. Si el estado clínico lo permite, puede intentarse una posición más incorporada."],
  ["Si el estado clínico del paciente lo permite, para una radiografía portátil de tórax es preferible intentar:", ["Mantener siempre el decúbito supino", "La sedestación", "El decúbito prono", "La posición de Trendelenburg"], 1, "TEMA 31", "medio", "La sedestación aproxima el estudio a las condiciones de una radiografía realizada en posición erecta y puede mejorar la representación de estructuras torácicas y de los niveles de líquido."],
  ["La sedestación, cuando es posible en una radiografía portátil de tórax, puede mejorar el estudio porque:", ["Elimina la necesidad de inspiración", "Favorece una representación más adecuada y evita ciertas diferencias morfológicas del decúbito", "Permite utilizar siempre menos colimación", "Hace innecesaria la distancia foco-paciente"], 1, "TEMA 31", "difícil", "La incorporación del paciente reduce algunas alteraciones producidas por el decúbito y proporciona una representación torácica más adecuada. No elimina la necesidad de una buena inspiración ni de una correcta geometría."],
  ["Para una radiografía portátil de tórax, se solicita una inspiración profunda principalmente para:", ["Reducir el tamaño del mediastino", "Conseguir una mayor expansión pulmonar", "Aumentar la magnificación cardíaca", "Visualizar mejor el colon"], 1, "TEMA 31", "medio", "Una inspiración adecuada aumenta la expansión pulmonar y permite valorar mejor el parénquima y las estructuras torácicas. La calidad del estudio depende también de la posición y de la técnica."],
  ["La distancia foco-paciente (DFP) recomendada para la radiografía portátil de tórax es aproximadamente:", ["50 cm", "100 cm", "150 cm", "180 cm"], 3, "TEMA 31", "difícil", "Una DFP de aproximadamente 180 cm ayuda a reducir la magnificación, especialmente la de la silueta cardíaca. En la práctica debe adaptarse a las posibilidades del paciente y del equipo."],
  ["La proyección más habitual en la radiografía portátil de abdomen es:", ["AP", "PA", "Lateral", "Oblicua"], 0, "TEMA 31", "medio", "En pacientes encamados, la proyección AP es la más práctica porque puede realizarse directamente en decúbito sin necesidad de trasladar al paciente."],
  ["La posición más habitual para la radiografía portátil de abdomen es:", ["Decúbito supino", "Bipedestación", "Decúbito prono", "Sedestación"], 0, "TEMA 31", "medio", "El abdomen portátil suele realizarse en decúbito supino, especialmente en pacientes hospitalizados o críticos que no pueden mantenerse de pie."],
  ["La adquisición de la radiografía portátil de abdomen se realiza habitualmente:", ["Al final de la inspiración", "Al final de la espiración", "Durante una inspiración máxima mantenida", "Independientemente del ciclo respiratorio"], 1, "TEMA 31", "difícil", "La adquisición al final de la espiración reduce el movimiento y proporciona una situación más estable del abdomen para la exposición."],
  ["En la radiografía portátil de abdomen, la flexión de las rodillas tiene como objetivo principal:", ["Aumentar la lordosis lumbar", "Relajar la musculatura abdominal", "Reducir la distancia foco-paciente", "Elevar el diafragma"], 1, "TEMA 31", "medio", "Flexionar las rodillas disminuye la tensión de la musculatura abdominal y facilita que el paciente mantenga una posición más cómoda y estable durante el estudio."],
  ["¿Por qué se recomienda colocar los brazos fuera del campo de irradiación en la radiografía portátil de abdomen?", ["Para aumentar la dosis", "Para evitar superposiciones sobre la imagen", "Para mejorar la inspiración", "Para reducir la distancia foco-paciente"], 1, "TEMA 31", "medio", "Los brazos dentro del campo pueden proyectarse sobre el abdomen y crear superposiciones que dificulten la interpretación. Siempre que sea posible deben quedar fuera del campo colimado."],
  ["En el estudio lateral de tórax, una adquisición en inspiración puede ser especialmente útil para valorar:", ["Derrame pleural", "Cálculos renales", "Fracturas de coxis", "Sacroilíacas"], 0, "TEMA 31", "difícil", "La proyección lateral en inspiración permite valorar mejor la distribución del líquido pleural y la anatomía de las bases pulmonares. El derrame puede apreciarse como una opacidad dependiente de la gravedad."],
  ["En el estudio de tórax, una proyección lateral en espiración puede ayudar especialmente a demostrar:", ["Derrame pleural", "Neumotórax", "Escoliosis", "Litiasis vesicular"], 1, "TEMA 31", "difícil", "En espiración disminuye el volumen pulmonar y el aire pleural puede hacerse más evidente, por lo que esta proyección puede ayudar a detectar un neumotórax pequeño."],
  ["En un paciente inmovilizado con sospecha de neumoperitoneo, una técnica complementaria adecuada es:", ["Abdomen AP con rayo horizontal", "Abdomen PA en bipedestación obligatoria", "Tórax AP exclusivamente", "Abdomen en inspiración profunda exclusivamente"], 0, "TEMA 31", "difícil", "Cuando el paciente no puede ponerse de pie, un rayo horizontal permite demostrar la acumulación de aire libre en zonas no dependientes, facilitando la detección de neumoperitoneo."],
  ["Durante una exploración portátil, la distancia mínima recomendada entre el técnico y el paciente durante la exposición es de aproximadamente:", ["50 cm", "1 m", "2 m", "5 m"], 2, "TEMA 31", "medio", "Aumentar la distancia respecto al paciente reduce la exposición del técnico a la radiación dispersa. Aproximadamente 2 m es una referencia práctica cuando las condiciones lo permiten."],
  ["Antes de realizar una exposición portátil, una medida de protección fundamental es:", ["Avisar verbalmente antes del disparo", "Avisar solo después de la exposición", "Aumentar el campo irradiado", "Mantener al personal innecesario dentro de la habitación"], 0, "TEMA 31", "medio", "Avisar antes de la exposición permite que el personal presente abandone la zona o adopte la protección necesaria y evita exposiciones innecesarias."],
  ["Respecto al personal presente durante una exposición portátil, la actuación correcta es:", ["Mantener a todo el personal en la sala", "Hacer que abandone la sala cuando sea posible o permanezca adecuadamente protegido si es imprescindible", "Situarlo junto al tubo", "Colocarlo siempre detrás del detector sin protección"], 1, "TEMA 31", "difícil", "La prioridad es reducir el número de personas expuestas. Quien deba permanecer debe situarse adecuadamente y utilizar las medidas de protección disponibles, manteniendo la máxima distancia razonable."],
  ["La colimación en radiología portátil debe utilizarse para:", ["Irradiar un campo lo más amplio posible", "Limitar el campo al mínimo necesario para el estudio", "Aumentar la radiación dispersa", "Compensar una mala posición del paciente"], 1, "TEMA 31", "medio", "Colimar limita el volumen irradiado al área necesaria para responder a la indicación clínica. Esto reduce la dosis al paciente y también la radiación dispersa en el entorno."],
  ["Para reducir la dosis en fluoroscopia, ¿qué combinación es más adecuada?", ["Aumentar el tiempo de escopia y usar fluoroscopia continua", "Reducir el tiempo de escopia y utilizar fluoroscopia pulsada", "Aumentar la magnificación electrónica y el tiempo", "Mantener siempre el intensificador alejado del paciente"], 1, "TEMA 31", "difícil", "La protección radiológica en fluoroscopia se basa en minimizar el tiempo de exposición y utilizar modos de baja dosis, como la fluoroscopia pulsada cuando sea adecuada para el procedimiento."],
  ["Durante la utilización del arco en C, para optimizar la protección radiológica se recomienda colocar el intensificador:", ["Lo más alejado posible del paciente", "Lo más próximo posible al paciente", "Siempre fuera del quirófano", "A la altura de la cabeza del técnico"], 1, "TEMA 31", "difícil", "Mantener el receptor de imagen próximo al paciente permite trabajar con una geometría más favorable y reduce la necesidad de aumentar la exposición. También ayuda a disminuir la magnificación."],
  ["En la disposición habitual del arco en C, el tubo de rayos X debe situarse preferentemente:", ["Por encima del paciente", "Por debajo del paciente", "Siempre lateral al paciente", "Siempre detrás del cirujano"], 1, "TEMA 31", "difícil", "Colocar el tubo debajo de la mesa reduce la exposición del personal a la radiación dispersa, ya que la mayor parte de la dispersión se produce hacia el lado de entrada del haz, donde está el paciente."],
  ["Cuando se realizan proyecciones oblicuas con fluoroscopia, una medida de protección adecuada es:", ["Acercarse al tubo", "Aumentar la distancia respecto al tubo", "Eliminar el delantal plomado", "Aumentar el tiempo de exposición"], 1, "TEMA 31", "difícil", "La radiación dispersa disminuye rápidamente al aumentar la distancia respecto a la fuente. Por eso, durante las proyecciones oblicuas conviene alejarse del tubo siempre que sea posible."],
  ["Durante una exposición radiológica, el técnico debe:", ["Manipular el equipo si es necesario para ganar tiempo", "Evitar manipular al paciente o el equipo durante la exposición", "Permanecer junto al tubo", "Aumentar el campo para no repetir"], 1, "TEMA 31", "medio", "Durante el disparo el técnico debe mantenerse fuera de la zona de exposición y evitar manipular al paciente o el equipo. La preparación correcta antes de la exposición reduce la necesidad de intervenir durante ella."],
  ["En quirófano, una actuación correcta del técnico de radiología es:", ["Invadir el campo estéril para colocar el arco en C", "Evitar contaminar el campo estéril y utilizar la protección radiológica correspondiente", "Retirar la ropa quirúrgica para trabajar con mayor comodidad", "Colocar el monitor donde no pueda verlo el cirujano"], 1, "TEMA 31", "difícil", "El técnico debe coordinarse con el equipo quirúrgico para mover y colocar el arco en C sin contaminar el campo estéril. Además, debe aplicar las medidas de protección radiológica durante toda la intervención."],
  ["Durante una intervención con arco en C, ¿qué conjunto de medidas ofrece una mejor protección radiológica?", ["Intensificador alejado, tubo arriba, fluoroscopia continua y muchas imágenes", "Intensificador próximo, tubo debajo del paciente, fluoroscopia pulsada, tiempo mínimo y número mínimo de imágenes", "Magnificación electrónica máxima y campo abierto", "Tubo próximo al personal y exposición prolongada"], 1, "TEMA 31", "difícil", "La protección óptima combina una geometría favorable con la reducción de la exposición: receptor próximo al paciente, tubo por debajo, fluoroscopia pulsada cuando sea posible, tiempo mínimo y el menor número de imágenes necesario para el procedimiento."]
];

window.topic31Curated = topic31Curated;

const previousTopicMenu31 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu31();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 31'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 31</span><h3>${esc((topics[31]||{}).title||'TEMA 31')}</h3><p>${topic31Curated.length} preguntas · portátil, UCI y quirófano</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 31', topic31Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 31</span><h3>${esc((topics[31]||{}).title||'TEMA 31')}</h3><p>${topic31Curated.length} preguntas · portátil, UCI y quirófano</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 31', topic31Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 31; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};
