// Banco curado del TEMA 16.
const topic16Curated = [
["¿Cuál es una característica fundamental que debe cumplir el carro de paros?",["Estar ubicado en una zona de acceso restringido.","Permanecer accesible, con el contenido visible y ordenado.","Utilizarse únicamente durante procedimientos quirúrgicos.","Contener exclusivamente material farmacológico."],1,"TEMA 16","medio","El carro de paros debe estar accesible y preparado para una actuación rápida. Mantener el material visible, ordenado y disponible facilita la respuesta ante una emergencia."],
["¿Con qué finalidad debe realizarse una revisión periódica del carro de paros?",["Para sustituir todos los medicamentos después de cada revisión.","Para comprobar que su contenido está preparado para atender una parada cardiorrespiratoria.","Para reducir el material disponible en el carro.","Para comprobar únicamente el funcionamiento del desfibrilador."],1,"TEMA 16","medio","La revisión periódica permite comprobar que el material y la medicación necesarios están disponibles, en condiciones adecuadas y preparados para responder ante una parada cardiorrespiratoria."],
["¿Cuál de los siguientes elementos forma parte de la dotación básica del carro de paros?",["Pulsioxímetro.","Equipo de resonancia magnética.","Inyector automático de contraste.","Ecógrafo."],0,"TEMA 16","medio","El pulsioxímetro permite controlar la saturación de oxígeno y forma parte del material básico de valoración del paciente en una emergencia. Los otros equipos no son elementos propios del carro de paros."],
["¿Cuál de los siguientes grupos corresponde a fármacos incluidos en la dotación básica del carro de paros?",["Adrenalina, atropina y salbutamol.","Furosemida, secretina y gadolinio.","Midazolam, diazepam y lidocaína.","Nitroglicerina, dobutamina y adenosina."],0,"TEMA 16","medio","La adrenalina, la atropina y el salbutamol son fármacos que pueden formar parte de la dotación básica para atender distintas situaciones de emergencia. Gadolinio y secretina, por ejemplo, son fármacos utilizados con finalidades diagnósticas específicas."],
["¿Cuál de los siguientes elementos permite valorar la saturación de oxígeno del paciente?",["Electrocardiógrafo.","Pulsioxímetro.","Desfibrilador.","Monitor de presión arterial."],1,"TEMA 16","fácil","El pulsioxímetro mide de forma no invasiva la saturación periférica de oxígeno de la hemoglobina. El electrocardiógrafo registra la actividad eléctrica cardíaca y el monitor de presión arterial mide la presión arterial."],
["Antes de realizar un estudio radiodiagnóstico, especialmente una resonancia magnética, es importante:",["Evitar explicar al paciente las características de la prueba.","Proporcionar información y apoyo psicológico y, cuando sea necesario, farmacológico.","Administrar siempre un anestésico general.","Administrar siempre un opioide."],1,"TEMA 16","medio","Explicar la prueba y ofrecer apoyo ayuda a reducir la ansiedad y facilita la colaboración del paciente. En determinados casos puede ser necesario recurrir a medicación para controlar la ansiedad o facilitar la exploración, pero no se administra siempre anestesia general ni opioides."],
["¿Cuál de los siguientes fármacos pertenece al grupo de las benzodiacepinas utilizadas para sedación?",["Fentanilo.","Midazolam.","Lidocaína.","Furosemida."],1,"TEMA 16","fácil","El midazolam es una benzodiacepina con efecto sedante y ansiolítico. El fentanilo es un opioide, la lidocaína es un anestésico local y la furosemida es un diurético."],
["¿Cuál de los siguientes es un anestésico local utilizado en radiología?",["Bupivacaína.","Morfina.","Midazolam.","Salbutamol."],0,"TEMA 16","fácil","La bupivacaína es un anestésico local que bloquea la conducción nerviosa en la zona donde se administra. La morfina es un opioide, el midazolam una benzodiacepina y el salbutamol un broncodilatador."],
["En una cardio-RM de estrés, ¿cuál es la finalidad del estrés farmacológico?",["Disminuir la frecuencia cardíaca hasta valores mínimos.","Evaluar la respuesta del corazón ante el estrés inducido farmacológicamente.","Conseguir la relajación de la musculatura intestinal.","Aumentar la producción de orina."],1,"TEMA 16","medio","El estrés farmacológico reproduce una situación de demanda cardíaca aumentada o modifica el flujo coronario para estudiar la respuesta del miocardio. La RM permite valorar los cambios funcionales y, según el protocolo, la perfusión y la contractilidad."],
["¿Qué efecto producen el dipiridamol y la adenosina utilizados en la cardio-RM de estrés?",["Vasoconstricción coronaria y aumento de la presión arterial.","Vasodilatación coronaria e inducción de isquemia miocárdica relativa.","Disminución de la contractilidad y de la frecuencia cardíaca.","Aumento de la producción de orina."],1,"TEMA 16","medio","La adenosina y el dipiridamol producen vasodilatación coronaria. Esto aumenta mucho el flujo en los territorios sanos y puede poner de manifiesto una diferencia de perfusión respecto a zonas irrigadas por arterias con enfermedad, generando una isquemia relativa."],
["¿Cuál de las siguientes situaciones constituye una contraindicación para el uso de dipiridamol o adenosina en una cardio-RM de estrés?",["Taquicardia sinusal.","Bloqueo auriculoventricular de segundo o tercer grado.","Hipertensión arterial leve.","Aumento de la contractilidad miocárdica."],1,"TEMA 16","difícil","La adenosina y el dipiridamol pueden alterar la conducción cardíaca. Por ello, los bloqueos auriculoventriculares de segundo o tercer grado constituyen una contraindicación importante para este tipo de estrés farmacológico."],
["¿Qué efecto produce la dobutamina durante una cardio-RM de estrés?",["Disminuye la contractilidad miocárdica.","Aumenta la contractilidad miocárdica y la frecuencia cardíaca.","Produce relajación de la musculatura intestinal.","Produce vasodilatación coronaria sin modificar la frecuencia cardíaca."],1,"TEMA 16","medio","La dobutamina es un fármaco inotrópico y cronotrópico que aumenta la contractilidad y la frecuencia cardíaca. De este modo incrementa la demanda de oxígeno del miocardio y permite estudiar su respuesta al estrés."],
["Durante una cardio-RM de estrés con dobutamina, ¿qué se valora mediante las secuencias de cine?",["La eliminación renal del fármaco.","La contractilidad segmentaria del corazón.","La distensión de la vía urinaria.","La motilidad intestinal."],1,"TEMA 16","medio","Las secuencias de cine permiten observar el movimiento de las paredes cardíacas durante el ciclo cardíaco. Con dobutamina se presta especial atención a la aparición de alteraciones de la contractilidad segmentaria inducidas por el estrés."],
["Para realizar una angio-TAC de las arterias coronarias, ¿por qué puede ser necesario administrar betabloqueantes?",["Para aumentar la frecuencia cardíaca por encima de 100 lpm.","Para conseguir una frecuencia cardíaca adecuada para la adquisición.","Para producir diuresis.","Para relajar el intestino."],1,"TEMA 16","medio","Los betabloqueantes reducen la frecuencia cardíaca y ayudan a conseguir un ritmo adecuado para adquirir las imágenes coronarias con menor movimiento cardíaco. Esto mejora la calidad de la angio-TAC."],
["¿Qué efecto se busca conseguir mediante la administración de nitroglicerina sublingual antes de una angio-TAC coronaria?",["Vasodilatación de las arterias coronarias.","Vasoconstricción de las arterias coronarias.","Disminución de la producción de orina.","Aumento de la contractilidad cardíaca."],0,"TEMA 16","medio","La nitroglicerina produce vasodilatación, incluida la dilatación de las arterias coronarias. Administrada antes de la angio-TAC puede favorecer la visualización de la luz coronaria."],
["¿Cuál es la finalidad de administrar furosemida en determinados estudios del aparato urinario?",["Disminuir la producción de orina.","Aumentar la producción de orina y favorecer la distensión de la vía urinaria.","Relajar la musculatura del intestino.","Aumentar la frecuencia cardíaca."],1,"TEMA 16","medio","La furosemida es un diurético que aumenta la producción de orina. En determinados estudios urinarios se utiliza para incrementar el flujo urinario y favorecer la distensión de las estructuras que se quieren estudiar."],
["¿Para qué se utilizan los fármacos antiperistálticos en los estudios del aparato digestivo?",["Para aumentar el movimiento intestinal.","Para relajar la musculatura lisa del esófago, estómago e intestino.","Para aumentar la secreción pancreática.","Para favorecer la producción de orina."],1,"TEMA 16","medio","Los antiperistálticos disminuyen temporalmente los movimientos de la musculatura lisa digestiva. Al reducir el movimiento intestinal se pueden obtener imágenes con menos artefactos y mejorar la valoración de las estructuras."],
["¿En qué tipo de estudios pueden utilizarse fármacos antiperistálticos?",["Únicamente en resonancia magnética cerebral.","En estudios baritados y en entero-RM.","Exclusivamente en estudios urológicos.","Únicamente en angio-TAC coronaria."],1,"TEMA 16","medio","Los antiperistálticos pueden emplearse en estudios digestivos en los que el movimiento intestinal dificulta la obtención de imágenes, como determinados estudios baritados y la entero-RM."],
["¿Cuál es la finalidad de utilizar secretina en determinados estudios de RM?",["Evaluar la respuesta secretora del páncreas y cuantificar su reserva exocrina.","Aumentar la producción de orina.","Disminuir la contractilidad cardíaca.","Eliminar restos fecales del colon."],0,"TEMA 16","difícil","La secretina estimula la secreción pancreática rica en bicarbonato. En determinados estudios de RM permite valorar la respuesta secretora del páncreas y estudiar su función exocrina."],
["¿Para qué se utilizan los laxantes antes de determinados estudios digestivos?",["Para aumentar la secreción exocrina pancreática.","Para eliminar restos fecales y mejorar la visualización de las paredes intestinales.","Para producir vasodilatación coronaria.","Para aumentar la frecuencia cardíaca."],1,"TEMA 16","medio","La limpieza intestinal reduce la cantidad de contenido fecal que puede ocultar o dificultar la valoración de la pared intestinal. Por eso los laxantes pueden formar parte de la preparación previa de determinados estudios digestivos."]
];
window.topic16Curated = topic16Curated;

// El Tema 16 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank16 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank16().filter(q=>q[3]!=='TEMA 16'); };
