const topic9Curated = [
  ['¿Cuál es una de las principales ventajas de la radiografía digital respecto a la radiografía convencional?',['Elimina completamente el ruido de la imagen','Permite reducir la dosis manteniendo una adecuada calidad diagnóstica','Evita la necesidad de procesar las imágenes','Impide que las imágenes sean modificadas posteriormente'],1,'TEMA 9','fácil','La radiografía digital ofrece un amplio margen de exposición y permite optimizar los parámetros técnicos, pudiendo mantener una calidad diagnóstica adecuada con una dosis ajustada.'],
  ['¿Qué característica del detector digital hace referencia a su capacidad para registrar un amplio intervalo de exposiciones?',['Resolución espacial','Eficiencia de detección cuántica','Rango dinámico','Tamaño del píxel'],2,'TEMA 9','fácil','El rango dinámico es la capacidad del detector para registrar un amplio intervalo de exposiciones y producir información útil dentro de ese intervalo.'],
  ['En radiografía digital, ¿qué representa la curva característica del detector?',['La relación entre el tamaño del píxel y la resolución espacial','La relación entre la radiación que llega al detector y la señal obtenida','La relación entre el contraste y el ruido','La relación entre la dosis al paciente y el tiempo de exposición'],1,'TEMA 9','medio','La curva característica relaciona la exposición recibida por el detector con la señal que genera, describiendo su respuesta frente a la radiación incidente.'],
  ['¿Qué factor resulta fundamental para mejorar la visibilidad de una estructura en una imagen digital y depende de las características del detector?',['El tamaño de la estructura','El contraste propio de la estructura','El ruido de la imagen','La densidad anatómica'],2,'TEMA 9','medio','El ruido limita la visibilidad de estructuras, especialmente cuando presentan poco contraste. Reducirlo mejora la relación señal-ruido y facilita su detección.'],
  ['Respecto a la DQE de un detector digital, ¿cuál de las siguientes afirmaciones es correcta?',['Evalúa únicamente la resolución espacial','Relaciona la señal obtenida con la eficiencia del detector para conservar información frente al ruido','Aumenta siempre al disminuir el tamaño del píxel','No depende de la tecnología de construcción del detector'],1,'TEMA 9','difícil','La DQE (eficiencia cuántica de detección) indica qué eficacia tiene el detector para transformar la radiación incidente en información útil, teniendo en cuenta el ruido.'],
  ['¿Qué ocurre, en general, al disminuir el tamaño del píxel de un detector digital?',['Disminuye la resolución espacial','Aumenta la resolución espacial, pero puede disminuir la DQE y aumentar el ruido','Aumenta siempre la DQE','Desaparece el ruido de la imagen'],1,'TEMA 9','medio','Un píxel más pequeño permite representar detalles más pequeños y aumenta la resolución espacial, pero puede reducir la eficiencia de detección y favorecer un mayor ruido.'],
  ['¿Cuál es el objetivo de separar la adquisición y la presentación de la imagen en radiografía digital?',['Evitar cualquier modificación posterior de la imagen','Permitir optimizar de forma independiente la adquisición y la presentación','Eliminar la necesidad de utilizar detectores digitales','Conseguir que todas las imágenes tengan el mismo contraste'],1,'TEMA 9','fácil','La adquisición registra la información procedente del detector y el procesamiento de presentación permite adaptar cómo se muestra. Separarlas permite optimizar ambas etapas de forma independiente.'],
  ['¿Cuál es la secuencia correcta del procesamiento básico de una imagen digital?',['DICOM de presentación → imagen adquirida → DICOM bruto','Imagen adquirida → DICOM bruto → DICOM para presentación','DICOM bruto → imagen adquirida → DICOM de presentación','Imagen adquirida → DICOM de presentación → DICOM bruto'],1,'TEMA 9','fácil','Primero se adquiere la imagen, después se genera la información digital en bruto y finalmente se procesa para obtener la imagen preparada para presentación.'],
  ['¿Qué caracteriza a la imagen DICOM para presentación?',['Es la señal sin ningún tipo de corrección','Es la imagen final procesada preparada para su visualización y archivo','Es exclusivamente la información procedente del detector antes de las correcciones','Es una copia de seguridad de la imagen adquirida'],1,'TEMA 9','fácil','La imagen DICOM de presentación contiene la imagen ya procesada para poder visualizarla y gestionarla dentro del entorno digital.'],
  ['En el ajuste de ventana, ¿qué parámetro determina principalmente el tipo de tejido que se visualiza?',['El ancho','El nivel','El tamaño del píxel','La DQE'],1,'TEMA 9','fácil','El nivel o centro de ventana determina qué rango de valores de atenuación se sitúa alrededor de la zona de visualización y, por tanto, qué tejidos se muestran adecuadamente.'],
  ['¿Qué efecto produce una ventana estrecha?',['Mayor número de tonos de gris y menor contraste','Menor número de tonos de gris y mayor contraste','Mayor ruido y menor contraste','Menor resolución espacial'],1,'TEMA 9','fácil','Una ventana estrecha concentra menos valores en la escala de grises, aumentando el contraste entre estructuras cuyos valores están dentro del intervalo seleccionado.'],
  ['¿Qué efecto produce una ventana amplia?',['Mayor contraste entre estructuras','Menor número de tonos de gris','Mayor número de tonos de gris y menor contraste','Visualización exclusiva de estructuras óseas'],2,'TEMA 9','fácil','Una ventana amplia incluye un intervalo mayor de valores en la escala de grises. Esto permite representar más tonos, pero reduce el contraste entre estructuras próximas.'],
  ['¿Qué tipo de nivel de ventana se utiliza principalmente para visualizar estructuras de baja densidad, como el aire o la grasa?',['Nivel alto','Nivel intermedio','Nivel bajo','Nivel máximo'],2,'TEMA 9','medio','Las estructuras de baja densidad presentan valores de atenuación bajos, por lo que se utilizan niveles de ventana bajos para visualizarlas correctamente.'],
  ['¿Qué consecuencia puede tener la corrección de una imagen obtenida con sobreexposición?',['Eliminación completa del ruido','Aparición de una imagen con mayor ruido del habitual','Disminución automática de la dosis administrada al paciente','Aumento de la resolución espacial del detector'],1,'TEMA 9','medio','El procesamiento puede compensar visualmente una exposición excesiva, pero no recupera la información que se ha perdido por saturación y puede dejar una imagen con más ruido cuando la señal útil es insuficiente en determinadas zonas.'],
  ['¿Cuál es el objetivo de la ecualización tisular?',['Aplicar el mismo procesamiento a toda la imagen','Diferenciar tejidos de distintas densidades dentro de una misma imagen mediante procesamientos adaptados a cada zona','Eliminar completamente el ruido','Aumentar exclusivamente la resolución espacial'],1,'TEMA 9','medio','La ecualización tisular adapta el procesamiento a diferentes regiones de la imagen para mejorar la representación de tejidos con distintas densidades dentro de una misma exploración.'],
  ['¿Cuál es la principal utilidad del realce de bordes?',['Reducir el contraste entre estructuras','Mejorar la visualización de las interfaces entre estructuras con diferente atenuación','Eliminar el ruido de la imagen','Disminuir el rango dinámico del detector'],1,'TEMA 9','fácil','El realce de bordes aumenta la diferencia visual en las transiciones entre estructuras, haciendo más evidentes sus límites.'],
  ['¿Qué efecto secundario puede producir el realce de bordes?',['Disminución de la resolución espacial','Aumento del ruido','Eliminación de estructuras de alto contraste','Reducción del rango dinámico'],1,'TEMA 9','fácil','El realce de bordes también puede reforzar las variaciones aleatorias de la imagen, por lo que un procesamiento excesivo puede aumentar la percepción del ruido.'],
  ['¿Por qué el procesamiento específico de mamografía debe ser especialmente cuidadoso?',['Porque la mama presenta exclusivamente estructuras óseas','Porque las diferencias de densidad entre los tejidos mamarios pueden ser muy pequeñas','Porque no puede utilizarse procesamiento digital','Porque la mamografía carece de contraste entre tejidos'],1,'TEMA 9','medio','En mamografía interesa detectar diferencias sutiles entre tejidos y pequeñas lesiones. Por eso el procesamiento debe preservar y hacer visibles esas diferencias sin introducir artefactos.'],
  ['¿En qué principio físico se basa la energía dual?',['La atenuación de los tejidos es independiente de la energía de los fotones','La atenuación de los tejidos varía en función de la energía de los fotones','Los fotones de cualquier energía producen siempre el mismo efecto','La imagen digital no depende de la energía utilizada'],1,'TEMA 9','medio','La atenuación de los materiales depende de la energía de los fotones. Al adquirir información con diferentes energías pueden aprovecharse esas diferencias para separar materiales.'],
  ['A energías elevadas, ¿qué interacción adquiere mayor importancia y produce menor diferencia de atenuación entre determinados tejidos?',['Efecto fotoeléctrico','Efecto Compton','Fluorescencia','Resonancia'],1,'TEMA 9','medio','A energías más elevadas aumenta la importancia relativa del efecto Compton. Su dependencia respecto al número atómico es menor que la del efecto fotoeléctrico, por lo que disminuyen determinadas diferencias de atenuación entre tejidos.'],
  ['En un sistema de energía dual de doble disparo, ¿qué función tiene el filtro de cobre situado entre los dos receptores?',['Aumentar la dosis administrada al paciente','Modificar el espectro de radiación que llega al segundo receptor','Eliminar completamente la radiación dispersa','Aumentar el tamaño del píxel'],1,'TEMA 9','difícil','El filtro de cobre modifica el espectro del haz antes de que llegue al segundo receptor, de modo que este recibe una radiación diferente y se obtiene información a otra energía efectiva.'],
  ['En la energía dual de doble disparo, ¿qué permite obtener el procesamiento de las imágenes adquiridas con diferentes energías?',['Únicamente una imagen convencional','Una imagen convencional y diferentes imágenes procesadas para resaltar determinadas estructuras','Una única imagen sin posibilidad de procesamiento','Exclusivamente una imagen ósea'],1,'TEMA 9','medio','La combinación de las adquisiciones a distintas energías permite generar una imagen convencional y procesamientos específicos que pueden resaltar o separar determinados materiales.'],
  ['En mamografía con energía dual y contraste yodado, ¿qué permite identificar principalmente la combinación de las imágenes obtenidas?',['Únicamente el tejido adiposo','Las zonas de captación del contraste yodado','Exclusivamente las calcificaciones','Solo las estructuras musculares'],1,'TEMA 9','medio','Al combinar las imágenes de baja y alta energía se puede realizar una imagen específica que muestra las zonas donde se ha concentrado el yodo administrado.'],
  ['¿Qué característica define a la tomosíntesis?',['Obtiene una única imagen plana con mayor contraste','Obtiene múltiples proyecciones desde distintos ángulos para reconstruir imágenes en diferentes planos','Utiliza exclusivamente una proyección lateral','Sustituye siempre a la radiografía convencional'],1,'TEMA 9','fácil','La tomosíntesis adquiere múltiples proyecciones de la mama desde distintos ángulos y utiliza esas proyecciones para reconstruir imágenes por planos.'],
  ['¿Cuál es una de las principales ventajas de la tomosíntesis?',['Elimina completamente la radiación dispersa','Permite separar estructuras superpuestas y mejorar su visualización','Reduce siempre la dosis respecto a cualquier técnica convencional','Solo permite estudiar estructuras óseas'],1,'TEMA 9','fácil','Al disponer de imágenes reconstruidas por planos, la tomosíntesis reduce el efecto de la superposición de tejidos y facilita la visualización de determinadas estructuras y lesiones.']
];

window.topic9Curated = topic9Curated;
