const topic40Questions = [
  {q:"¿Cuál de las siguientes afirmaciones sobre la ecografía de la pelvis femenina es correcta?", options:["Utiliza radiación ionizante y requiere contraste intravenoso.","Es una técnica invasiva cuya principal utilidad es el estudio ovárico.","Es una modalidad ampliamente disponible, no utiliza radiación y proporciona información diagnóstica útil.","Su principal limitación es que no permite obtener imágenes en tiempo real."], answer:2},
  {q:"En una mujer en edad fértil, el tamaño aproximado habitual de los ovarios es:", options:["1 × 1 × 1 cm","2 × 1 × 1 cm","3 × 2 × 2 cm","5 × 4 × 3 cm"], answer:2},
  {q:"Una paciente presenta un ovario difícil de localizar por su posición. ¿Cuál es la referencia anatómica más útil para su localización ecográfica?", options:["El borde externo de los músculos iliopsoas.","El borde interno de los vasos ilíacos.","El fondo vesical.","El borde externo del recto."], answer:1},
  {q:"¿Cuál es la secuencia correcta de desarrollo folicular?", options:["Primordial → secundario → primario → De Graaf.","Primario → primordial → secundario → De Graaf.","Primordial → primario → secundario → maduro o de De Graaf.","Primordial → De Graaf → primario → secundario."], answer:2},
  {q:"¿Cuál de los siguientes segmentos de la trompa de Falopio corresponde a la porción central y más larga?", options:["Intersticial.","Ístmico.","Ampular.","Infundibular."], answer:2},
  {q:"Respecto a la zona fímbrica de la trompa de Falopio, señale la afirmación correcta:", options:["Es el segmento muscular más estrecho próximo al útero.","Corresponde al extremo distal del infundíbulo y presenta prolongaciones que rodean parte del ovario.","Atraviesa el músculo uterino antes de alcanzar la cavidad endometrial.","Es la zona donde se produce exclusivamente la implantación."], answer:1},
  {q:"¿Cuál de las siguientes NO corresponde a una de las cuatro partes descritas del útero?", options:["Fondo.","Cuerpo.","Istmo.","Ligamento ancho."], answer:3},
  {q:"¿Qué capa uterina es la más externa y forma lateralmente los ligamentos anchos?", options:["Endometrio.","Miometrio.","Perimetrio.","Estrato basal."], answer:2},
  {q:"Durante la menstruación, ¿qué parte del endometrio se descama?", options:["Exclusivamente el estrato basal.","La capa funcional formada por los estratos compacto y esponjoso.","Todo el miometrio.","Únicamente el estrato compacto."], answer:1},
  {q:"¿Cuál de las siguientes asociaciones entre fase del ciclo y aspecto ecográfico endometrial es correcta?", options:["Semana 1 → aumento máximo del espesor endometrial.","Semana 2 → banda hipoecogénica alrededor de la línea cavitaria.","Semanas 3–4 → desaparición completa de la línea cavitaria.","Fase menstrual → banda hiperecogénica rodeada de halo hipoecogénico."], answer:1},
  {q:"Durante las semanas 3–4 del ciclo, en la fase secretora:", options:["Disminuye el espesor endometrial y desaparece la línea cavitaria.","Aumenta el espesor endometrial y la línea cavitaria queda rodeada por una banda hiperecogénica y un halo hipoecogénico.","El endometrio apenas es visible.","Aparece exclusivamente una banda hipoecogénica."], answer:1},
  {q:"¿Cuál de las siguientes NO constituye una indicación de la ecografía pélvica?", options:["Sangrado posmenopáusico.","Localización de dispositivos intrauterinos.","Incontinencia o prolapso.","Necesidad de utilizar radiación ionizante para valorar la pelvis."], answer:3},
  {q:"Antes de iniciar una exploración ecográfica ginecológica, la anamnesis es especialmente importante porque:", options:["Permite prescindir de la exploración ecográfica.","Tiene valor orientativo y es indispensable para interpretar correctamente las imágenes.","Solo es necesaria en pacientes posmenopáusicas.","Sustituye al estudio Doppler."], answer:1},
  {q:"Para la ecografía transabdominal de la pelvis femenina, la preparación vesical adecuada consiste en:", options:["Vejiga completamente vacía.","Buena repleción vesical.","Vejiga vacía salvo en mujeres posmenopáusicas.","Repleción exclusivamente mediante contraste ecográfico."], answer:1},
  {q:"En la exploración transabdominal, la vejiga llena resulta especialmente útil porque:", options:["Impide visualizar el útero.","Actúa como ventana acústica para el estudio pélvico.","Elimina las asas intestinales de forma permanente.","Permite visualizar directamente las trompas normales."], answer:1},
  {q:"En una ecografía transabdominal, ¿cuál es la secuencia inicial de exploración descrita?", options:["Plano axial sobre el ovario derecho y posteriormente plano sagital.","Plano sagital sobre el eje uterovaginal y posteriormente barrido transversal para localizar los anejos.","Plano coronal sobre la vejiga seguido de Doppler.","Plano transversal sobre el cuello uterino seguido de exploración rectal."], answer:1},
  {q:"En la ecografía transvaginal, la preparación vesical recomendada es:", options:["Vejiga muy llena para crear una ventana acústica.","Vejiga vacía o con poca cantidad de orina.","Llenado vesical mediante sondaje.","No existe ninguna recomendación respecto a la vejiga."], answer:1},
  {q:"¿Cuál de las siguientes características corresponde a la sonda utilizada en la ecografía transvaginal?", options:["Sonda convexa de baja frecuencia exclusivamente.","Sonda endocavitaria de alta frecuencia con extremo convexo y ángulo variable.","Sonda sectorial de alta frecuencia exclusivamente.","Sonda lineal superficial de 3–5 MHz."], answer:1},
  {q:"Durante la ecografía transvaginal, en el plano sagital:", options:["El fondo uterino aparece a la derecha y el cuello a la izquierda de la pantalla.","El fondo uterino aparece a la izquierda y el cuello a la derecha.","Ambos aparecen siempre en el centro de la pantalla.","El cuello uterino no puede identificarse."], answer:1},
  {q:"En el plano axial de una ecografía transvaginal, debido a la orientación de la imagen:", options:["El ovario derecho aparece en el sector derecho de la pantalla.","El ovario izquierdo aparece siempre en el sector derecho.","El ovario derecho puede verse en el sector izquierdo de la pantalla y viceversa.","La lateralidad ovárica no puede determinarse."], answer:2},
  {q:"La sonohisterografía consiste en:", options:["Estudiar exclusivamente las trompas mediante contraste yodado.","Estudiar la cavidad uterina mediante ecografía transvaginal mientras se introduce suero salino mediante un catéter balón.","Estudiar los ovarios después de llenar la vejiga.","Valorar el útero mediante radiología convencional."], answer:1},
  {q:"Una de las principales utilidades de la sonohisterografía es:", options:["Diferenciar un quiste folicular de un endometrioma.","Diferenciar miomas submucosos de pólipos pediculados.","Diagnosticar exclusivamente la torsión ovárica.","Valorar el flujo de las arterias uterinas."], answer:1},
  {q:"¿Cuál de las siguientes situaciones constituye una contraindicación de la sonohisterografía?", options:["Infertilidad.","Sangrado vaginal.","Posibilidad de embarazo.","Sospecha de adherencias."], answer:2},
  {q:"Durante una sonohisterografía, una vez colocado el catéter en la cavidad endometrial:", options:["Se infla el balón con aproximadamente 2 mL de suero salino y posteriormente se administra lentamente el suero.","Se infla el balón con 20 mL de contraste yodado.","Se introduce inmediatamente aire a presión.","Se vacía completamente la cavidad uterina antes de introducir la sonda."], answer:0},
  {q:"La sonohisterosalpingografía se diferencia de la sonohisterografía fundamentalmente porque:", options:["Utiliza radiación ionizante.","Utiliza contraste ecográfico para valorar la permeabilidad tubárica.","Se realiza exclusivamente por vía transrectal.","No permite estudiar las trompas."], answer:1},
  {q:"¿Cuándo puede resultar especialmente útil la ecografía transrectal en la pelvis femenina?", options:["Como primera elección obligatoria en todas las pacientes.","En mujeres vírgenes o cuando la vía vaginal no es posible, y como guía para determinados procedimientos intervencionistas.","Únicamente para estudiar el endometrio durante la menstruación.","Solo cuando la vejiga está completamente llena."], answer:1},
  {q:"Respecto a la posición uterina, señale la afirmación correcta:", options:["La retroversión siempre indica patología.","La lateroversión siempre indica una masa pélvica.","La anteversión es frecuente y la retroversión o lateroversión pueden ser variantes no patológicas.","La posición uterina es independiente de la repleción vesical y rectal."], answer:2},
  {q:"La línea endometrial normal se describe como:", options:["Una banda gruesa hiperecogénica que siempre corresponde a tejido sólido.","Un fino trazo ecogénico central que representa la interfase entre las dos capas endometriales adheridas.","Una estructura anecoica permanente que representa la cavidad uterina llena de líquido.","Una estructura exclusivamente visible mediante Doppler."], answer:1},
  {q:"Respecto a los ovarios normales, señale la opción correcta:", options:["Son siempre homogéneamente anecoicos.","La corteza periférica puede ser menos ecogénica y la médula central más ecogénica.","La médula es siempre menos ecogénica que la corteza.","Los folículos periféricos son necesariamente lesiones patológicas."], answer:1},
  {q:"Una mujer en la mitad de su ciclo presenta pequeños quistes foliculares periféricos de aproximadamente 2–2,5 cm. ¿Cuál es la interpretación más adecuada?", options:["Son necesariamente quistes ováricos patológicos.","Son compatibles con cambios foliculares que pueden considerarse fisiológicos.","Son diagnósticos de ovario poliquístico.","Son característicos de un cistoadenocarcinoma."], answer:1},
  {q:"¿Cuál de las siguientes características orienta hacia un quiste folicular?", options:["Lesión anecogénica periférica, de paredes lisas y generalmente menor de 3 cm.","Lesión sólida con vascularización interna.","Lesión compleja con nódulos murales vascularizados.","Lesión bilateral con puentes hiperecogénicos centrales."], answer:0},
  {q:"Una paciente presenta una lesión ovárica dolorosa a mitad de ciclo, con patrón interno reticular y sin flujo interno. Si se rompe, puede producir hemoperitoneo. ¿Cuál es la lesión más probable?", options:["Quiste paraovárico.","Quiste hemorrágico.","Cistoadenoma seroso.","Quiste folicular simple."], answer:1},
  {q:"¿Cuál de las siguientes características favorece el diagnóstico de ovarios poliquísticos?", options:["Un único quiste ovárico que desaparece tras dos ciclos.","Múltiples microquistes periféricos, aumento del volumen ovárico y puentes hiperecogénicos centrales.","Una lesión parauterina independiente del ovario.","Una lesión quística con nódulos murales vascularizados."], answer:1},
  {q:"Una lesión quística parauterina se encuentra próxima a un ovario normal, localizada en el seno del ligamento ancho y sin dependencia del ovario ni del útero. ¿Cuál es el diagnóstico más compatible?", options:["Quiste folicular.","Endometrioma.","Quiste paraovárico.","Cistoadenocarcinoma mucinoso."], answer:2},
  {q:"Una paciente joven presenta una masa ovárica compleja con componentes hiperecogénicos que producen sombra acústica y atenuación del sonido. La lesión contiene tejidos derivados de diferentes capas embrionarias y su principal complicación es la torsión. ¿Cuál es el diagnóstico más probable?", options:["Endometrioma.","Quiste hemorrágico.","Teratoma maduro o quiste dermoide.","Cistoadenoma seroso."], answer:2}
];

window.topic40Questions = topic40Questions;

if (typeof window.registerCuratedTopicTest === 'function') {
  window.registerCuratedTopicTest(40, topic40Questions);
} else {
  window.curatedTests = window.curatedTests || {};
  window.curatedTests[40] = topic40Questions;
}
