// Banco curado del TEMA 17.
const topic17Curated = [
["¿Qué se considera una reacción adversa a un medio de contraste?",["Cualquier efecto que produzca el contraste, independientemente de su finalidad.","Cualquier efecto producido por el contraste que no corresponda a la mejora de la caracterización de los tejidos.","Únicamente las reacciones alérgicas graves.","Únicamente los efectos producidos por contrastes intravenosos."],1,"TEMA 17","medio","Una reacción adversa es un efecto no deseado del medio de contraste que no forma parte del objetivo buscado, como mejorar la caracterización de los tejidos. No se limita a las reacciones alérgicas ni a una vía concreta de administración."],
["La toxicidad celular directa de los contrastes intravenosos se relaciona principalmente con:",["La dosis y la osmolaridad del contraste.","La edad del paciente exclusivamente.","La vía oral de administración.","La presencia de alergias previas."],0,"TEMA 17","medio","La toxicidad directa depende especialmente de la cantidad administrada y de la osmolaridad del contraste. A mayor carga osmótica y exposición, mayor posibilidad de efectos directos sobre los tejidos."],
["¿Qué característica presentan las reacciones de hipersensibilidad a los medios de contraste?",["Son siempre proporcionales a la dosis administrada.","Son predecibles y aparecen únicamente con dosis elevadas.","No presentan una relación clara con la dosis y pueden ser impredecibles.","Se producen exclusivamente por toxicidad celular directa."],2,"TEMA 17","medio","Las reacciones de hipersensibilidad no siguen una relación dosis-respuesta clara como la toxicidad directa. Pueden aparecer de forma impredecible incluso sin que la dosis sea elevada."],
["¿Cuándo se consideran agudas las reacciones adversas no renales a los medios de contraste?",["Durante los primeros 10 minutos.","Durante la primera hora tras la administración.","Entre 1 hora y 1 semana.","Después de una semana."],1,"TEMA 17","fácil","Las reacciones agudas no renales son las que aparecen durante la primera hora tras la administración. Las que aparecen después se clasifican como tardías según el intervalo temporal establecido."],
["¿Cuál de las siguientes situaciones constituye un factor de riesgo del paciente para presentar una reacción adversa al contraste?",["Ausencia de antecedentes alérgicos.","Antecedentes de reacciones previas al contraste.","Edad inferior a 30 años exclusivamente.","Realización de una exploración sin contraste."],1,"TEMA 17","fácil","El antecedente más importante es haber presentado una reacción previa al mismo tipo de contraste o a un contraste. Este antecedente obliga a valorar cuidadosamente el riesgo y las alternativas."],
["Ante un paciente con elevado riesgo de reacción al contraste, ¿cuál de las siguientes medidas puede considerarse?",["Aumentar la dosis de contraste para reducir el riesgo.","Realizar siempre la exploración con contraste iónico de alta osmolaridad.","Valorar un estudio alternativo, otro tipo de contraste o premedicación con corticoides.","Evitar cualquier vigilancia posterior."],2,"TEMA 17","difícil","Cuando el riesgo es elevado, pueden valorarse alternativas como realizar la prueba sin contraste, utilizar otro medio de contraste o aplicar premedicación cuando esté indicada. La decisión depende del riesgo y del contexto clínico."],
["¿Cuándo aparecen generalmente las reacciones adversas tardías a los medios de contraste?",["Durante los primeros 30 minutos.","Entre 1 hora y 1 semana después de la administración.","Después de un año.","Exclusivamente durante las primeras 2 horas."],1,"TEMA 17","fácil","Las reacciones tardías suelen aparecer entre 1 hora y 1 semana después de la administración. Por eso la vigilancia y las instrucciones al paciente no terminan necesariamente al finalizar la exploración."],
["¿Cuál de las siguientes medidas puede utilizarse para tratar las reacciones adversas tardías leves o moderadas?",["Antihistamínicos orales.","Betabloqueantes.","Furosemida.","Nitroglicerina sublingual."],0,"TEMA 17","fácil","Las reacciones tardías cutáneas leves o moderadas pueden tratarse sintomáticamente con antihistamínicos orales. El tratamiento concreto siempre depende de la intensidad y de la manifestación clínica."],
["¿Qué alteración puede producirse como reacción muy tardía tras la administración de contraste yodado?",["Tirotoxicosis.","Hipoglucemia.","Hipotermia.","Bradicardia fisiológica."],0,"TEMA 17","medio","El yodo del contraste puede desencadenar alteraciones tiroideas en pacientes susceptibles, incluida la tirotoxicosis. Es un efecto muy tardío y distinto de las reacciones agudas de hipersensibilidad."],
["¿Cuál de los siguientes pacientes presenta mayor riesgo de fibrosis sistémica nefrogénica asociada al gadolinio?",["Paciente con función renal normal.","Paciente con insuficiencia renal crónica avanzada o en diálisis.","Paciente con alergia alimentaria leve.","Paciente con hipertensión arterial controlada."],1,"TEMA 17","medio","La fibrosis sistémica nefrogénica se ha relacionado especialmente con pacientes con insuficiencia renal grave, particularmente en estadios avanzados o en diálisis, tras la exposición a determinados agentes de gadolinio."],
["¿Cuál es el principal predictor de nefropatía inducida por contraste (NIC)?",["La presencia de disfunción renal previa.","La edad inferior a 30 años.","La ausencia de alergias.","La administración oral del contraste."],0,"TEMA 17","fácil","La función renal previa es uno de los factores fundamentales para valorar el riesgo renal asociado al contraste. Una disfunción renal previa aumenta la vulnerabilidad del paciente."],
["¿Cuál de las siguientes es una medida preventiva frente a la nefropatía inducida por contraste?",["Evitar la hidratación del paciente.","Utilizar la mayor dosis posible de contraste.","Evitar la deshidratación y utilizar contrastes de baja osmolaridad y menor dosis.","Administrar siempre contraste yodado de alta osmolaridad."],2,"TEMA 17","medio","La prevención busca reducir el estrés renal: evitar la deshidratación, utilizar la menor dosis necesaria y, cuando corresponda, contrastes de menor osmolaridad. No se debe administrar una cantidad de contraste superior a la necesaria."],
["Ante una extravasación de contraste, ¿cuál debe ser la primera actuación?",["Elevar inmediatamente el miembro.","Aplicar frío local.","Detener la administración del contraste.","Administrar antibióticos."],2,"TEMA 17","fácil","Lo primero es detener inmediatamente la administración para evitar que siga entrando contraste en los tejidos. Después se valora la extremidad y se aplican las medidas locales indicadas según el caso."],
["¿Cuál de los siguientes factores aumenta el riesgo de extravasación de contraste?",["Utilización de venas frágiles o lesionadas.","Administración mediante una vena de características normales.","Uso de pequeños volúmenes exclusivamente.","Ausencia de alteraciones circulatorias."],0,"TEMA 17","fácil","Las venas frágiles, lesionadas o de pequeño calibre tienen mayor riesgo de extravasación. También influyen otros factores relacionados con el acceso venoso y las características de la administración."],
["¿Qué recomendación es correcta respecto a la administración de contraste yodado en pacientes sometidos a hemodiálisis?",["Es necesario realizar una sesión adicional inmediatamente después.","Es necesario sincronizar siempre el estudio con la sesión de hemodiálisis.","No es necesario programar nuevas sesiones ni sincronizar el estudio con la hemodiálisis por este motivo.","Está absolutamente contraindicado administrar contraste yodado."],2,"TEMA 17","difícil","En un paciente en hemodiálisis, la administración de contraste yodado no obliga por sí misma a realizar una sesión adicional ni a modificar la programación habitual de diálisis. La decisión debe considerar el estado clínico global."],
["En relación con la metformina y los contrastes yodados, ¿qué situación aumenta el riesgo de acidosis láctica?",["La aparición de un fallo renal que favorezca la acumulación de lactato.","La administración de gadolinio.","La función renal normal.","La administración de cualquier contraste ecográfico."],0,"TEMA 17","medio","El problema con la metformina aparece cuando una alteración renal importante favorece su acumulación y aumenta el riesgo de acidosis láctica. Por eso la función renal es clave para decidir la conducta ante contraste yodado."],
["En una exploración programada, ¿qué se recomienda si la TFG se encuentra entre 30 y 44 mL/min en un paciente tratado con metformina?",["Mantener siempre la medicación sin ninguna consideración.","Suspender la metformina 48 horas antes y hasta 48 horas después.","Sustituirla por gadolinio.","Administrar una dosis doble de metformina."],1,"TEMA 17","difícil","Con la función renal reducida indicada en el material, la conducta recomendada es suspender temporalmente la metformina alrededor de la administración del contraste y reanudarla después según la reevaluación de la función renal."],
["¿Qué efecto pueden producir los contrastes yodados sobre las exploraciones con radioyodo?",["Aumentan la captación del radioyodo.","Reducen la captación del radioyodo y pueden interferir en su uso diagnóstico o terapéutico.","No producen ninguna interferencia.","Sustituyen al radioyodo en las gammagrafías."],1,"TEMA 17","medio","La carga de yodo del contraste puede disminuir temporalmente la captación del radioyodo por la tiroides. Por eso puede interferir con determinadas pruebas diagnósticas o tratamientos basados en radioyodo."],
["¿Qué precaución se recomienda con los contrastes yodados antes de una prueba diagnóstica o tratamiento con isótopos radiactivos?",["Esperar aproximadamente 2 meses.","Esperar únicamente 30 minutos.","Realizar la prueba inmediatamente después.","Esperar 24 horas en todos los casos."],0,"TEMA 17","medio","El material establece un intervalo aproximado de 2 meses para evitar la interferencia del yodo del contraste con determinadas pruebas o tratamientos con radioisótopos. El intervalo concreto puede depender del procedimiento."],
["¿Cuál de las siguientes afirmaciones sobre los contrastes hepatoespecíficos en RM es correcta?",["El manganeso no presenta ninguna contraindicación relacionada con el embarazo.","El óxido de hierro puede agravar la sobrecarga férrica en pacientes con hemosiderosis o hemocromatosis.","El gadolinio está contraindicado únicamente en pacientes con alergias alimentarias.","El óxido de hierro no puede producir reacciones de hipersensibilidad."],1,"TEMA 17","medio","Los contrastes basados en óxido de hierro pueden aumentar la carga férrica y deben valorarse con especial precaución en pacientes con hemosiderosis o hemocromatosis. La afirmación correcta relaciona el contraste con esa sobrecarga de hierro."]
];
window.topic17Curated = topic17Curated;

// El Tema 17 deja de participar en el banco automático de preguntas.
const previousBuildTopicBank17 = window.buildTopicBank;
window.buildTopicBank = function(){ return previousBuildTopicBank17().filter(q=>q[3]!=='TEMA 17'); };
