// Test curado del TEMA 38 · EXPLORACIÓN ECOGRÁFICA DEL RIÑÓN Y VEJIGA
const topic38Curated = [
  ["La ecografía renal y vesical presenta como una de sus principales limitaciones que:", ["Utiliza radiación ionizante", "Es una técnica dependiente del operador y requiere formación teórica y práctica", "Solo puede realizarse en pacientes hospitalizados", "No permite estudios en tiempo real"], 1, "TEMA 38", "medio", "La ecografía no utiliza radiación ionizante y permite obtener imágenes en tiempo real, pero la calidad del estudio y su correcta interpretación dependen mucho de la experiencia y formación del operador."],
  ["¿Qué aporta especialmente el Doppler en la exploración renal y vesical?", ["Solo permite medir el tamaño vesical", "Permite valorar cuantitativa y cualitativamente el flujo sanguíneo y visualizar el jet ureteral", "Sustituye siempre a la ecografía convencional", "Permite visualizar directamente todos los uréteres normales"], 1, "TEMA 38", "difícil", "El Doppler permite estudiar el flujo sanguíneo y también visualizar el jet ureteral, es decir, la salida de orina desde el uréter hacia la vejiga. No sustituye a la ecografía convencional ni permite seguir siempre todo el uréter normal."],
  ["¿Cuál es la localización anatómica habitual de los riñones?", ["Intraperitoneal, delante de la columna", "Retroperitoneal, a ambos lados de la columna y adosados a la pared abdominal posterior", "Exclusivamente pélvica", "Intratorácica"], 1, "TEMA 38", "fácil", "Los riñones son órganos retroperitoneales situados a ambos lados de la columna y adosados a la pared abdominal posterior."],
  ["La médula renal está constituida principalmente por:", ["Las columnas de Bertin", "Las pirámides renales", "La cápsula fibrosa", "La grasa del seno renal"], 1, "TEMA 38", "fácil", "La médula renal está formada principalmente por las pirámides renales. Las columnas de Bertin son prolongaciones de la corteza que se introducen entre ellas."],
  ["Respecto a las pirámides renales, señale la afirmación CORRECTA:", ["Son estructuras redondeadas cuyos vértices se dirigen hacia la corteza", "Son triangulares y sus vértices se proyectan hacia el seno renal formando las papilas", "Se localizan exclusivamente en la corteza", "Contienen directamente los cálices mayores en su interior"], 1, "TEMA 38", "medio", "Las pirámides renales tienen forma triangular y sus vértices se dirigen hacia el seno renal, donde forman las papilas renales por las que la orina pasa hacia los cálices."],
  ["Las columnas de Bertin corresponden a:", ["Extensiones de la médula que separan los cálices", "Extensiones de la corteza renal que se introducen entre las pirámides", "Estructuras vasculares del seno renal", "Restos embrionarios del uréter"], 1, "TEMA 38", "medio", "Las columnas de Bertin son prolongaciones de la corteza renal que se introducen entre las pirámides y las separan. Por tanto, forman parte del parénquima cortical."],
  ["¿Qué estructura NO forma parte del contenido habitual del seno renal?", ["Vasos renales", "Cálices y pelvis renal", "Nervios y linfáticos", "Parénquima cortical completo rodeando externamente al riñón"], 3, "TEMA 38", "difícil", "El seno renal contiene vasos, cálices, pelvis renal, nervios, linfáticos y grasa. El parénquima cortical constituye la periferia del riñón y no es el contenido habitual del seno."],
  ["Las arterias renales se originan habitualmente en:", ["La vena cava inferior", "La aorta abdominal", "Las arterias ilíacas internas", "La arteria mesentérica superior"], 1, "TEMA 38", "fácil", "Las arterias renales nacen habitualmente de la aorta abdominal. Las venas renales, en cambio, desembocan en la vena cava inferior."],
  ["¿Cuál de las siguientes relaciones vasculares es correcta?", ["La vena renal derecha suele ser más larga que la izquierda", "La vena renal izquierda pasa por debajo de la arteria mesentérica superior antes de llegar a la vena cava inferior", "Ambas venas renales desembocan en la vena porta", "La vena renal izquierda pasa por detrás de la vena cava inferior"], 1, "TEMA 38", "difícil", "La vena renal izquierda es más larga y pasa por debajo de la arteria mesentérica superior antes de desembocar en la vena cava inferior, formando la conocida pinza aortomesentérica."],
  ["El sistema colector urinario comienza en el riñón y continúa, en el orden correcto, por:", ["Papilas → cálices → pelvis renal → uréter → vejiga", "Papilas → pelvis renal → cálices → vejiga → uréter", "Cálices → papilas → pelvis renal → vejiga → uréter", "Papilas → uréter → cálices → pelvis renal → vejiga"], 0, "TEMA 38", "medio", "El recorrido de la orina es: papilas renales → cálices → pelvis renal → uréter → vejiga. Las papilas son el punto de salida de la orina desde las pirámides renales hacia el sistema colector."],
  ["El calibre aproximado descrito para el uréter normal es de:", ["0,5–1 mm", "2–8 mm", "10–15 mm", "15–20 mm"], 1, "TEMA 38", "fácil", "El material describe un calibre aproximado de 2–8 mm para el uréter normal. Es un conducto estrecho que lleva la orina desde la pelvis renal hasta la vejiga."],
  ["¿Dónde desembocan los uréteres en la vejiga?", ["En el vértice vesical", "En los ángulos laterales del trígono vesical, atravesando la pared vesical", "En el cuello vesical, por debajo de la uretra", "Directamente en la próstata"], 1, "TEMA 38", "medio", "Cada uréter atraviesa la pared vesical y desemboca en uno de los ángulos laterales del trígono vesical, formando los meatos ureterales."],
  ["En el varón, la vejiga urinaria se encuentra:", ["Por debajo de la próstata y detrás del recto", "Por encima de la próstata y por delante del recto y de las vesículas seminales", "Por delante del pubis y fuera de la pelvis", "Entre el útero y la vagina"], 1, "TEMA 38", "medio", "En el varón, la vejiga se sitúa por encima de la próstata y por delante del recto y de las vesículas seminales. En la mujer, se encuentra por delante del útero y la vagina."],
  ["Para conseguir una adecuada distensión vesical antes de la ecografía renal-vesical, la preparación indicada es:", ["No beber líquidos y orinar inmediatamente antes", "No orinar antes de la prueba y beber aproximadamente 1 litro de agua una hora antes", "Ayuno de 24 horas sin ingerir líquidos", "Beber 1 litro justo al iniciar la exploración y vaciar la vejiga después"], 1, "TEMA 38", "fácil", "Para obtener una buena ventana acústica vesical se indica no orinar antes de la prueba y beber aproximadamente 1 litro de agua una hora antes. El material también contempla unas 6 horas de ayuno para esta exploración."],
  ["Durante la exploración renal, una inspiración profunda mantenida puede ser útil porque:", ["Hace ascender los riñones hacia el tórax", "Permite que los riñones desciendan y facilita su visualización", "Elimina la grasa del seno renal", "Provoca el vaciamiento vesical"], 1, "TEMA 38", "medio", "La inspiración profunda desplaza los riñones hacia abajo, alejándolos parcialmente del reborde costal y facilitando su visualización ecográfica."],
  ["En la exploración ecográfica sistemática de los riñones, lo adecuado es:", ["Estudiarlos solo en un plano longitudinal", "Explorarlos en decúbito supino y posteriormente en ambos decúbitos laterales, con barrido completo", "Explorarlos únicamente en bipedestación", "Realizar exclusivamente imágenes Doppler"], 1, "TEMA 38", "medio", "La exploración renal debe ser sistemática y completa, utilizando el decúbito supino y los decúbitos laterales y realizando un barrido que permita valorar todo el órgano."],
  ["Como mínimo, para documentar las dimensiones de un riñón deben obtenerse medidas:", ["Solo longitudinales", "Longitudinal, anteroposterior y transversal", "Únicamente anteroposteriores", "Longitudinal y oblicua exclusivamente"], 1, "TEMA 38", "fácil", "Para valorar las dimensiones renales se obtienen medidas en los tres ejes: longitud, diámetro anteroposterior y diámetro transversal."],
  ["La exploración del uréter proximal se favorece especialmente mediante:", ["Una aproximación coronal oblicua utilizando el riñón como ventana acústica", "Una aproximación exclusivamente anterior a través de la vejiga", "Doppler color sin imagen B", "Una exploración transrectal obligatoria"], 0, "TEMA 38", "difícil", "El uréter proximal puede estudiarse mediante una aproximación coronal oblicua utilizando el riñón como ventana acústica. La vía a través de la vejiga resulta especialmente útil para valorar el extremo distal."],
  ["¿Por qué suele ser difícil seguir ecográficamente un uréter normal hasta la vejiga?", ["Porque el uréter normal contiene aire", "Por la interposición del gas intestinal, salvo cuando el uréter está dilatado", "Porque carece de paredes", "Porque solo puede estudiarse mediante resonancia"], 1, "TEMA 38", "medio", "El gas intestinal puede dificultar la visualización continua del uréter normal. Cuando el uréter está dilatado, resulta mucho más sencillo seguirlo ecográficamente."],
  ["El meato ureteral puede identificarse especialmente bien mediante:", ["Un corte transversal del suelo vesical", "Un corte longitudinal exclusivo del riñón derecho", "Una imagen del polo superior renal", "Una exploración Doppler de la aorta"], 0, "TEMA 38", "medio", "Los meatos ureterales se localizan en los ángulos laterales del trígono y pueden identificarse especialmente bien mediante un corte transversal del suelo vesical."],
  ["El jet ureteral observado con Doppler color representa:", ["El flujo sanguíneo de la arteria renal", "La llegada de orina desde el uréter a la vejiga", "El movimiento de la pared vesical", "El flujo venoso de la pelvis renal"], 1, "TEMA 38", "medio", "El jet ureteral es la salida de orina desde el uréter hacia la vejiga. Puede visualizarse con Doppler y permite comprobar que existe flujo urinario hacia el interior vesical."],
  ["La visualización del jet ureteral mediante Doppler color permite afirmar fundamentalmente que:", ["Existe una obstrucción completa del uréter", "No existe una obstrucción total al paso de orina por ese uréter", "El riñón presenta siempre una función normal", "La vejiga está vacía"], 1, "TEMA 38", "difícil", "Si se visualiza el jet ureteral significa que existe paso de orina desde ese uréter hasta la vejiga, por lo que no hay una obstrucción total en ese momento. No implica por sí solo que toda la función renal sea normal."],
  ["Si una vejiga excesivamente llena hace que el sistema colector renal parezca dilatado, la conducta adecuada es:", ["Diagnosticar inmediatamente hidronefrosis", "Explorar primero la vejiga y continuar el estudio renal después de su vaciamiento", "Suspender siempre la exploración", "Realizar únicamente una radiografía simple"], 1, "TEMA 38", "difícil", "Una vejiga excesivamente distendida puede modificar la apariencia del sistema colector. Por eso conviene valorar la vejiga y repetir la evaluación renal después de vaciarla antes de diagnosticar una hidronefrosis."],
  ["La elevada ecogenicidad del seno renal se debe principalmente a:", ["La presencia de líquido urinario", "La grasa que contiene", "La presencia de pirámides hiperecogénicas", "La ausencia de vasos"], 1, "TEMA 38", "medio", "El seno renal aparece hiperecogénico principalmente por la abundante grasa que contiene alrededor de los vasos y de las estructuras del sistema colector."],
  ["En ecografía, las pirámides renales normales suelen observarse como estructuras:", ["Triangulares e hipoecoicas respecto al seno renal", "Redondas e hiperecogénicas respecto a la corteza", "Anecoicas y comunicadas con la vejiga", "Hiperecogénicas por contener grasa"], 0, "TEMA 38", "medio", "Las pirámides renales tienen forma triangular y suelen ser hipoecogénicas respecto al seno renal. Su reconocimiento ayuda a identificar la arquitectura normal del parénquima renal."],
  ["Una imagen anecoica dentro del seno renal:", ["Demuestra siempre una hidronefrosis", "Puede corresponder a líquido en vasos renales o en el sistema colector y no debe interpretarse automáticamente como dilatación", "Es necesariamente un tumor sólido", "Solo puede corresponder a un quiste renal simple cortical"], 1, "TEMA 38", "difícil", "Una imagen anecoica en el seno renal no significa automáticamente hidronefrosis. Puede corresponder a vasos o a estructuras del sistema colector, por lo que hay que valorar su localización y utilizar Doppler si existe duda."],
  ["Ante imágenes anecoicas en el seno renal cuya naturaleza no está clara, el Doppler resulta especialmente útil para:", ["Demostrar la presencia de grasa", "Diferenciar estructuras vasculares de una posible dilatación del sistema colector", "Medir el volumen renal", "Diagnosticar siempre un carcinoma"], 1, "TEMA 38", "difícil", "El Doppler permite identificar el flujo dentro de los vasos y ayuda a distinguir una estructura vascular de una posible dilatación del sistema colector, evitando errores diagnósticos."],
  ["La hipertrofia de una columna de Bertin puede plantear un diagnóstico diferencial con:", ["Una litiasis vesical", "Un tumor renal", "Una infección urinaria baja exclusivamente", "Una obstrucción uretral"], 1, "TEMA 38", "medio", "La hipertrofia de la columna de Bertin es una variante anatómica normal que puede formar una prominencia del parénquima y simular una masa o tumor renal."],
  ["¿Qué característica favorece que una imagen corresponda a una hipertrofia de columna de Bertin y no a un tumor renal verdadero?", ["No tiene continuidad con el parénquima renal", "Presenta continuidad con el resto del parénquima renal y mantiene características similares", "Siempre presenta una cápsula propia", "Produce necesariamente sombra acústica"], 1, "TEMA 38", "difícil", "La columna de Bertin forma parte de la corteza renal, por lo que mantiene continuidad con el parénquima y características ecográficas similares. Esa continuidad ayuda a reconocerla como pseudolesión."],
  ["En una hipertrofia de columna de Bertin, el diámetro descrito como característico es:", ["Siempre superior a 5 cm", "Inferior a 3 cm", "Entre 5 y 8 cm", "No existe ningún límite orientativo"], 1, "TEMA 38", "difícil", "El material de estudio describe como característica una hipertrofia de columna de Bertin de diámetro inferior a 3 cm. Este dato debe valorarse junto con la continuidad con la corteza y el resto de características ecográficas."],
  ["Ante la duda entre una pseudolesión renal y un tumor, en ecografía con contraste una pseudolesión como la hipertrofia de columna de Bertin tiende a:", ["Realzar de forma similar al parénquima renal", "No presentar nunca realce", "Realzar de forma completamente distinta al parénquima", "Mostrar siempre calcificación"], 0, "TEMA 38", "difícil", "Una hipertrofia de columna de Bertin pertenece al propio parénquima renal, por lo que con contraste tiende a realzar de forma similar al resto del tejido renal. Esto ayuda a diferenciarla de una masa verdadera."],
  ["¿Cuál de los siguientes conjuntos de criterios es compatible con un quiste renal simple?", ["Redondeado, bien delimitado, pared lisa y totalmente anecoico", "Pared irregular, ecos internos y septos gruesos", "Sólido, hiperecogénico y con sombra posterior", "Mal delimitado y con vascularización interna"], 0, "TEMA 38", "medio", "Un quiste renal simple es una lesión redondeada, bien delimitada, de pared lisa y contenido anecoico. Al contener líquido, puede producir además refuerzo acústico posterior."],
  ["La enfermedad renal poliquística se caracteriza por:", ["Un único quiste unilateral sin repercusión", "Múltiples quistes que sustituyen progresivamente el parénquima, con aumento renal y afectación bilateral", "Una infección aguda del sistema colector", "La presencia exclusiva de quistes vesicales"], 1, "TEMA 38", "medio", "La poliquistosis renal se caracteriza por múltiples quistes, habitualmente bilaterales, que sustituyen progresivamente parte del parénquima renal. Puede producir aumento del tamaño renal y acabar causando insuficiencia renal."],
  ["La pionefrosis debe considerarse especialmente grave porque consiste en:", ["Una infección supurada del sistema excretor asociada previamente a una obstrucción", "Un quiste renal simple asintomático", "Una inflamación aislada de la vejiga", "Una hipertrofia benigna de la columna de Bertin"], 0, "TEMA 38", "difícil", "La pionefrosis combina infección y obstrucción del sistema urinario, con acumulación de material purulento. Por esta asociación constituye una situación grave y una urgencia médica."],
  ["En un varón con dificultad para la micción, una vejiga de esfuerzo se caracteriza típicamente por:", ["Pared fina y completamente regular", "Pared engrosada e irregular, pudiendo asociar divertículos", "Ausencia de pared visible", "Vejiga siempre colapsada"], 1, "TEMA 38", "medio", "La vejiga de esfuerzo aparece habitualmente en el contexto de una obstrucción urinaria crónica. La pared se engrosa y puede hacerse irregular, y pueden aparecer divertículos por el aumento mantenido de presión durante la micción."]
];

window.topic38Curated = topic38Curated;

const previousTopicMenu38 = window.topicMenu;
window.topicMenu = function(){
  previousTopicMenu38();
  if(!ws || ws.hidden) return;
  const cards = ws.querySelector('.cards');
  if(!cards) return;
  const existing = [...cards.querySelectorAll('button.module-card')].find(b => (b.textContent || '').includes('TEMA 38'));
  if(existing){
    existing.disabled = false;
    existing.innerHTML = `<span class="module-number">TEMA 38</span><h3>${esc((topics[38]||{}).title||'TEMA 38')}</h3><p>${topic38Curated.length} preguntas · riñón y vejiga</p><span class="module-action">Entrenar →</span>`;
    existing.onclick = () => session('TEMA 38', topic38Curated);
    return;
  }
  const button = document.createElement('button');
  button.className = 'module-card';
  button.type = 'button';
  button.innerHTML = `<span class="module-number">TEMA 38</span><h3>${esc((topics[38]||{}).title||'TEMA 38')}</h3><p>${topic38Curated.length} preguntas · riñón y vejiga</p><span class="module-action">Entrenar →</span>`;
  button.onclick = () => session('TEMA 38', topic38Curated);
  const before = [...cards.querySelectorAll('button.module-card')].find(b => { const m=(b.textContent||'').match(/TEMA\s+(\d+)/); return m && Number(m[1]) > 38; });
  if(before) cards.insertBefore(button,before); else cards.appendChild(button);
};